SELECT
PO.PO_LINE_ID AS PO_LINE_ID
,PO.STATUS AS STATUS
,STATUSCAT.CATEGORY_CODE_NAME AS DISP_STATUS
,PO.PO_SLIP_ID AS PO_SLIP_ID
,PO.LINE_NO AS LINE_NO
,PO.PRODUCT_CODE AS PRODUCT_CODE
,PO.SUPPLIER_PCODE AS SUPPLIER_PCODE
,PO.PRODUCT_ABSTRACT AS PRODUCT_ABSTRACT
,PO.QUANTITY AS QUANTITY
,PRODMST.PO_LOT AS PO_LOT
,PRODMST.MAX_PO_NUM AS MAX_PO_NUM
,PRODMST.MAX_STOCK_NUM AS MAX_STOCK_NUM
,PRODMST.RACK_CODE AS RACK_CODE
,PO.TEMP_UNIT_PRICE_CATEGORY AS TEMP_UNIT_PRICE_CATEGORY
,PO.TAX_CATEGORY AS TAX_CATEGORY
,PO.SUPPLIER_CM_CATEGORY AS SUPPLIER_CM_CATEGORY
,PO.UNIT_PRICE AS UNIT_PRICE
,PO.PRICE AS PRICE
,PO.CTAX_PRICE AS CTAX_PRICE
,PO.CTAX_RATE AS CTAX_RATE
,PO.DOL_UNIT_PRICE AS DOL_UNIT_PRICE
,PO.DOL_PRICE AS DOL_PRICE
,PO.RATE AS RATE
,PO.DELIVERY_DATE AS DELIVERY_DATE
,PO.REMARKS AS REMARKS
,PO.PRODUCT_REMARKS AS PRODUCT_REMARKS
,PO.REST_QUANTITY AS REST_QUANTITY
,PO.CRE_FUNC AS CRE_FUNC
,PO.CRE_DATETM AS CRE_DATETM
,PO.CRE_USER AS CRE_USER
,PO.UPD_FUNC AS UPD_FUNC
,PO.UPD_DATETM AS UPD_DATETM
,PO.UPD_USER AS UPD_USER
FROM
		PO_LINE_TRN_/*$domainId*/ PO
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ STATUSCAT
			ON STATUSCAT.CATEGORY_ID = /*poLineStatusCategory*/
			AND STATUSCAT.CATEGORY_CODE = PO.STATUS
		LEFT OUTER JOIN PRODUCT_MST_/*$domainId*/ PRODMST
			ON PRODMST.PRODUCT_CODE = PO.PRODUCT_CODE
	WHERE
		PO.PO_SLIP_ID=/*poSlipId*/
	ORDER BY
		PO.LINE_NO ASC
