SELECT
PS.PO_SLIP_ID				AS PO_SLIP_ID
,PS.PO_DATE					AS PO_DATE
,PS.SUPPLIER_NAME			AS SUPPLIER_NAME
,PS.SUPPLIER_DEPT_NAME		AS SUPPLIER_DEPT_NAME
,PS.SUPPLIER_PC_POST		AS SUPPLIER_PC_POST
,PS.SUPPLIER_PC_NAME		AS SUPPLIER_PC_NAME
,PS.SUPPLIER_PC_PRE			AS SUPPLIER_PC_PRE
,PS.SUPPLIER_TEL			AS SUPPLIER_TEL
,PS.SUPPLIER_FAX			AS SUPPLIER_FAX

,PS.DELIVERY_DATE			AS DELIVERY_DATE
,PS.REMARKS					AS REMARKS

,CASE WHEN PS.RATE_ID IS NULL THEN PS.PRICE_TOTAL
 ELSE PS.FE_PRICE_TOTAL END 						AS FE_PRICE_TOTAL
,PS.CTAX_TOTAL					AS CTAX_TOTAL
,RMST.SIGN					AS SIGN
,S.FOB_NAME					AS FOB_NAME

FROM
		PO_SLIP_TRN_/*$domainId*/ PS
		LEFT OUTER JOIN RATE_MST_/*$domainId*/ RMST
			ON RMST.RATE_ID = PS.RATE_ID
		LEFT OUTER JOIN SUPPLIER_MST_/*$domainId*/ S
			ON PS.SUPPLIER_CODE = S.SUPPLIER_CODE
	WHERE
		PO_SLIP_ID=/*poSlipId*/
