SELECT
	(SELECT PL.DELIVERY_DATE FROM PO_LINE_TRN_/*$domainId*/ PL INNER JOIN PO_SLIP_TRN_/*$domainId*/ PS ON PL.PO_SLIP_ID = PS.PO_SLIP_ID WHERE PL.PRODUCT_CODE=P.PRODUCT_CODE AND PS.TRANSPORT_CATEGORY <> '3' AND PL.STATUS <> '9' AND PL.REST_QUANTITY <> 0 ORDER BY PL.DELIVERY_DATE ASC LIMIT 1) AS PURCHASE_DATE_1,
	(SELECT PL.REST_QUANTITY FROM PO_LINE_TRN_/*$domainId*/ PL INNER JOIN PO_SLIP_TRN_/*$domainId*/ PS ON PL.PO_SLIP_ID = PS.PO_SLIP_ID WHERE PL.PRODUCT_CODE=P.PRODUCT_CODE AND PS.TRANSPORT_CATEGORY <> '3' AND PL.STATUS <> '9' AND PL.REST_QUANTITY <> 0 ORDER BY PL.DELIVERY_DATE ASC LIMIT 1) AS PURCHASE_NUM_1,
	(SELECT PL.DELIVERY_DATE FROM PO_LINE_TRN_/*$domainId*/ PL INNER JOIN PO_SLIP_TRN_/*$domainId*/ PS ON PL.PO_SLIP_ID = PS.PO_SLIP_ID WHERE PL.PRODUCT_CODE=P.PRODUCT_CODE AND PS.TRANSPORT_CATEGORY <> '3' AND PL.STATUS <> '9' AND PL.REST_QUANTITY <> 0 ORDER BY PL.DELIVERY_DATE ASC LIMIT 1 OFFSET 1) AS PURCHASE_DATE_2,
	(SELECT PL.REST_QUANTITY FROM PO_LINE_TRN_/*$domainId*/ PL INNER JOIN PO_SLIP_TRN_/*$domainId*/ PS ON PL.PO_SLIP_ID = PS.PO_SLIP_ID WHERE PL.PRODUCT_CODE=P.PRODUCT_CODE AND PS.TRANSPORT_CATEGORY <> '3' AND PL.STATUS <> '9' AND PL.REST_QUANTITY <> 0 ORDER BY PL.DELIVERY_DATE ASC LIMIT 1 OFFSET 1) AS PURCHASE_NUM_2
FROM
	PRODUCT_MST_/*$domainId*/ P
/*BEGIN*/
WHERE
	/*IF productCode != null*/
	P.PRODUCT_CODE = /*productCode*/'0'
	/*END*/
/*END*/
ORDER BY
	P.PRODUCT_CODE
