SELECT
		PO.PO_SLIP_ID		AS PO_SLIP_ID

		,CASE WHEN ( PO.STATUS <> /*statusPorderSlipPurchased*/'9' -- 仕入完了：Constants.STATUS_PORDER_SLIP.PURCHASED じゃない。
				OR COALESCE(UNPAIDSUPPSLIP.UNPAIDSUPPSLIPCOUNT, 0) > 0 )
			THEN /*slipPaymentStatusUnpaid*/
			ELSE /*slipPaymentStatusPaid*/ END	AS PAYMENT_STATUS

		,PAY.PAYMENT_DATE	AS PAYMENT_DATE
FROM
		PO_SLIP_TRN_/*$domainId*/ PO

		LEFT OUTER JOIN (
			SELECT
				COUNT(DISTINCT SUPPSLIP.PO_SLIP_ID) AS UNPAIDSUPPSLIPCOUNT
				,SUPPSLIP.PO_SLIP_ID AS PO_SLIP_ID
					FROM SUPPLIER_SLIP_TRN_/*$domainId*/ SUPPSLIP
				WHERE SUPPSLIP.STATUS = /*statusSupplierSlipUnpaid*/'0' -- 未払い：Constants.STATUS_SUPPLIER_SLIP.UNPAID
				GROUP BY
					SUPPSLIP.PO_SLIP_ID
		) UNPAIDSUPPSLIP
				ON PO.PO_SLIP_ID = UNPAIDSUPPSLIP.PO_SLIP_ID
				AND PO.STATUS = /*statusPorderSlipPurchased*/'9' -- 仕入完了：Constants.STATUS_PORDER_SLIP.PURCHASED

		LEFT OUTER JOIN PAYMENT_SLIP_TRN_/*$domainId*/ PAY
				ON PO.PO_SLIP_ID = PAY.PO_SLIP_ID

	WHERE
		PO.PO_SLIP_ID=/*poSlipId*/
	ORDER BY
		PAYMENT_DATE DESC LIMIT 1
