SELECT
	SLIP.PO_SLIP_ID			AS PO_SLIP_ID
	,SLIP.STATUS			AS STATUS
	,SLIP.PO_DATE			AS PO_DATE
	,SLIP.PO_ANNUAL			AS PO_ANNUAL
	,SLIP.PO_MONTHLY		AS PO_MONTHLY
	,SLIP.PO_YM				AS PO_YM
	,SLIP.DELIVERY_DATE		AS DELIVERY_DATE
	,SLIP.USER_ID			AS USER_ID
	,SLIP.USER_NAME			AS USER_NAME
	,SLIP.REMARKS			AS REMARKS
	,SLIP.SUPPLIER_CODE		AS SUPPLIER_CODE
	,SLIP.SUPPLIER_NAME		AS SUPPLIER_NAME
	,SLIP.SUPPLIER_KANA		AS SUPPLIER_KANA
	,SLIP.SUPPLIER_ABBR		AS SUPPLIER_ABBR
	,SLIP.SUPPLIER_ZIP_CODE	AS SUPPLIER_ZIP_CODE
	,SLIP.SUPPLIER_ADDRESS_1	AS SUPPLIER_ADDRESS_1
	,SLIP.SUPPLIER_ADDRESS_2	AS SUPPLIER_ADDRESS_2
	,SLIP.SUPPLIER_DEPT_NAME	AS SUPPLIER_DEPT_NAME
	,SLIP.SUPPLIER_PC_NAME		AS SUPPLIER_PC_NAME
	,SLIP.SUPPLIER_PC_KANA		AS SUPPLIER_PC_KANA
	,SLIP.SUPPLIER_PC_PRE_CATEGORY	AS SUPPLIER_PC_PRE_CATEGORY
	,SLIP.SUPPLIER_PC_PRE		AS SUPPLIER_PC_PRE
	,SLIP.SUPPLIER_PC_POST		AS SUPPLIER_PC_POST
	,SLIP.SUPPLIER_TEL			AS SUPPLIER_TEL
	,SLIP.SUPPLIER_FAX			AS SUPPLIER_FAX
	,SLIP.SUPPLIER_EMAIL		AS SUPPLIER_EMAIL
	,SLIP.SUPPLIER_URL			AS SUPPLIER_URL
	,SLIP.SUPPLIER_CM_CATEGORY	AS SUPPLIER_CM_CATEGORY
	,SLIP.TAX_SHIFT_CATEGORY	AS TAX_SHIFT_CATEGORY
	,SLIP.TRANSPORT_CATEGORY	AS TRANSPORT_CATEGORY
	,SLIP.TAX_FRACT_CATEGORY	AS TAX_FRACT_CATEGORY
	,SLIP.PRICE_FRACT_CATEGORY	AS PRICE_FRACT_CATEGORY
	,SLIP.RATE_ID				AS RATE_ID
	,SLIP.PRICE_TOTAL			AS PRICE_TOTAL
	,SLIP.CTAX_TOTAL			AS CTAX_TOTAL
	,SLIP.CTAX_RATE				AS CTAX_RATE
	,SLIP.FE_PRICE_TOTAL		AS FE_PRICE_TOTAL
	,SLIP.PRINT_COUNT			AS PRINT_COUNT

	,SLIP.CRE_FUNC				AS CRE_FUNC
	,SLIP.CRE_DATETM			AS CRE_DATETM
	,SLIP.CRE_USER				AS CRE_USER
	,SLIP.UPD_FUNC				AS UPD_FUNC
	,SLIP.UPD_DATETM			AS UPD_DATETM
	,SLIP.UPD_USER				AS UPD_USER

	,LINE1.RATE					AS SUPPLIER_RATE

FROM
		PO_SLIP_TRN_/*$domainId*/ SLIP
		INNER JOIN(
			SELECT
				LINE.PO_SLIP_ID		AS PO_SLIP_ID
				,LINE.RATE			AS RATE
				,LINE.CTAX_RATE		AS CTAX_RATE
			FROM PO_LINE_TRN_/*$domainId*/ LINE
			WHERE LINE.PO_SLIP_ID =/*poSlipId*/
			ORDER BY LINE_NO ASC LIMIT 1
		) LINE1
			ON LINE1.PO_SLIP_ID = SLIP.PO_SLIP_ID
	WHERE
		SLIP.PO_SLIP_ID = /*poSlipId*/
