INSERT INTO DELIVERY_MST_/*$domainId*/
(
DELIVERY_CODE
,DELIVERY_NAME
,DELIVERY_KANA
,DELIVERY_OFFICE_NAME
,DELIVERY_OFFICE_KANA
,DELIVERY_DEPT_NAME
,DELIVERY_ZIP_CODE
,DELIVERY_ADDRESS_1
,DELIVERY_ADDRESS_2
,DELIVERY_PC_NAME
,DELIVERY_PC_KANA
,DELIVERY_PC_PRE_CATEGORY
,DELIVERY_TEL
,DELIVERY_FAX
,DELIVERY_EMAIL
,DELIVERY_URL
,REMARKS
,CRE_FUNC
,CRE_DATETM
,CRE_USER
,UPD_FUNC
,UPD_DATETM
,UPD_USER
)
VALUES
(
/*deliveryCode*/
,/*deliveryName*/
,/*deliveryKana*/
,/*deliveryOfficeName*/
,/*deliveryOfficeKana*/
,/*deliveryDeptName*/
,/*deliveryZipCode*/
,/*deliveryAddress1*/
,/*deliveryAddress2*/
,/*deliveryPcName*/
,/*deliveryPcKana*/
,/*deliveryPcPreCategory*/
,/*deliveryTel*/
,/*deliveryFax*/
,/*deliveryEmail*/
,/*deliveryUrl*/
,/*remarks*/
,/*creFunc*/
,now()
,/*creUser*/
,/*updFunc*/
,now()
,/*updUser*/
)