SELECT
	RO_LINE.RO_SLIP_ID
	,RO_LINE.LINE_NO
	,RO_SLIP.SHIP_DATE
	,RO_LINE.QUANTITY - IFNULL(SX.QUANTITY,0) AS REST_QUANTITY
FROM
	RO_SLIP_TRN_/*$domainId*/ RO_SLIP
	INNER JOIN RO_LINE_TRN_/*$domainId*/ RO_LINE ON RO_SLIP.RO_SLIP_ID = RO_LINE.RO_SLIP_ID
	LEFT OUTER JOIN
	(
		SELECT
			SL.PRODUCT_CODE AS PRODUCT_CODE
			,SL.RO_LINE_ID AS RO_LINE_ID
			,SUM(SL.QUANTITY) AS QUANTITY
		FROM
			SALES_SLIP_TRN_/*$domainId*/ SS
			INNER JOIN SALES_LINE_TRN_/*$domainId*/ SL ON SS.SALES_SLIP_ID = SL.SALES_SLIP_ID
		WHERE
			SS.SALES_DATE <= CURDATE()
	    	AND SL.PRODUCT_CODE = /*productCode*/'A'
		GROUP BY SL.PRODUCT_CODE,SL.RO_LINE_ID
	) SX ON RO_LINE.PRODUCT_CODE = SX.PRODUCT_CODE AND RO_LINE.RO_LINE_ID = SX.RO_LINE_ID
WHERE
	RO_LINE.QUANTITY - IFNULL(SX.QUANTITY,0) > 0
	AND RO_LINE.PRODUCT_CODE = /*productCode*/'A'
/*IF setProductCode != null*/
UNION ALL
SELECT
	RO_LINE.RO_SLIP_ID
	,RO_LINE.LINE_NO
	,RO_SLIP.SHIP_DATE
	,(RO_LINE.QUANTITY - IFNULL(SX.QUANTITY,0)) * PS.QUANTITY AS REST_QUANTITY
FROM
	RO_SLIP_TRN_/*$domainId*/ RO_SLIP
	INNER JOIN RO_LINE_TRN_/*$domainId*/ RO_LINE ON RO_SLIP.RO_SLIP_ID = RO_LINE.RO_SLIP_ID
	INNER JOIN PRODUCT_SET_MST_/*$domainId*/ PS ON RO_LINE.PRODUCT_CODE = PS.SET_PRODUCT_CODE AND PS.PRODUCT_CODE =  /*productCode*/'A'
	LEFT OUTER JOIN
	(
		SELECT
			SL.PRODUCT_CODE AS PRODUCT_CODE
			,SL.RO_LINE_ID AS RO_LINE_ID
			,SUM(SL.QUANTITY) AS QUANTITY
		FROM
			SALES_SLIP_TRN_/*$domainId*/ SS
			INNER JOIN SALES_LINE_TRN_/*$domainId*/ SL ON SS.SALES_SLIP_ID = SL.SALES_SLIP_ID
		WHERE
			SS.SALES_DATE <= CURDATE()
	    	AND SL.PRODUCT_CODE IN /*setProductCode*/('BBB','XXX')
		GROUP BY SL.PRODUCT_CODE,SL.RO_LINE_ID
	) SX ON RO_LINE.PRODUCT_CODE = SX.PRODUCT_CODE AND RO_LINE.RO_LINE_ID = SX.RO_LINE_ID
WHERE
	RO_LINE.QUANTITY - IFNULL(SX.QUANTITY,0) > 0
	AND RO_LINE.PRODUCT_CODE IN /*setProductCode*/('BBB','XXX')
/*END*/
ORDER BY
	RO_SLIP_ID
	,LINE_NO