SELECT	PO_LINE.PO_SLIP_ID,PO_LINE.LINE_NO,EE_SLIP.ENTRUST_EAD_DATE,EE_LINE.QUANTITY
FROM	ENTRUST_EAD_SLIP_TRN_/*$domainId*/ EE_SLIP
		INNER JOIN ENTRUST_EAD_LINE_TRN_/*$domainId*/ EE_LINE ON EE_SLIP.ENTRUST_EAD_SLIP_ID = EE_LINE.ENTRUST_EAD_SLIP_ID
		INNER JOIN PO_LINE_TRN_/*$domainId*/ PO_LINE ON EE_LINE.PO_LINE_ID = PO_LINE.PO_LINE_ID
WHERE	EE_LINE.ENTRUST_EAD_CATEGORY = '1'
AND		EE_LINE.REL_ENTRUST_EAD_LINE_ID IS NULL
AND		EE_LINE.PRODUCT_CODE = /*productCode*/'A'
ORDER BY PO_LINE.PO_SLIP_ID,PO_LINE.LINE_NO
