SELECT	PO_LINE.PO_SLIP_ID,PO_LINE.LINE_NO,PO_SLIP.PO_DATE,PO_LINE.DELIVERY_DATE,PO_LINE.REST_QUANTITY
FROM	PO_SLIP_TRN_/*$domainId*/ PO_SLIP
		INNER JOIN PO_LINE_TRN_/*$domainId*/ PO_LINE ON PO_SLIP.PO_SLIP_ID = PO_LINE.PO_SLIP_ID
WHERE	PO_LINE.STATUS NOT IN ('2','3','9')
AND		PO_LINE.PRODUCT_CODE = /*productCode*/'A'
AND		PO_SLIP.TRANSPORT_CATEGORY = '3'
ORDER BY PO_LINE.PO_SLIP_ID,PO_LINE.LINE_NO
