SELECT
        S.SUPPLIER_CODE
        ,S.SUPPLIER_NAME
        ,S.SUPPLIER_KANA
        ,S.SUPPLIER_ABBR
        ,S.SUPPLIER_ZIP_CODE
        ,S.SUPPLIER_ADDRESS_1
        ,S.SUPPLIER_ADDRESS_2
        ,S.SUPPLIER_DEPT_NAME
        ,S.SUPPLIER_PC_NAME
        ,S.SUPPLIER_PC_KANA
        ,S.SUPPLIER_PC_PRE_CATEGORY
        ,PRECAT.CATEGORY_CODE_NAME AS SUPPLIER_PC_PRE
        ,S.SUPPLIER_PC_POST
        ,S.SUPPLIER_TEL
        ,S.SUPPLIER_FAX
        ,S.SUPPLIER_EMAIL
        ,S.SUPPLIER_URL
        ,S.SUPPLIER_CM_CATEGORY
        ,S.TAX_SHIFT_CATEGORY
        ,S.PAYMENT_TYPE_CATEGORY
        ,S.PAYMENT_CYCLE_CATEGORY
        ,S.LAST_CUTOFF_DATE
        ,S.PAYMENT_DATE
        ,CASE WHEN TAXFCAT.CATEGORY_CODE IS NULL
               THEN MINE.TAX_FRACT_CATEGORY
               ELSE TAXFCAT.CATEGORY_CODE
                                   END AS TAX_FRACT_CATEGORY
        ,CASE WHEN PRIFCAT.CATEGORY_CODE IS NULL
               THEN MINE.PRICE_FRACT_CATEGORY
               ELSE PRIFCAT.CATEGORY_CODE
                                   END AS PRICE_FRACT_CATEGORY
        ,MINE.UNIT_PRICE_DEC_ALIGNMENT AS DOL_UNIT_PRICE_DEC_ALIGNMENT
        ,0                             AS UNIT_PRICE_DEC_ALIGNMENT
        ,0                             AS TAX_PRICE_DEC_ALIGNMENT
        ,S.PO_SLIP_COMEOUT_CATEGORY
        ,S.SERVICE_CHARGE_CATEGORY
        ,S.TRANSFER_TYPE_CATEGORY
        ,S.NATIONAL_CATEGORY
        ,S.RATE_ID
        ,R.NAME AS SUPPLIER_RATE_NAME
        ,S.FOB_NAME
        ,S.REMARKS
        ,S.COMMENT_DATA
        ,S.CRE_DATETM
        ,S.UPD_DATETM
        ,S.UPD_USER
        ,R.SIGN AS C_UNIT_SIGN
    FROM
        SUPPLIER_MST_/*$domainId*/ S
        LEFT OUTER JOIN RATE_MST_/*$domainId*/ R
        	ON S.RATE_ID = R.RATE_ID
        LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ PRECAT
        	ON PRECAT.CATEGORY_ID = /*preTypeCategoryId*/
        	AND PRECAT.CATEGORY_CODE = S.SUPPLIER_PC_PRE_CATEGORY
        LEFT OUTER JOIN MINE_MST_/*$domainId*/ MINE
        	ON COMPANY_NAME IS NOT NULL
        LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ TAXFCAT
        	ON TAXFCAT.CATEGORY_ID = /*taxFractCategoryId*/
        	AND S.TAX_FRACT_CATEGORY = TAXFCAT.CATEGORY_CODE
        LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ PRIFCAT
        	ON PRIFCAT.CATEGORY_ID = /*priceFractCategoryId*/
        	AND S.PRICE_FRACT_CATEGORY = PRIFCAT.CATEGORY_CODE
	WHERE
		S.SUPPLIER_CODE=/*supplierCode*/''
