INSERT INTO SUPPLIER_MST_/*$domainId*/ (
	SUPPLIER_CODE
	,SUPPLIER_NAME
	,SUPPLIER_KANA
	,SUPPLIER_ABBR
	,SUPPLIER_ZIP_CODE
	,SUPPLIER_ADDRESS_1
	,SUPPLIER_ADDRESS_2
	,SUPPLIER_DEPT_NAME
	,SUPPLIER_PC_NAME
	,SUPPLIER_PC_KANA
	,SUPPLIER_PC_PRE_CATEGORY
	,SUPPLIER_PC_POST
	,SUPPLIER_TEL
	,SUPPLIER_FAX
	,SUPPLIER_EMAIL
	,SUPPLIER_URL
	,SUPPLIER_CM_CATEGORY
	,TAX_SHIFT_CATEGORY
	,PAYMENT_TYPE_CATEGORY
	,PAYMENT_CYCLE_CATEGORY
	,LAST_CUTOFF_DATE
	,PAYMENT_DATE
	,TAX_FRACT_CATEGORY
	,PRICE_FRACT_CATEGORY
	,PO_SLIP_COMEOUT_CATEGORY
	,SERVICE_CHARGE_CATEGORY
	,TRANSFER_TYPE_CATEGORY
	,NATIONAL_CATEGORY
	,RATE_ID
	,FOB_NAME
	,REMARKS
	,COMMENT_DATA
	,CRE_FUNC
	,CRE_DATETM
	,CRE_USER
	,UPD_FUNC
	,UPD_DATETM
	,UPD_USER
) VALUES (
	/*supplierCode*/NULL
	,/*supplierName*/NULL
	,/*supplierKana*/NULL
	,/*supplierAbbr*/NULL
	,/*supplierZipCode*/NULL
	,/*supplierAddress1*/NULL
	,/*supplierAddress2*/NULL
	,/*supplierDeptName*/NULL
	,/*supplierPcName*/NULL
	,/*supplierPcKana*/NULL
	,/*supplierPcPreCategory*/NULL
	,/*supplierPcPost*/NULL
	,/*supplierTel*/NULL
	,/*supplierFax*/NULL
	,/*supplierEmail*/NULL
	,/*supplierUrl*/NULL
	,/*supplierCmCategory*/NULL
	,/*taxShiftCategory*/NULL
	,/*paymentTypeCategory*/NULL
	,/*paymentCycleCategory*/NULL
	,/*lastCutoffDate*/NULL
	,/*paymentDate*/NULL
	,/*taxFractCategory*/NULL
	,/*priceFractCategory*/NULL
	,/*poSlipComeoutCategory*/NULL
	,/*serviceChargeCategory*/NULL
	,/*transferTypeCategory*/NULL
	,/*nationalCategory*/NULL
	,/*rateId*/NULL
	,/*fobName*/NULL
	,/*remarks*/NULL
	,/*commentData*/NULL
	,/*creFunc*/NULL
	,now()
	,/*creUser*/NULL
	,/*updFunc*/NULL
	,now()
	,/*updUser*/NULL
)
