SELECT
	W.PRODUCT_CODE,
	IFNULL(STDDEV_SAMP(W.QUANTITY), 0) AS SALES_STANDARD_DEVIATION
FROM
	STDDEV_AGGREGATE_YM_WORK_/*$domainId*/ W
WHERE
	W.SESSION_ID=/*sessionId*/'S'
GROUP BY
	W.PRODUCT_CODE