SELECT
	SS.SALES_YM,
	SL.PRODUCT_CODE,
	IFNULL(SUM(SL.QUANTITY), 0) AS QUANTITY
FROM
	SALES_SLIP_TRN_/*$domainId*/ SS INNER JOIN SALES_LINE_TRN_/*$domainId*/ SL ON SS.SALES_SLIP_ID = SL.SALES_SLIP_ID
WHERE
	SS.SALES_DATE BETWEEN DATE_FORMAT(DATE_SUB(now(), interval /*aggregateMonthsRange*/ month), '%Y-%m-01') AND now()
GROUP BY
	SS.SALES_YM,
	SL.PRODUCT_CODE
