SELECT
	P.HIST_ID,
	P.ACTION_TYPE,
	P.PRODUCT_CODE,
	PRODUCT_NAME,
	PRODUCT_KANA,
	ONLINE_PCODE,
	JAN_PCODE,
	DISCARD_DATE,
	P.SUPPLIER_CODE,
	SUP.SUPPLIER_NAME,
	SUPPLIER_PCODE,
	SUPPLIER_PRICE_YEN,
	SUPPLIER_PRICE_DOL,
	STOCK_CTL_CATEGORY 		 	STOCK_CTL_CATEGORY_CDX,
	CATT1.CATEGORY_CODE_NAME 	STOCK_CTL_CATEGORY_NM,
	PACK_QUANTITY,
	RACK_CODE,
	LEAD_TIME,
	PO_NUM,
	CASE WHEN PO_UPD_FLAG=1 THEN '自動' ELSE '手動' END PO_UPD_FLAG,
	MINE_SAFETY_STOCK,
	CASE WHEN MINE_SAFETY_STOCK_UPD_FLAG=1 THEN '自動' ELSE '手動' END MINE_SAFETY_STOCK_UPD_FLAG,
	ENTRUST_SAFETY_STOCK,
	SALES_STANDARD_DEVIATION,
	PO_LOT,
	CASE WHEN LOT_UPD_FLAG=1 THEN '自動' ELSE '手動' END LOT_UPD_FLAG,
	MAX_STOCK_NUM,
	CASE WHEN STOCK_UPD_FLAG=1 THEN '自動' ELSE '手動' END STOCK_UPD_FLAG,
	MAX_PO_NUM,
	CASE WHEN MAX_PO_UPD_FLAG=1 THEN '自動' ELSE '手動' END MAX_PO_UPD_FLAG,

	RO_MAX_NUM,
	RETAIL_PRICE,

	PRODUCT_STATUS_CATEGORY		PRODUCT_STATUS_CATEGORY_CDX,
	CATT2.CATEGORY_CODE_NAME 	PRODUCT_STATUS_CATEGORY_NM,
	PRODUCT_STOCK_CATEGORY		PRODUCT_STOCK_CATEGORY_CDX,
	CATT3.CATEGORY_CODE_NAME 	PRODUCT_STOCK_CATEGORY_NM,
	PRODUCT_PURVAY_CATEGORY		PRODUCT_PURVAY_CATEGORY_CDX,
	CATT4.CATEGORY_CODE_NAME 	PRODUCT_PURVAY_CATEGORY_NM,
	PRODUCT_STANDARD_CATEGORY	PRODUCT_STANDARD_CATEGORY_CDX,
	CATT5.CATEGORY_CODE_NAME 	PRODUCT_STANDARD_CATEGORY_NM,
	SO_RATE,
	CASE WHEN SET_TYPE_CATEGORY = '0' THEN '単品' ELSE 'セット品' END SET_TYPE_CATEGORY,

	CONCAT(PRODUCT_1,CONCAT(PRODUCT_2,PRODUCT_3)) 	PRODUCT_CDX,
	CONCAT(P1CLASS.CLASS_NAME,CONCAT('/', CONCAT(P2CLASS.CLASS_NAME,CONCAT('/' ,P3CLASS.CLASS_NAME)))) PRODUCT_NM,
	UNIT_CATEGORY				UNIT_CATEGORY_CDX,
	CATT11.CATEGORY_CODE_NAME 	UNIT_CATEGORY_NM,
	WEIGHT,
	WEIGHT_UNIT_SIZE_CATEGORY	WEIGHT_UNIT_SIZE_CATEGORY_CDX,
	CATT6.CATEGORY_CODE_NAME 	WEIGHT_UNIT_SIZE_CATEGORY_NM,
	LENGTH,
	LENGTH_UNIT_SIZE_CATEGORY	LENGTH_UNIT_SIZE_CATEGORY_CDX,
	CATT7.CATEGORY_CODE_NAME 	LENGTH_UNIT_SIZE_CATEGORY_NM,
	WIDTH,
	WIDTH_UNIT_SIZE_CATEGORY	WIDTH_UNIT_SIZE_CATEGORY_CDX,
	CATT8.CATEGORY_CODE_NAME 	WIDTH_UNIT_SIZE_CATEGORY_NM,
	DEPTH,
	DEPTH_UNIT_SIZE_CATEGORY	DEPTH_UNIT_SIZE_CATEGORY_CDX,
	CATT9.CATEGORY_CODE_NAME 	DEPTH_UNIT_SIZE_CATEGORY_NM,
	HEIGHT,
	HEIGHT_UNIT_SIZE_CATEGORY	HEIGHT_UNIT_SIZE_CATEGORY_CDX,
	CATT10.CATEGORY_CODE_NAME 	HEIGHT_UNIT_SIZE_CATEGORY_NM,
	CORE_NUM,
	P.REMARKS,
	EAD_REMARKS,
	P.COMMENT_DATA,

	P.REC_DATETM UPD_DATETM

FROM
	PRODUCT_MST_HIST_/*$domainId*/ P
		LEFT OUTER JOIN SUPPLIER_MST_HIST_/*$domainId*/ SUP
			ON P.SUPPLIER_CODE = SUP.SUPPLIER_CODE
			   AND SUP.REC_DATETM =
			   ( SELECT max(REC_DATETM)
			   	 FROM SUPPLIER_MST_HIST_/*$domainId*/ SUP2
			 	 WHERE SUP2.REC_DATETM <= P.REC_DATETM
			 		AND SUP2.SUPPLIER_CODE = P.SUPPLIER_CODE
				GROUP BY SUPPLIER_CODE
				)

		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CATT1
			ON STOCK_CTL_CATEGORY = CATT1.CATEGORY_CODE AND CATT1.CATEGORY_ID=20
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CATT2
			ON PRODUCT_STATUS_CATEGORY = CATT2.CATEGORY_CODE AND CATT2.CATEGORY_ID=16
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CATT3
			ON PRODUCT_STOCK_CATEGORY = CATT3.CATEGORY_CODE AND CATT3.CATEGORY_ID=17
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CATT4
			ON PRODUCT_PURVAY_CATEGORY = CATT4.CATEGORY_CODE AND CATT4.CATEGORY_ID=21
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CATT5
			ON PRODUCT_STANDARD_CATEGORY = CATT5.CATEGORY_CODE AND CATT5.CATEGORY_ID=3
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CATT6
			ON WEIGHT_UNIT_SIZE_CATEGORY = CATT6.CATEGORY_CODE AND CATT6.CATEGORY_ID=24
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CATT7
			ON LENGTH_UNIT_SIZE_CATEGORY = CATT7.CATEGORY_CODE AND CATT7.CATEGORY_ID=23
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CATT8
			ON WIDTH_UNIT_SIZE_CATEGORY = CATT8.CATEGORY_CODE AND CATT8.CATEGORY_ID=23
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CATT9
			ON DEPTH_UNIT_SIZE_CATEGORY = CATT9.CATEGORY_CODE AND CATT9.CATEGORY_ID=23
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CATT10
			ON HEIGHT_UNIT_SIZE_CATEGORY = CATT10.CATEGORY_CODE AND CATT10.CATEGORY_ID=23
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CATT11
			ON UNIT_CATEGORY = CATT11.CATEGORY_CODE AND CATT11.CATEGORY_ID=22

		LEFT OUTER JOIN PRODUCT_CLASS_MST_HIST_/*$domainId*/ P1CLASS
			ON  P1CLASS.CLASS_CODE_1 = P.PRODUCT_1
			AND P1CLASS.CLASS_CODE_2 = ' '
			AND P1CLASS.CLASS_CODE_3 = ' '
			AND P1CLASS.REC_DATETM =
				( SELECT max(REC_DATETM)
				  FROM PRODUCT_CLASS_MST_HIST_/*$domainId*/ P1CLASS2
				  WHERE P1CLASS2.REC_DATETM <= P.REC_DATETM
				 	AND P1CLASS2.CLASS_CODE_1 = P.PRODUCT_1
					AND P1CLASS2.CLASS_CODE_2 = ' '
					AND P1CLASS2.CLASS_CODE_3 = ' '
				GROUP BY CLASS_CODE_3
				)

		LEFT OUTER JOIN PRODUCT_CLASS_MST_HIST_/*$domainId*/ P2CLASS
			ON  P2CLASS.CLASS_CODE_1 = P.PRODUCT_1
			AND P2CLASS.CLASS_CODE_2 = P.PRODUCT_2
			AND P2CLASS.CLASS_CODE_3 = ' '
			AND P2CLASS.REC_DATETM =
				( SELECT max(REC_DATETM)
				  FROM PRODUCT_CLASS_MST_HIST_/*$domainId*/ P2CLASS2
				  WHERE P2CLASS2.REC_DATETM <= P.REC_DATETM
				 	AND P2CLASS2.CLASS_CODE_1 = P.PRODUCT_1
					AND P2CLASS2.CLASS_CODE_2 = P.PRODUCT_2
					AND P2CLASS2.CLASS_CODE_3 = ' '
				GROUP BY CLASS_CODE_3
				)

		LEFT OUTER JOIN PRODUCT_CLASS_MST_HIST_/*$domainId*/ P3CLASS
			ON  P3CLASS.CLASS_CODE_1 = P.PRODUCT_1
			AND P3CLASS.CLASS_CODE_2 = P.PRODUCT_2
			AND P3CLASS.CLASS_CODE_3 = P.PRODUCT_3
			AND P3CLASS.REC_DATETM =
			   ( SELECT max(REC_DATETM)
			   	 FROM PRODUCT_CLASS_MST_HIST_/*$domainId*/ P3CLASS2
			 	 WHERE P3CLASS2.REC_DATETM <= P.REC_DATETM
			 		AND P3CLASS2.CLASS_CODE_1 = P.PRODUCT_1
					AND P3CLASS2.CLASS_CODE_2 = P.PRODUCT_2
					AND P3CLASS2.CLASS_CODE_3 = P.PRODUCT_3
				GROUP BY CLASS_CODE_3
				)

WHERE
	P.PRODUCT_CODE = /*productCode*/'S'
ORDER BY HIST_ID
