SELECT
		P.PRODUCT_CODE
		,P.PRODUCT_NAME
		,P.SUPPLIER_PRICE_YEN
		,P.RETAIL_PRICE
		,P.SO_RATE
		,P.LENGTH
	FROM
		PRODUCT_MST_/*$domainId*/ P
	WHERE
		P.PRODUCT_CODE like /*productCode*/''