SELECT
		P.PRODUCT_CODE
		,P.PRODUCT_NAME
		,P.PRODUCT_KANA
		,P.ONLINE_PCODE
		,P.SUPPLIER_PCODE
		,P.SUPPLIER_CODE
		,P.RACK_CODE
		,W.WAREHOUSE_NAME
		,P.SUPPLIER_PRICE_YEN
		,P.SUPPLIER_PRICE_DOL
		,P.RETAIL_PRICE
		,P.SO_RATE
		,P.UNIT_CATEGORY
		,P.PACK_QUANTITY
		,P.JAN_PCODE
		,P.WIDTH
		,P.WIDTH_UNIT_SIZE_CATEGORY
		,P.DEPTH
		,P.DEPTH_UNIT_SIZE_CATEGORY
		,P.HEIGHT
		,P.HEIGHT_UNIT_SIZE_CATEGORY
		,P.WEIGHT
		,P.WEIGHT_UNIT_SIZE_CATEGORY
		,P.LENGTH
		,P.LENGTH_UNIT_SIZE_CATEGORY
		,P.PO_LOT
		,P.LOT_UPD_FLAG
		,P.LEAD_TIME
		,P.PO_NUM
		,P.PO_UPD_FLAG
		,P.MINE_SAFETY_STOCK
		,P.MINE_SAFETY_STOCK_UPD_FLAG
		,P.ENTRUST_SAFETY_STOCK
		,P.SALES_STANDARD_DEVIATION
		,P.AVG_SHIP_COUNT
		,P.MAX_STOCK_NUM
		,P.STOCK_UPD_FLAG
		,P.TERM_SHIP_NUM
		,P.MAX_PO_NUM
		,P.MAX_PO_UPD_FLAG
		,P.FRACT_CATEGORY
		,P.TAX_CATEGORY
		,P.STOCK_CTL_CATEGORY
		,P.STOCK_ASSES_CATEGORY
		,P.PRODUCT_CATEGORY
		,P.PRODUCT_1
		,P.PRODUCT_2
		,P.PRODUCT_3
		,P.RO_MAX_NUM
		,P.PRODUCT_RANK
		,P.SET_TYPE_CATEGORY
		,P.PRODUCT_STATUS_CATEGORY
		,P.PRODUCT_STOCK_CATEGORY
		,P.PRODUCT_PURVAY_CATEGORY
		,P.PRODUCT_STANDARD_CATEGORY
		,P.CORE_NUM
		,P.NUM_1
		,P.NUM_2
		,P.NUM_3
		,P.NUM_4
		,P.NUM_5
		,P.DEC_1
		,P.DEC_2
		,P.DEC_3
		,P.DEC_4
		,P.DEC_5
		,P.DISCARD_DATE
		,P.REMARKS
		,P.EAD_REMARKS
		,P.COMMENT_DATA
		,P.LAST_RO_DATE
		,P.CRE_FUNC
		,P.CRE_DATETM
		,P.CRE_USER
		,P.UPD_FUNC
		,P.UPD_DATETM
		,P.UPD_USER
		,S.SUPPLIER_NAME
		,CT.CATEGORY_CODE_NAME AS SET_TYPE_CATEGORY_NAME
		,CT2.CATEGORY_CODE_NAME AS UNIT_CATEGORY_NAME
		,CT3.CATEGORY_CODE_NAME AS PRODUCT_STATUS_CATEGORY_NAME
		,CT4.CATEGORY_CODE_NAME AS PRODUCT_STOCK_CATEGORY_NAME
		,CASE WHEN P.PRODUCT_STATUS_CATEGORY = /*productStatusSaleCancel*/ THEN '1' ELSE '0' END AS DISCARDED
		,DISREL.DISCOUNT_ID AS DISCOUNT_ID
		,DISMST.DISCOUNT_NAME AS DISCOUNT_NAME
		,DISREL.UPD_DATETM AS DISCOUNT_UPD_DATETM
		,R.RACK_NAME AS RACK_NAME
		,RATE.SIGN
	FROM
		PRODUCT_MST_/*$domainId*/ P
		LEFT OUTER JOIN SUPPLIER_MST_/*$domainId*/ S
			ON P.SUPPLIER_CODE = S.SUPPLIER_CODE
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CT
			ON P.SET_TYPE_CATEGORY = CT.CATEGORY_CODE AND CT.CATEGORY_ID = /*categoryId*/
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CT2
			ON P.UNIT_CATEGORY = CT2.CATEGORY_CODE AND CT2.CATEGORY_ID = /*unitCategoryId*/
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CT3
			ON P.PRODUCT_STATUS_CATEGORY = CT3.CATEGORY_CODE AND CT3.CATEGORY_ID = /*productStatusCategoryId*/
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CT4
			ON P.PRODUCT_STOCK_CATEGORY = CT4.CATEGORY_CODE AND CT4.CATEGORY_ID = /*productStockCategoryId*/
		LEFT OUTER JOIN DISCOUNT_REL_/*$domainId*/ DISREL
				ON DISREL.PRODUCT_CODE = P.PRODUCT_CODE
			LEFT OUTER JOIN DISCOUNT_MST_/*$domainId*/ DISMST
					ON DISREL.DISCOUNT_ID = DISMST.DISCOUNT_ID
		LEFT OUTER JOIN RACK_MST_/*$domainId*/ R
			ON P.RACK_CODE = R.RACK_CODE
		LEFT OUTER JOIN RATE_MST_/*$domainId*/ RATE
			ON S.RATE_ID = RATE.RATE_ID
		LEFT OUTER JOIN WAREHOUSE_MST_/*$domainId*/ W
			ON R.WAREHOUSE_CODE = W.WAREHOUSE_CODE
	WHERE
		P.PRODUCT_CODE=/*productCode*/''