SELECT
		P.PRODUCT_CODE		AS PRODUCT_CODE
		,P.PRODUCT_NAME		AS PRODUCT_NAME
		,P.PRODUCT_KANA		AS PRODUCT_KANA
		,P.ONLINE_PCODE	AS ONLINE_PCODE
		,P.JAN_PCODE		AS JAN_PCODE
		,P.DISCARD_DATE		AS DISCARD_DATE

		,P.SUPPLIER_CODE	AS SUPPLIER_CODE
		,SUP.SUPPLIER_NAME	AS SUPPLIER_NAME
		,P.SUPPLIER_PCODE	AS SUPPLIER_PCODE
		,P.SUPPLIER_PRICE_YEN	AS SUPPLIER_PRICE_YEN
		,P.SUPPLIER_PRICE_DOL	AS SUPPLIER_PRICE_DOL
		,P.RETAIL_PRICE		AS RETAIL_PRICE

		,SCTLCAT.CATEGORY_CODE_NAME		AS STOCK_CTL_CATEGORY_NAME

		,P.PACK_QUANTITY	AS PACK_QUANTITY
		,P.AVG_SHIP_COUNT	AS AVG_SHIP_COUNT
		,P.RACK_CODE		AS RACK_CODE
		,P.LEAD_TIME		AS LEAD_TIME
		,P.PO_NUM			AS PO_NUM
		,P.PO_UPD_FLAG		AS PO_UPD_FLAG
		,P.MINE_SAFETY_STOCK AS MINE_SAFETY_STOCK
		,P.MINE_SAFETY_STOCK_UPD_FLAG AS MINE_SAFETY_STOCK_UPD_FLAG
		,P.ENTRUST_SAFETY_STOCK AS ENTRUST_SAFETY_STOCK
		,P.SALES_STANDARD_DEVIATION AS SALES_STANDARD_DEVIATION
		,P.PO_LOT			AS PO_LOT
		,P.LOT_UPD_FLAG		AS LOT_UPD_FLAG
		,P.MAX_STOCK_NUM	AS MAX_STOCK_NUM
		,P.STOCK_UPD_FLAG	AS STOCK_UPD_FLAG
		,P.MAX_PO_NUM		AS MAX_PO_NUM
		,P.MAX_PO_UPD_FLAG	AS MAX_PO_UPD_FLAG
		,P.RO_MAX_NUM		AS RO_MAX_NUM

		,STATUSCAT.CATEGORY_CODE_NAME	AS PRODUCT_STATUS_CATEGORY_NAME
		,STOCKCAT.CATEGORY_CODE_NAME	AS PRODUCT_STOCK_CATEGORY_NAME
		,PURVAYCAT.CATEGORY_CODE_NAME	AS PRODUCT_PURVAY_CATEGORY_NAME
		,STANDARDCAT.CATEGORY_CODE_NAME	AS PRODUCT_STANDARD_CATEGORY_NAME

		,SETCAT.CATEGORY_CODE_NAME		AS SET_TYPE_CATEGORY_NAME

		,P.SO_RATE			AS SO_RATE

		,P1CLASS.CLASS_NAME	AS PRODUCT1_NAME
		,P2CLASS.CLASS_NAME	AS PRODUCT2_NAME
		,P3CLASS.CLASS_NAME	AS PRODUCT3_NAME

		,UNITCAT.CATEGORY_CODE_NAME			AS UNIT_CATEGORY_NAME

		,P.WEIGHT			AS WEIGHT
		,WEIGHTUNITCAT.CATEGORY_CODE_NAME	AS WEIGHT_UNIT_SIZE_CATEGORY_NAME

		,P.LENGTH			AS LENGTH
		,LUNITCAT.CATEGORY_CODE_NAME			AS LENGTH_UNIT_SIZE_CATEGORY_NAME
		,P.WIDTH			AS WIDTH
		,WUNITCAT.CATEGORY_CODE_NAME			AS WIDTH_UNIT_SIZE_CATEGORY_NAME
		,P.DEPTH			AS DEPTH
		,DUNITCAT.CATEGORY_CODE_NAME			AS DEPTH_UNIT_SIZE_CATEGORY_NAME
		,P.HEIGHT			AS HEIGHT
		,HUNITCAT.CATEGORY_CODE_NAME			AS HEIGHT_UNIT_SIZE_CATEGORY_NAME

		,P.CORE_NUM			AS CORE_NUM

		,P.REMARKS			AS REMARKS
		,P.EAD_REMARKS		AS EAD_REMARKS
		,P.COMMENT_DATA		AS COMMENT_DATA

		,DISMST.DISCOUNT_NAME	AS DISCOUNT_NAME

	FROM
		PRODUCT_MST_/*$domainId*/ P

		LEFT OUTER JOIN SUPPLIER_MST_/*$domainId*/ SUP
				ON P.SUPPLIER_CODE = SUP.SUPPLIER_CODE

		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ SCTLCAT
				ON SCTLCAT.CATEGORY_ID = /*stockCtlCategoryId*/
					AND P.STOCK_CTL_CATEGORY = SCTLCAT.CATEGORY_CODE

		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ STATUSCAT
				ON STATUSCAT.CATEGORY_ID = /*productStatusCategoryId*/
					AND P.PRODUCT_STATUS_CATEGORY = STATUSCAT.CATEGORY_CODE
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ STOCKCAT
				ON STOCKCAT.CATEGORY_ID = /*productStockCategoryId*/
					AND P.PRODUCT_STOCK_CATEGORY = STOCKCAT.CATEGORY_CODE
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ PURVAYCAT
				ON PURVAYCAT.CATEGORY_ID = /*productPurvayCategoryId*/
					AND P.PRODUCT_PURVAY_CATEGORY = PURVAYCAT.CATEGORY_CODE
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ STANDARDCAT
				ON STANDARDCAT.CATEGORY_ID = /*productStandardCategoryId*/
					AND P.PRODUCT_STANDARD_CATEGORY = STANDARDCAT.CATEGORY_CODE

		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ SETCAT
				ON SETCAT.CATEGORY_ID = /*setTypeCategoryId*/
					AND P.SET_TYPE_CATEGORY = SETCAT.CATEGORY_CODE

		LEFT OUTER JOIN PRODUCT_CLASS_MST_/*$domainId*/ P1CLASS
				ON  P1CLASS.CLASS_CODE_1 = P.PRODUCT_1
				AND P1CLASS.CLASS_CODE_2 = ' '
				AND P1CLASS.CLASS_CODE_3 = ' '
		LEFT OUTER JOIN PRODUCT_CLASS_MST_/*$domainId*/ P2CLASS
				ON  P2CLASS.CLASS_CODE_1 = P.PRODUCT_1
				AND P2CLASS.CLASS_CODE_2 = P.PRODUCT_2
				AND P2CLASS.CLASS_CODE_3 = ' '
		LEFT OUTER JOIN PRODUCT_CLASS_MST_/*$domainId*/ P3CLASS
				ON  P3CLASS.CLASS_CODE_1 = P.PRODUCT_1
				AND P3CLASS.CLASS_CODE_2 = P.PRODUCT_2
				AND P3CLASS.CLASS_CODE_3 = P.PRODUCT_3

		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ UNITCAT
				ON UNITCAT.CATEGORY_ID = /*unitCategoryId*/
					AND P.UNIT_CATEGORY = UNITCAT.CATEGORY_CODE

		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ WEIGHTUNITCAT
				ON WEIGHTUNITCAT.CATEGORY_ID = /*weightUnitSizeCategoryId*/
					AND P.WEIGHT_UNIT_SIZE_CATEGORY = WEIGHTUNITCAT.CATEGORY_CODE

		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ LUNITCAT
				ON LUNITCAT.CATEGORY_ID = /*lengthUnitSizeCategoryId*/
					AND P.LENGTH_UNIT_SIZE_CATEGORY = LUNITCAT.CATEGORY_CODE

		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ WUNITCAT
				ON WUNITCAT.CATEGORY_ID = /*lengthUnitSizeCategoryId*/
					AND P.WIDTH_UNIT_SIZE_CATEGORY = WUNITCAT.CATEGORY_CODE
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ DUNITCAT
				ON DUNITCAT.CATEGORY_ID = /*lengthUnitSizeCategoryId*/
					AND P.DEPTH_UNIT_SIZE_CATEGORY = DUNITCAT.CATEGORY_CODE
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ HUNITCAT
				ON HUNITCAT.CATEGORY_ID = /*lengthUnitSizeCategoryId*/
					AND P.HEIGHT_UNIT_SIZE_CATEGORY = HUNITCAT.CATEGORY_CODE

		LEFT OUTER JOIN DISCOUNT_REL_/*$domainId*/ DISREL
				ON DISREL.PRODUCT_CODE = P.PRODUCT_CODE
			LEFT OUTER JOIN DISCOUNT_MST_/*$domainId*/ DISMST
					ON DISREL.DISCOUNT_ID = DISMST.DISCOUNT_ID

	WHERE
		P.PRODUCT_CODE = /*productCode*/

