insert into PRODUCT_MST_/*$domainId*/'DEFAULT'(
	PRODUCT_CODE,
	PRODUCT_NAME,
	PRODUCT_KANA,
	ONLINE_PCODE,
	SUPPLIER_PCODE,
	SUPPLIER_CODE,
	RACK_CODE,
	SUPPLIER_PRICE_YEN,
	SUPPLIER_PRICE_DOL,
	RETAIL_PRICE,
	SO_RATE,
	UNIT_CATEGORY,
	PACK_QUANTITY,
	JAN_PCODE,
	WIDTH,
	WIDTH_UNIT_SIZE_CATEGORY,
	DEPTH,
	DEPTH_UNIT_SIZE_CATEGORY,
	HEIGHT,
	HEIGHT_UNIT_SIZE_CATEGORY,
	WEIGHT,
	WEIGHT_UNIT_SIZE_CATEGORY,
	LENGTH,
	LENGTH_UNIT_SIZE_CATEGORY,
	PO_LOT,
	LOT_UPD_FLAG,
	LEAD_TIME,
	PO_NUM,
	PO_UPD_FLAG,
	MINE_SAFETY_STOCK,
	MINE_SAFETY_STOCK_UPD_FLAG,
	ENTRUST_SAFETY_STOCK,
	SALES_STANDARD_DEVIATION,
	AVG_SHIP_COUNT,
	MAX_STOCK_NUM,
	STOCK_UPD_FLAG,
	TERM_SHIP_NUM,
	MAX_PO_NUM,
	MAX_PO_UPD_FLAG,
	FRACT_CATEGORY,
	TAX_CATEGORY,
	STOCK_CTL_CATEGORY,
	STOCK_ASSES_CATEGORY,
	PRODUCT_CATEGORY,
	PRODUCT_1,
	PRODUCT_2,
	PRODUCT_3,
	RO_MAX_NUM,
	PRODUCT_RANK,
	SET_TYPE_CATEGORY,
	PRODUCT_STATUS_CATEGORY,
	PRODUCT_STOCK_CATEGORY,
	PRODUCT_PURVAY_CATEGORY,
	PRODUCT_STANDARD_CATEGORY,
	CORE_NUM,
	NUM_1,
	NUM_2,
	NUM_3,
	NUM_4,
	NUM_5,
	DEC_1,
	DEC_2,
	DEC_3,
	DEC_4,
	DEC_5,
	DISCARD_DATE,
	REMARKS,
	EAD_REMARKS,
	COMMENT_DATA,
	LAST_RO_DATE,
	CRE_FUNC,
	CRE_DATETM,
	CRE_USER,
	UPD_FUNC,
	UPD_DATETM,
	UPD_USER
	)
	values (
	/*productCode*/
	,/*productName*/
	,/*productKana*/
	,/*onlinePcode*/NULL
	,/*supplierPcode*/NULL
	,/*supplierCode*/NULL
	,/*rackCode*/NULL
	,/*supplierPriceYen*/NULL
	,/*supplierPriceDol*/NULL
	,/*retailPrice*/NULL
	,/*soRate*/NULL
	,/*unitCategory*/NULL
	,/*packQuantity*/NULL
	,/*janPcode*/NULL
	,/*width*/NULL
	,/*widthUnitSizeCategory*/NULL
	,/*depth*/NULL
	,/*depthUnitSizeCategory*/NULL
	,/*height*/NULL
	,/*heightUnitSizeCategory*/NULL
	,/*weight*/NULL
	,/*weightUnitSizeCategory*/NULL
	,/*length*/NULL
	,/*lengthUnitSizeCategory*/NULL
	,/*poLot*/NULL
	,/*lotUpdFlag*/NULL
	,/*leadTime*/NULL
	,/*poNum*/NULL
	,/*poUpdFlag*/NULL
	,/*mineSafetyStock*/NULL
	,/*mineSafetyStockUpdFlag*/NULL
	,/*entrustSafetyStock*/NULL
	,/*salesStandardDeviation*/NULL
	,/*avgShipCount*/NULL
	,/*maxStockNum*/
	,/*stockUpdFlag*/NULL
	,/*termShipNum*/NULL
	,/*maxPoNum*/
	,/*maxPoUpdFlag*/NULL
	,/*fractCategory*/NULL
	,/*taxCategory*/NULL
	,/*stockCtlCategory*/NULL
	,/*stockAssesCategory*/NULL
	,/*productCategory*/NULL
	,/*product1*/NULL
	,/*product2*/NULL
	,/*product3*/NULL
	,/*roMaxNum*/
	,/*productRank*/NULL
	,/*setTypeCategory*/NULL
	,/*productStatusCategory*/NULL
	,/*productStockCategory*/NULL
	,/*productPurvayCategory*/NULL
	,/*productStandardCategory*/NULL
	,/*coreNum*/NULL
	,/*num1*/NULL
	,/*num2*/NULL
	,/*num3*/NULL
	,/*num4*/NULL
	,/*num5*/NULL
	,/*dec1*/NULL
	,/*dec2*/NULL
	,/*dec3*/NULL
	,/*dec4*/NULL
	,/*dec5*/NULL
	,/*discardDate*/NULL
	,/*remarks*/NULL
	,/*eadRemarks*/NULL
	,/*commentData*/NULL
	,/*lastRoDate*/NULL
	,/*creFunc*/NULL
	,now()
	,/*creUser*/NULL
	,/*updFunc*/NULL
	,now()
	,/*updUser*/NULL
)