UPDATE STDDEV_AGGREGATE_YM_WORK_/*$domainId*/ AW
	INNER JOIN STDDEV_PRODUCT_SALES_YM_WORK_/*$domainId*/ SW
	ON AW.SESSION_ID=SW.SESSION_ID AND AW.YM=SW.YM AND AW.PRODUCT_CODE=SW.PRODUCT_CODE
SET AW.QUANTITY = SW.QUANTITY
WHERE
	SW.SESSION_ID=/*sessionId*/
