update
	PRODUCT_MST_/*$domainId*/ SET
		PRODUCT_NAME =/*productName*/
		,PRODUCT_KANA =/*productKana*/
		,ONLINE_PCODE =/*onlinePcode*/
		,SUPPLIER_PCODE =/*supplierPcode*/
		,SUPPLIER_CODE =/*supplierCode*/
		,RACK_CODE =/*rackCode*/
		,SUPPLIER_PRICE_YEN =/*supplierPriceYen*/
		,SUPPLIER_PRICE_DOL =/*supplierPriceDol*/
		,RETAIL_PRICE =/*retailPrice*/
		,SO_RATE =/*soRate*/
		,UNIT_CATEGORY =/*unitCategory*/
		,PACK_QUANTITY =/*packQuantity*/
		,JAN_PCODE =/*janPcode*/
		,WIDTH =/*width*/
		,WIDTH_UNIT_SIZE_CATEGORY =/*widthUnitSizeCategory*/
		,DEPTH =/*depth*/
		,DEPTH_UNIT_SIZE_CATEGORY =/*depthUnitSizeCategory*/
		,HEIGHT =/*height*/
		,HEIGHT_UNIT_SIZE_CATEGORY =/*heightUnitSizeCategory*/
		,WEIGHT =/*weight*/
		,WEIGHT_UNIT_SIZE_CATEGORY =/*weightUnitSizeCategory*/
		,LENGTH =/*length*/
		,LENGTH_UNIT_SIZE_CATEGORY =/*lengthUnitSizeCategory*/
		,PO_LOT =/*poLot*/
		,LOT_UPD_FLAG =/*lotUpdFlag*/
		,LEAD_TIME =/*leadTime*/
		,PO_NUM =/*poNum*/
		,PO_UPD_FLAG =/*poUpdFlag*/
		,MINE_SAFETY_STOCK=/*mineSafetyStock*/
		,MINE_SAFETY_STOCK_UPD_FLAG=/*mineSafetyStockUpdFlag*/
		,ENTRUST_SAFETY_STOCK=/*entrustSafetyStock*/
		,SALES_STANDARD_DEVIATION=/*salesStandardDeviation*/
		,AVG_SHIP_COUNT =/*avgShipCount*/
		,MAX_STOCK_NUM =/*maxStockNum*/
		,STOCK_UPD_FLAG =/*stockUpdFlag*/
		,TERM_SHIP_NUM =/*termShipNum*/
		,MAX_PO_NUM =/*maxPoNum*/
		,MAX_PO_UPD_FLAG =/*maxPoUpdFlag*/
		,FRACT_CATEGORY =/*fractCategory*/
		,TAX_CATEGORY =/*taxCategory*/
		,STOCK_CTL_CATEGORY =/*stockCtlCategory*/
		,STOCK_ASSES_CATEGORY =/*stockAssesCategory*/
		,PRODUCT_CATEGORY =/*productCategory*/
		,CORE_NUM = /*coreNum*/
		,PRODUCT_1 =/*product1*/
		,PRODUCT_2 =/*product2*/
		,PRODUCT_3 =/*product3*/
		,RO_MAX_NUM =/*roMaxNum*/
		,PRODUCT_RANK =/*productRank*/
		,SET_TYPE_CATEGORY =/*setTypeCategory*/
		,PRODUCT_STATUS_CATEGORY =/*productStatusCategory*/
		,PRODUCT_STOCK_CATEGORY =/*productStockCategory*/
		,PRODUCT_PURVAY_CATEGORY =/*productPurvayCategory*/
		,PRODUCT_STANDARD_CATEGORY =/*productStandardCategory*/
		,CORE_NUM =/*coreNum*/
		,NUM_1 =/*num1*/
		,NUM_2 =/*num2*/
		,NUM_3 =/*num3*/
		,NUM_4 =/*num4*/
		,NUM_5 =/*num5*/
		,DEC_1 =/*dec1*/
		,DEC_2 =/*dec2*/
		,DEC_3 =/*dec3*/
		,DEC_4 =/*dec4*/
		,DEC_5 =/*dec5*/
		,DISCARD_DATE =/*discardDate*/
		,REMARKS =/*remarks*/
		,EAD_REMARKS =/*eadRemarks*/
		,COMMENT_DATA =/*commentData*/
		,LAST_RO_DATE =/*lastRoDate*/
		,UPD_FUNC =/*updFunc*/NULL
		,UPD_DATETM =now()
		,UPD_USER =/*updUser*/NULL
	where
 		PRODUCT_CODE=/*productCode*/