INSERT
    INTO
		ART_BALANCE_TRN_/*$domainId*/ (
			ART_BALANCE_ID
			,ART_ANNUAL
			,ART_MONTHLY
			,ART_YM
			,ART_CUTOFF_DATE
			,USER_ID
			,USER_NAME
			,BA_CODE
			,BA_NAME
			,CUSTOMER_CODE
			,CUSTOMER_NAME
			,SALES_CM_CATEGORY
			,LAST_ART_PRICE
			,DEPOSIT_PRICE
			,ADJ_PRICE
			,COV_PRICE
			,SALES_PRICE
			,CTAX_PRICE
			,RGU_PRICE
			,DCT_PRICE
			,ETC_PRICE
			,THIS_ART_PRICE
			,GM_PRICE
			,ART_CUTOFF_GROUP
			,PAYBACK_CYCLE_CATEGORY
			,SALES_SLIP_NUM
			,ART_CUTOFF_PDATE
			,DEPOSIT_CASH
			,DEPOSIT_CHECK
			,DEPOSIT_TRANSFER
			,DEPOSIT_SC
			,DEPOSIT_INST
			,DEPOSIT_SETOFF
			,DEPOSIT_ETC
			,FAMILY_CATEGORY
			,DELIVERY_PLACE_NUM
			,REMARKS
			,CRE_FUNC
			,CRE_DATETM
			,CRE_USER
			,UPD_FUNC
			,UPD_DATETM
			,UPD_USER
	) VALUES (
			/*artBalanceId*/NULL
			,/*artAnnual*/NULL
			,/*artMonthly*/NULL
			,/*artYm*/NULL
			,/*artCutoffDate*/NULL
			,/*userId*/NULL
			,/*userName*/NULL
			,/*baCode*/NULL
			,/*baName*/NULL
			,/*customerCode*/NULL
			,/*customerName*/NULL
			,/*salesCmCategory*/NULL
			,/*lastArtPrice*/NULL
			,/*depositPrice*/NULL
			,/*adjPrice*/NULL
			,/*covPrice*/NULL
			,/*salesPrice*/NULL
			,/*ctaxPrice*/NULL
			,/*rguPrice*/NULL
			,/*dctPrice*/NULL
			,/*etcPrice*/NULL
			,/*thisArtPrice*/NULL
			,/*gmPrice*/NULL
			,/*artCutoffGroup*/NULL
			,/*paybackCycleCategory*/NULL
			,/*salesSlipNum*/NULL
			,/*artCutoffPdate*/NULL
			,/*depositCash*/NULL
			,/*depositCheck*/NULL
			,/*depositTransfer*/NULL
			,/*depositSc*/NULL
			,/*depositInst*/NULL
			,/*depositSetoff*/NULL
			,/*depositEtc*/NULL
			,/*familyCategory*/NULL
			,/*deliveryPlaceNum*/NULL
			,/*remarks*/NULL
			,/*creFunc*/NULL
			,now()
			,/*creUser*/NULL
			,/*updFunc*/NULL
			,now()
			,/*updUser*/NULL
	)
