SELECT
    A.DELIVERY_SLIP_ID,
    A.DELIVERY_DATE,
    A.PRODUCT_PRICE,
    A.COD_PRICE,
    A.DATA_CATEGORY,
    B.SALES_SLIP_ID,
    B.DEPOSIT_SLIP_ID,
    C.PRICE_TOTAL
FROM
    DELIVERY_DEPOSIT_WORK_/*$domainId*/ A
    LEFT OUTER JOIN
      DELIVERY_DEPOSIT_REL_/*$domainId*/ B
      ON A.DELIVERY_SLIP_ID = B.DELIVERY_SLIP_ID
    LEFT OUTER JOIN
      SALES_SLIP_TRN_/*$domainId*/ C
      ON B.SALES_SLIP_ID = C.SALES_SLIP_ID
WHERE
    A.USER_ID=/*userId*/''
ORDER BY
	A.DELIVERY_SLIP_ID,
	A.DATA_CATEGORY