INSERT
    INTO
	PICKING_LINE_TRN_/*$domainId*/ (
		PICKING_LINE_ID
		,PICKING_LIST_ID
		,SALES_LINE_ID
		,RO_LINE_ID
		,LINE_NO
		,SALES_DETAIL_CATEGORY
		,PRODUCT_CODE
		,CUSTOMER_PCODE
		,PRODUCT_ABSTRACT
		,QUANTITY
		,UNIT_PRICE
		,UNIT_CATEGORY
		,UNIT_NAME
		,PACK_QUANTITY
		,UNIT_RETAIL_PRICE
		,RETAIL_PRICE
		,UNIT_COST
		,COST
		,TAX_CATEGORY
		,CTAX_RATE
		,CTAX_PRICE
		,GM
		,RACK_CODE_SRC
		,STOCK_NUM
		,REMARKS
		,CRE_FUNC
		,CRE_DATETM
		,CRE_USER
		,UPD_FUNC
		,UPD_DATETM
		,UPD_USER
	) VALUES (
		/*pickingLineId*/0
		,/*pickingListId*/NULL
		,/*salesLineId*/NULL
		,/*roLineId*/NULL
		,/*pickingLineNo*/NULL
		,/*salesDetailCategory*/NULL
		,/*productCode*/NULL
		,/*customerPcode*/NULL
		,/*productAbstract*/NULL
		,/*quantity*/NULL
		,/*unitPrice*/NULL
		,/*unitCategory*/NULL
		,/*unitName*/NULL
		,/*packQuantity*/NULL
		,/*unitRetailPrice*/NULL
		,/*retailPrice*/NULL
		,/*unitCost*/NULL
		,/*cost*/NULL
		,/*taxCategory*/NULL
		,/*ctaxRate*/NULL
		,/*ctaxPrice*/NULL
		,/*gm*/NULL
		,/*rackCodeSrc*/NULL
		,/*stockNum*/NULL
		,/*remarks*/NULL
		,/*creFunc*/NULL
		,now()
		,/*creUser*/NULL
		,/*updFunc*/NULL
		,now()
		,/*updUser*/NULL
)
