/*ファイル登録画面*/
UPDATE MENU_MST_XXXXX SET URL ='/setting/searchFileUpload'
 WHERE MENU_ID = '1205';

-- セキュリティ設定画面を追加
INSERT INTO MENU_MST_XXXXX (MENU_ID,CAPTION,DESCRIPTION,URL,PARENT_ID,SEQ,VALID_TYPE,FONT_COLOR,BG_COLOR,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('1207', 'セキュリティ設定',NULL,'/setting/setSecurity','0012',8,'0','FFFFFF','B3B3B7','初期登録', now(), 'ARK', '初期登録', now(), 'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('090','セキュリティ設定',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('090','1207','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','090','初期登録',now(),'ARK','初期登録',now(),'ARK');

-- 消費税8%を追加
INSERT INTO TAX_RATE_MST_XXXXX (TAX_TYPE_CATEGORY,START_DATE,TAX_RATE,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('1', '2014-04-01', 8, '初期登録',now(),'ARK', '初期登録',now(),'ARK');
