SELECT
	EAD.ENTRUST_EAD_SLIP_ID,
	EAD.ENTRUST_EAD_DATE,
	EAD.ENTRUST_EAD_ANNUAL,
	EAD.ENTRUST_EAD_MONTHLY,
	EAD.ENTRUST_EAD_YM,
	PO.SUPPLIER_CODE,
	PO.SUPPLIER_NAME,
	EAD.USER_ID,
	EAD.USER_NAME,
	EAD.ENTRUST_EAD_CATEGORY,
	EAD.REMARKS,
	EAD.PO_SLIP_ID,
	EAD.DISPATCH_ORDER_PRINT_COUNT,
	EAD.CRE_FUNC,
	EAD.CRE_DATETM,
	EAD.CRE_USER,
	EAD.UPD_FUNC,
	EAD.UPD_DATETM,
	EAD.UPD_USER
FROM
	ENTRUST_EAD_SLIP_TRN_/*$domainId*/ EAD LEFT OUTER JOIN PO_SLIP_TRN_/*$domainId*/ PO
	ON EAD.PO_SLIP_ID = PO.PO_SLIP_ID
WHERE
	ENTRUST_EAD_SLIP_ID=/*entrustEadSlipId*/0
