UPDATE ENTRUST_EAD_LINE_TRN_/*$domainId*/, (
		SELECT T1.ENTRUST_EAD_LINE_ID T1_RESULT, T2.ENTRUST_EAD_LINE_ID T2_RESULT
		FROM ENTRUST_EAD_LINE_TRN_/*$domainId*/ T1 LEFT OUTER JOIN ENTRUST_EAD_LINE_TRN_/*$domainId*/ T2
			ON T1.PO_LINE_ID = T2.PO_LINE_ID AND T2.ENTRUST_EAD_CATEGORY='2'
		WHERE T1.PO_LINE_ID = /*poLineId*/
			AND T1.ENTRUST_EAD_CATEGORY='1'
	) TTT
SET
	REL_ENTRUST_EAD_LINE_ID = IF(ENTRUST_EAD_CATEGORY='1', T2_RESULT, T1_RESULT )
WHERE
	PO_LINE_ID = /*poLineId*/
