SELECT  E.ESTIMATE_LINE_ID
		,E.ESTIMATE_SHEET_ID
		,E.LINE_NO
		,E.PRODUCT_CODE
		,E.CUSTOMER_PCODE
		,E.PRODUCT_ABSTRACT
		,E.QUANTITY
		,E.UNIT_COST
		,E.UNIT_RETAIL_PRICE
		,E.COST
		,E.RETAIL_PRICE
		,E.REMARKS
        ,E.UPD_FUNC
        ,E.UPD_DATETM
        ,E.UPD_USER
        ,P.SUPPLIER_PCODE
        ,P.RO_MAX_NUM
    FROM ESTIMATE_LINE_TRN_/*$domainId*/ E
    LEFT JOIN  PRODUCT_MST_/*$domainId*/ P ON  E.PRODUCT_CODE = P.PRODUCT_CODE
	WHERE
		ESTIMATE_SHEET_ID=/*estimateSheetId*/'default'
	ORDER BY E.LINE_NO
