SELECT
	DISTINCT
	LINE.PRODUCT_CODE
FROM
	RO_SLIP_TRN_/*$domainId*/ SLIP
	INNER JOIN RO_LINE_TRN_/*$domainId*/ LINE ON SLIP.RO_SLIP_ID = LINE.RO_SLIP_ID
/*BEGIN*/
WHERE
	/*IF roDate != null */
	AND SLIP.RO_DATE >= CAST(/*roDate*/ AS DATE)
	AND SLIP.RO_DATE <= CURDATE()
	/*END*/
/*END*/
ORDER BY
	LINE.PRODUCT_CODE
