-- SP_UPDATE_CUSTOMER_RANKプロシージャ呼び出し

SET @STARTDT=now();

call SP_UPDATE_CUSTOMER_RANK_XXXXX;

SELECT
        CASE WHEN IFNULL(MAX(STATUS_CODE),1)=0 THEN 'SUCCESS' ELSE 'FAILURE' END AS RESULT
FROM
        BATCH_LOG
WHERE
        DOMAIN_ID='XXXXX' AND
        FUNC_NAME = 'SP_UPDATE_CUSTOMER_RANK' AND
        DATETM >= @STARTDT;

SELECT
        CASE WHEN COUNT(*) > 0 THEN '名寄せの結果、更新対象から除外された顧客が存在します。' ELSE '' END AS ''
FROM
        BATCH_LOG
WHERE
        DOMAIN_ID='XXXXX' AND
        FUNC_NAME = 'SP_UPDATE_CUSTOMER_RANK' AND
        DATETM >= @STARTDT AND
        DISCRIPTION LIKE '%除外%';

quit
