-- SP_UPDATE_PRODUCT_STOCK_VALUESプロシージャ呼び出し

SET @STARTDT=now();

call SP_UPDATE_PRODUCT_STOCK_VALUES_XXXXX;

SELECT
        CASE WHEN IFNULL(MAX(STATUS_CODE),1)=0 THEN 'SUCCESS' ELSE 'FAILURE' END AS RESULT
FROM
        BATCH_LOG
WHERE
        DOMAIN_ID='XXXXX' AND
        FUNC_NAME = 'SP_UPDATE_PRODUCT_STOCK_VALUES' AND
        DATETM >= @STARTDT;

quit
