SELECT
	COUNT(SL.SUPPLIER_LINE_ID)
FROM
	PO_LINE_TRN_/*$domainId*/ PL
        LEFT OUTER JOIN SUPPLIER_LINE_TRN_/*$domainId*/ SL ON PL.PO_LINE_ID = SL.PO_LINE_ID
		LEFT OUTER JOIN SUPPLIER_SLIP_TRN_/*$domainId*/ S ON SL.SUPPLIER_SLIP_ID = S.SUPPLIER_SLIP_ID
WHERE
    PL.PO_SLIP_ID = /*poSlipId*/'default' AND
    SL.STATUS = /*status*/'default'
