SELECT
	R.RATE_ID,
	R.NAME,
	R.SIGN,
	R.REMARKS,
	R.CRE_FUNC,
	R.CRE_DATETM,
	R.CRE_USER,
	R.UPD_FUNC,
	R.UPD_DATETM,
	R.UPD_USER,
	RT.START_DATE,
	RT.RATE
FROM
	RATE_MST_/*$domainId*/ R INNER JOIN RATE_TRN_/*$domainId*/ RT ON R.RATE_ID = RT.RATE_ID
WHERE
	R.RATE_ID=/*rateId*/0
	AND RT.START_DATE = (
		SELECT MAX(RT2.START_DATE) FROM RATE_TRN_/*$domainId*/ RT2 WHERE RT2.START_DATE <= now() AND RT2.RATE_ID = RT.RATE_ID
	)
