SELECT
	SLIP.CUSTOMER_CODE,
	SLIP.CUSTOMER_NAME,
	CAT1.CATEGORY_CODE_NAME AS SALES_CM_CATEGORY,
	SLIP.LAST_ART_PRICE,
	IFNULL(SLIP.DEPOSIT_PRICE,0) + IFNULL(SLIP.ADJ_PRICE,0) AS DEPOSIT_PRICE,
	(IFNULL(SLIP.DEPOSIT_PRICE,0) + IFNULL(SLIP.ADJ_PRICE,0))/IFNULL(SLIP.LAST_ART_PRICE,0) AS DEPOSIT_RATE,
	IFNULL(SLIP.SALES_PRICE,0) + IFNULL(SLIP.DCT_PRICE,0) + IFNULL(SLIP.RGU_PRICE,0) + IFNULL(SLIP.ETC_PRICE,0) AS THIS_SALES_PRICE,
	SLIP.CTAX_PRICE,
	SLIP.RGU_PRICE,
	SLIP.THIS_ART_PRICE,
	0 AS DEPOSIT_INST,
	SLIP.SALES_PRICE,
	(
		SELECT MAX(T1.SALES_DATE)
		FROM SALES_SLIP_TRN_/*$domainId*/ T1
		WHERE
		T1.CUSTOMER_CODE=SLIP.CUSTOMER_CODE
	) LATEST_SALES_DATE,
	(
		SELECT MAX(T2.DEPOSIT_DATE)
		FROM DEPOSIT_SLIP_TRN_/*$domainId*/ T2
		WHERE T2.BILL_CUTOFF_DATE=SLIP.ART_CUTOFF_DATE AND
		T2.CUSTOMER_CODE=SLIP.CUSTOMER_CODE
	) LATEST_DEPOSIT_DATE
FROM
	UNIT_ART_BALANCE_TRN_/*$domainId*/ SLIP
	-- 最も新しいデータを出す
    INNER JOIN
        (
        SELECT
            MAX(ART_CUTOFF_DATE) CD
            ,CUSTOMER_CODE
        FROM
		/*IF targetDate != null */
            UNIT_ART_BALANCE_TRN_/*$domainId*/ SLIP2
		/*END*/
        WHERE
            SLIP2.ART_YM = /*targetDate*/201001
        GROUP BY CUSTOMER_CODE
        ) AS SLIP3
        ON ( SLIP.CUSTOMER_CODE = SLIP3.CUSTOMER_CODE
            AND SLIP.ART_CUTOFF_DATE = SLIP3.CD )
	LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CAT1 ON (SLIP.SALES_CM_CATEGORY = CAT1.CATEGORY_CODE AND CAT1.CATEGORY_ID = /*salesCmCategory*/32)
WHERE
	-- 全ての金額がゼロの場合表示しないよ
	(
		COALESCE(SLIP.LAST_ART_PRICE,0) != 0
		OR (COALESCE(SLIP.DEPOSIT_PRICE,0) + COALESCE(SLIP.ADJ_PRICE,0)) != 0
		OR COALESCE(SLIP.SALES_PRICE,0) != 0
		OR COALESCE(SLIP.RGU_PRICE,0) != 0
		OR COALESCE(SLIP.DCT_PRICE,0) != 0
		OR COALESCE(SLIP.ETC_PRICE,0) != 0
		OR COALESCE(SLIP.CTAX_PRICE,0) != 0
		OR COALESCE(SLIP.THIS_ART_PRICE,0) != 0
	)
	/*IF targetDate != null */
	AND SLIP.ART_YM = /*targetDate*/201001
	/*END*/
	/*IF customerCodeFrom != null */
	AND SLIP.CUSTOMER_CODE >= /*customerCodeFrom*/'1'
	/*END*/
	/*IF customerCodeTo != null */
	AND SLIP.CUSTOMER_CODE <= /*customerCodeTo*/'1'
	/*END*/
ORDER BY CUSTOMER_CODE