SELECT
	COUNT(DISTINCT SLIP.APT_BALANCE_ID)
FROM
	APT_BALANCE_TRN_/*$domainId*/ SLIP
	INNER JOIN PO_LINE_TRN_/*$domainId*/ PO_LINE ON SLIP.PO_LINE_ID = PO_LINE.PO_LINE_ID
	INNER JOIN SUPPLIER_LINE_TRN_/*$domainId*/ SP_LINE ON SLIP.SUPPLIER_LINE_ID = SP_LINE.SUPPLIER_LINE_ID
/*BEGIN*/
WHERE
	/*IF targetDate != null */
	AND SLIP.APT_YM = /*targetDate*/201001
	/*END*/
	/*IF supplierCode != null */
	AND SLIP.SUPPLIER_CODE = /*supplierCode*/'1'
	/*END*/
/*END*/
