SELECT
	SLIP.SUPPLIER_NAME,
	SLIP.PRODUCT_CODE,
	SLIP.PRODUCT_NAME,
	SLIP.SUPPLIER_PCODE,
	SLIP.QUANTITY,
	SLIP.UNIT_RETAIL_PRICE,
	SLIP.RETAIL_PRICE,
	CASE
		WHEN S.RATE_ID IS NOT NULL THEN NULL
		ELSE
			CASE
				WHEN (SELECT TAX_FRACT_CATEGORY FROM MINE_MST_/*$domainId*/) = '0' THEN
					TRUNCATE(SLIP.RETAIL_PRICE * (SELECT TAX_RATE / 100 FROM TAX_RATE_MST_/*$domainId*/ R WHERE PO_SLIP.PO_DATE >= R.START_DATE ORDER BY R.START_DATE DESC LIMIT 1), 0)
				WHEN (SELECT TAX_FRACT_CATEGORY FROM MINE_MST_/*$domainId*/) = '1' THEN
					TRUNCATE(SLIP.RETAIL_PRICE * (SELECT TAX_RATE / 100 FROM TAX_RATE_MST_/*$domainId*/ R WHERE PO_SLIP.PO_DATE >= R.START_DATE ORDER BY R.START_DATE DESC LIMIT 1) + 0.5, 0)
				WHEN (SELECT TAX_FRACT_CATEGORY FROM MINE_MST_/*$domainId*/) = '2' THEN
					TRUNCATE(SLIP.RETAIL_PRICE * (SELECT TAX_RATE / 100 FROM TAX_RATE_MST_/*$domainId*/ R WHERE PO_SLIP.PO_DATE >= R.START_DATE ORDER BY R.START_DATE DESC LIMIT 1) + 0.9, 0)
				ELSE NULL
			END
	END AS CTAX_PRICE,
	SLIP.DOL_UNIT_PRICE,
	SLIP.DOL_PRICE,
	SLIP.PO_SLIP_ID,
	PO_LINE.LINE_NO AS PO_LINE_NO,
	SLIP.SUPPLIER_SLIP_ID,
	SP_LINE.LINE_NO AS SUPPLIER_LINE_NO,
	SLIP.SUPPLIER_DATE,
	SLIP.UNPAID_PRICE
FROM
	APT_BALANCE_TRN_/*$domainId*/ SLIP
	INNER JOIN PO_SLIP_TRN_/*$domainId*/ PO_SLIP ON SLIP.PO_SLIP_ID=PO_SLIP.PO_SLIP_ID
	INNER JOIN PO_LINE_TRN_/*$domainId*/ PO_LINE ON SLIP.PO_LINE_ID = PO_LINE.PO_LINE_ID
	INNER JOIN SUPPLIER_LINE_TRN_/*$domainId*/ SP_LINE ON SLIP.SUPPLIER_LINE_ID = SP_LINE.SUPPLIER_LINE_ID
	INNER JOIN SUPPLIER_MST_/*$domainId*/ S ON SLIP.SUPPLIER_CODE = S.SUPPLIER_CODE
/*BEGIN*/
WHERE
	/*IF targetDate != null */
	AND SLIP.APT_YM = /*targetDate*/201001
	/*END*/
	/*IF supplierCode != null */
	AND SLIP.SUPPLIER_CODE = /*supplierCode*/'1'
	/*END*/
/*END*/
ORDER BY SLIP.SUPPLIER_CODE,SLIP.PRODUCT_CODE
