SELECT
	A.PRODUCT_CODE
	,IFNULL(SUM(A.REST_QUANTITY), 0) AS QUANTITY
FROM
	(
		SELECT
				RL.PRODUCT_CODE
				,RL.QUANTITY - IFNULL(SX.QUANTITY,0) AS REST_QUANTITY
		FROM
			RO_LINE_TRN_/*$domainId*/ RL
			LEFT OUTER JOIN
			(
				SELECT
					SL.PRODUCT_CODE AS PRODUCT_CODE
					,SL.RO_LINE_ID AS RO_LINE_ID
					,SUM(SL.QUANTITY) AS QUANTITY
				FROM
					SALES_SLIP_TRN_/*$domainId*/ SS
					INNER JOIN SALES_LINE_TRN_/*$domainId*/ SL ON SS.SALES_SLIP_ID = SL.SALES_SLIP_ID
				WHERE
					SS.SALES_DATE <= CURDATE()
			    	AND SL.PRODUCT_CODE = /*productCode*/'AAA'
				GROUP BY SL.PRODUCT_CODE,SL.RO_LINE_ID
			) SX ON RL.PRODUCT_CODE = SX.PRODUCT_CODE AND RL.RO_LINE_ID = SX.RO_LINE_ID
	    WHERE
	    	RL.PRODUCT_CODE = /*productCode*/'AAA'
    	/*IF setProductCode != null*/
		UNION ALL
		SELECT
			PS.PRODUCT_CODE
			,(RL.QUANTITY - IFNULL(SX.QUANTITY,0))*PS.QUANTITY AS REST_QUANTITY
		FROM
			RO_LINE_TRN_/*$domainId*/ RL
			INNER JOIN PRODUCT_SET_MST_/*$domainId*/ PS ON RL.PRODUCT_CODE = PS.SET_PRODUCT_CODE AND PS.PRODUCT_CODE = /*productCode*/'XM2S-37**'
			LEFT OUTER JOIN
			(
				SELECT
					SL.PRODUCT_CODE AS PRODUCT_CODE
					,SL.RO_LINE_ID AS RO_LINE_ID
					,SUM(SL.QUANTITY) AS QUANTITY
				FROM
					SALES_SLIP_TRN_/*$domainId*/ SS
					INNER JOIN SALES_LINE_TRN_/*$domainId*/ SL ON SS.SALES_SLIP_ID = SL.SALES_SLIP_ID
				WHERE
					SS.SALES_DATE <= CURDATE()
			    	AND SL.PRODUCT_CODE IN /*setProductCode*/('BBB','XXX')
				GROUP BY SL.PRODUCT_CODE,SL.RO_LINE_ID
			) SX ON RL.PRODUCT_CODE = SX.PRODUCT_CODE AND RL.RO_LINE_ID = SX.RO_LINE_ID
		WHERE
			RL.PRODUCT_CODE IN /*setProductCode*/('BBB','CCC')
		/*END*/
	) A
GROUP BY
	A.PRODUCT_CODE
