SELECT
    A.DELIVERY_SLIP_ID,
    A.SALES_SLIP_ID AS INVOICE_SALES_SLIP_ID,
    B.SALES_SLIP_ID,
    B.CUSTOMER_CODE
FROM
    INVOICE_DATA_WORK_/*$domainId*/ A
    LEFT OUTER JOIN
      SALES_SLIP_TRN_/*$domainId*/ B
      ON A.SALES_SLIP_ID = B.SALES_SLIP_ID
WHERE
    A.USER_ID=/*userId*/''
ORDER BY
	DELIVERY_SLIP_ID