SELECT
        PS.PICKING_LIST_ID
		,PS.RO_DATE
		,PS.SALES_ANNUAL
		,PS.SALES_MONTHLY
		,PS.SALES_YM
		,PS.RO_SLIP_ID
		,PS.SALES_SLIP_ID
		,PS.RECEPT_NO
		,PS.SALES_CM_CATEGORY
		,PS.PICKING_REMARKS
		,PS.REMARKS
		,PS.CUSTOMER_CODE
		,PS.CUSTOMER_NAME
		,PS.CUSTOMER_PC_NAME
		,PS.CUSTOMER_ZIP_CODE
		,PS.CUSTOMER_ADDRESS_1
		,PS.CUSTOMER_ADDRESS_2
		,PS.CUSTOMER_TEL
		,PS.CUSTOMER_REMARKS
		,PS.DELIVERY_CODE
		,PS.DELIVERY_NAME
		,PS.DELIVERY_KANA
		,PS.DELIVERY_OFFICE_NAME
		,PS.DELIVERY_OFFICE_KANA
		,PS.DELIVERY_DEPT_NAME
		,PS.DELIVERY_ZIP_CODE
		,PS.DELIVERY_ADDRESS_1
		,PS.DELIVERY_ADDRESS_2
		,PS.DELIVERY_PC_NAME
		,PS.DELIVERY_PC_KANA
		,PS.DELIVERY_PC_PRE_CATEGORY
		,PS.DELIVERY_PC_PRE
		,PS.DELIVERY_TEL
		,PS.DELIVERY_FAX
		,PS.DELIVERY_EMAIL
		,PS.DELIVERY_URL
		,PS.BA_CODE
		,PS.TAX_SHIFT_CATEGORY
		,PS.TAX_FRACT_CATEGORY
		,PS.PRICE_FRACT_CATEGORY
		,PS.CTAX_PRICE_TOTAL
		,PS.PRICE_TOTAL
		,PS.PRINT_DATE
		,PS.COD_SC
		,PS.CRE_FUNC
		,PS.CRE_DATETM
		,PS.CRE_USER
		,PS.UPD_FUNC
		,PS.UPD_DATETM
		,PS.UPD_USER
		,PS.CUSTOMER_OFFICE_NAME
		,PS.CUSTOMER_OFFICE_KANA
		,PS.CUSTOMER_ABBR
		,PS.CUSTOMER_DEPT_NAME
		,PS.CUSTOMER_PC_POST
		,PS.CUSTOMER_PC_KANA
		,PS.CUSTOMER_PC_PRE_CATEGORY
		,PS.CUSTOMER_PC_PRE
		,PS.CUSTOMER_FAX
		,PS.CUSTOMER_EMAIL
		,PS.CUSTOMER_URL
FROM
	PICKING_LIST_TRN_/*$domainId*/ PS
    /*BEGIN*/
	WHERE
		/*IF pickingListId != null */
		PS.PICKING_LIST_ID = /*pickingListId*/0
		/*END*/
		/*IF roSlipId != null */
		PS.RO_SLIP_ID = /*roSlipId*/0
		/*END*/
		/*IF salesSlipId != null */
		PS.SALES_SLIP_ID = /*salesSlipId*/0
		/*END*/
		/*IF receptNo != null */
		PL.RECEPT_NO = /*receptNo*/0
		/*END*/
	/*END*/
	/*BEGIN*/
	ORDER BY
		/*IF customerCode != null */
		PS./*customerCode*/CUSTOMER_CODE
		/*END*/

		/*IF sortOrder != null*/
		/*$sortOrder*/
		/*END*/
	/*END*/
	/*BEGIN*/
		LIMIT /*rowCount*/100 OFFSET /*offsetRow*/0
	/*END*/
	/*IF lockRecord != null */
	/*$lockRecord*/
	/*END*/
