INSERT
    INTO
	PICKING_LIST_TRN_/*$domainId*/ (
		PICKING_LIST_ID
		,RO_DATE
		,SALES_ANNUAL
		,SALES_MONTHLY
		,SALES_YM
		,RO_SLIP_ID
		,SALES_SLIP_ID
		,RECEPT_NO
		,SALES_CM_CATEGORY
		,PICKING_REMARKS
		,REMARKS
		,CUSTOMER_CODE
		,CUSTOMER_NAME
		,CUSTOMER_PC_NAME
		,CUSTOMER_ZIP_CODE
		,CUSTOMER_ADDRESS_1
		,CUSTOMER_ADDRESS_2
		,CUSTOMER_TEL
		,CUSTOMER_REMARKS
		,DELIVERY_CODE
		,DELIVERY_NAME
		,DELIVERY_KANA
		,DELIVERY_OFFICE_NAME
		,DELIVERY_OFFICE_KANA
		,DELIVERY_DEPT_NAME
		,DELIVERY_ZIP_CODE
		,DELIVERY_ADDRESS_1
		,DELIVERY_ADDRESS_2
		,DELIVERY_PC_NAME
		,DELIVERY_PC_KANA
		,DELIVERY_PC_PRE_CATEGORY
		,DELIVERY_PC_PRE
		,DELIVERY_TEL
		,DELIVERY_FAX
		,DELIVERY_EMAIL
		,DELIVERY_URL
		,BA_CODE
		,TAX_SHIFT_CATEGORY
		,TAX_FRACT_CATEGORY
		,PRICE_FRACT_CATEGORY
		,CTAX_PRICE_TOTAL
		,PRICE_TOTAL
		,PRINT_DATE
		,COD_SC
		,CRE_FUNC
		,CRE_DATETM
		,CRE_USER
		,UPD_FUNC
		,UPD_DATETM
		,UPD_USER
		,CUSTOMER_OFFICE_NAME
		,CUSTOMER_OFFICE_KANA
		,CUSTOMER_ABBR
		,CUSTOMER_DEPT_NAME
		,CUSTOMER_PC_POST
		,CUSTOMER_PC_KANA
		,CUSTOMER_PC_PRE_CATEGORY
		,CUSTOMER_PC_PRE
		,CUSTOMER_FAX
		,CUSTOMER_EMAIL
		,CUSTOMER_URL
	) VALUES (
		/*pickingListId*/0
		,/*roDate*/NULL
		,/*salesAnnual*/NULL
		,/*salesMonthly*/NULL
		,/*salesYm*/NULL
		,/*roSlipId*/NULL
		,/*salesSlipId*/NULL
		,/*receptNo*/NULL
		,/*salesCmCategory*/NULL
		,/*pickingRemarks*/NULL
		,/*remarks*/NULL
		,/*customerCode*/NULL
		,/*customerName*/NULL
		,/*customerPcName*/NULL
		,/*customerZipCode*/NULL
		,/*customerAddress1*/NULL
		,/*customerAddress2*/NULL
		,/*customerTel*/NULL
		,/*customerRemarks*/NULL
		,/*deliveryCode*/NULL
		,/*deliveryName*/NULL
		,/*deliveryKana*/NULL
		,/*deliveryOfficeName*/NULL
		,/*deliveryOfficeKana*/NULL
		,/*deliveryDeptName*/NULL
		,/*deliveryZipCode*/NULL
		,/*deliveryAddress1*/NULL
		,/*deliveryAddress2*/NULL
		,/*deliveryPcName*/NULL
		,/*deliveryPcKana*/NULL
		,/*deliveryPcPreCategory*/NULL
		,/*deliveryPcPre*/NULL
		,/*deliveryTel*/NULL
		,/*deliveryFax*/NULL
		,/*deliveryEmail*/NULL
		,/*deliveryUrl*/NULL
		,/*baCode*/NULL
		,/*taxShiftCategory*/NULL
		,/*taxFractCategory*/NULL
		,/*priceFractCategory*/NULL
		,/*ctaxPriceTotal*/NULL
		,/*priceTotal*/NULL
		,/*printDate*/NULL
		,/*codSc*/NULL
		,/*creFunc*/NULL
		,now()
		,/*creUser*/NULL
		,/*updFunc*/NULL
		,now()
		,/*updUser*/NULL
		,/*customerOfficeName*/NULL
		,/*customerOfficeKana*/NULL
		,/*customerAbbr*/NULL
		,/*customerDeptName*/NULL
		,/*customerPcPost*/NULL
		,/*customerPcKana*/NULL
		,/*customerPcPreCategory*/NULL
		,/*customerPcPre*/NULL
		,/*customerFax*/NULL
		,/*customerEmail*/NULL
		,/*customerUrl*/NULL
)
