/*カテゴリ名修正*/
UPDATE CATEGORY_MST_XXXXX SET CATEGORY_NAME = '通販サイト支払条件'
 WHERE CATEGORY_ID = '48';
UPDATE CATEGORY_MST_XXXXX SET CATEGORY_NAME = '通販サイト顧客属性'
 WHERE CATEGORY_ID = '60';
UPDATE CATEGORY_MST_XXXXX SET CATEGORY_NAME = '通販サイト請求書送付先'
 WHERE CATEGORY_ID = '61';
UPDATE CATEGORY_MST_XXXXX SET CATEGORY_NAME = '配送業者支払区分'
 WHERE CATEGORY_ID = '63';
