SELECT
	SLIP.HIST_ID,
	SLIP.ACTION_TYPE,
	SLIP.ACTION_FUNC,
	SLIP.REC_DATETM,
	SLIP.REC_USER,
	R.CUSTOMER_CODE,
	CATT.CATEGORY_CODE_NAME,
	SLIP.DELIVERY_CODE,
	SLIP.DELIVERY_NAME,
	SLIP.DELIVERY_KANA,
	SLIP.DELIVERY_OFFICE_NAME,
	SLIP.DELIVERY_OFFICE_KANA,
	SLIP.DELIVERY_DEPT_NAME,
	SLIP.DELIVERY_ZIP_CODE,
	SLIP.DELIVERY_ADDRESS_1,
	SLIP.DELIVERY_ADDRESS_2,
	SLIP.DELIVERY_PC_NAME,
	SLIP.DELIVERY_PC_KANA,
	SLIP.DELIVERY_PC_PRE_CATEGORY,
	SLIP.DELIVERY_TEL,
	SLIP.DELIVERY_FAX,
	SLIP.DELIVERY_EMAIL,
	SLIP.DELIVERY_URL,
	SLIP.REMARKS,
	SLIP.CRE_FUNC,
	SLIP.CRE_DATETM,
	SLIP.CRE_USER,
	SLIP.UPD_FUNC,
	SLIP.UPD_DATETM,
	SLIP.UPD_USER
FROM
    DELIVERY_MST_HIST_/*$domainId*/ SLIP
        LEFT OUTER JOIN (
        	SELECT
        		CUSTOMER_CODE, REL_CODE, CUST_REL_CATEGORY
        	FROM
        		CUSTOMER_REL_HIST_/*$domainId*/
        	group by
        		CUSTOMER_CODE, REL_CODE, CUST_REL_CATEGORY ) R
            ON SLIP.DELIVERY_CODE = R.REL_CODE
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CATT
        	ON R.CUST_REL_CATEGORY = CATT.CATEGORY_CODE AND CATT.CATEGORY_ID='67'
/*BEGIN*/
WHERE
	/*IF actionType != null */
	AND SLIP.ACTION_TYPE = /*actionType*/'S'
	/*END*/
	/*IF recDateFrom != null */
	AND CAST(SLIP.REC_DATETM AS DATE) >= CAST(/*recDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF recDateTo != null */
	AND CAST(SLIP.REC_DATETM AS DATE) <= CAST(/*recDateTo*/'2010/01/01' AS DATE)
	/*END*/
	/*IF customerCodeFrom != null */
	AND R.CUSTOMER_CODE >= /*customerCodeFrom*/'S'
	/*END*/
	/*IF customerCodeTo != null */
	AND R.CUSTOMER_CODE <= /*customerCodeTo*/'S'
	/*END*/
	/*IF creDateFrom != null */
	AND CAST(SLIP.CRE_DATETM AS DATE) >= CAST(/*creDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF creDateTo != null */
	AND CAST(SLIP.CRE_DATETM AS DATE) <= CAST(/*creDateTo*/'2010/01/01' AS DATE)
	/*END*/
/*END*/
ORDER BY SLIP.HIST_ID
