SELECT
	DISTINCT
	SLIP.HIST_ID,
	SLIP.ACTION_TYPE,
	SLIP.ACTION_FUNC,
	SLIP.REC_DATETM,
	SLIP.REC_USER,
	SLIP.SUPPLIER_SLIP_ID,
	SLIP.STATUS,
	SLIP.SUPPLIER_DATE,
	SLIP.SUPPLIER_ANNUAL,
	SLIP.SUPPLIER_MONTHLY,
	SLIP.SUPPLIER_YM,
	SLIP.USER_ID,
	SLIP.USER_NAME,
	SLIP.SUPPLIER_SLIP_CATEGORY,
	SLIP.SUPPLIER_CODE,
	SLIP.SUPPLIER_NAME,
	SLIP.SUPPLIER_CM_CATEGORY,
	SLIP.DELIVERY_DATE,
	SLIP.RATE_ID,
	SLIP.TAX_SHIFT_CATEGORY,
	SLIP.TAX_FRACT_CATEGORY,
	SLIP.PRICE_FRACT_CATEGORY,
	SLIP.CTAX_TOTAL,
	SLIP.PRICE_TOTAL,
	SLIP.FE_PRICE_TOTAL,
	SLIP.PO_SLIP_ID,
	SLIP.PAYMENT_SLIP_ID,
	SLIP.SUPPLIER_PAYMENT_DATE,
	SLIP.PAYMENT_CUTOFF_DATE,
	SLIP.PAYMENT_PDATE,
	SLIP.REMARKS,
	SLIP.CRE_FUNC,
	SLIP.CRE_DATETM,
	SLIP.CRE_USER,
	SLIP.UPD_FUNC,
	SLIP.UPD_DATETM,
	SLIP.UPD_USER
FROM
	SUPPLIER_SLIP_TRN_HIST_/*$domainId*/ SLIP
	INNER JOIN SUPPLIER_LINE_TRN_HIST_/*$domainId*/ LINE ON SLIP.SUPPLIER_SLIP_ID = LINE.SUPPLIER_SLIP_ID
/*BEGIN*/
WHERE
	/*IF actionType != null */
	AND SLIP.ACTION_TYPE = /*actionType*/'S'
	/*END*/
	/*IF recDateFrom != null */
	AND CAST(SLIP.REC_DATETM AS DATE) >= CAST(/*recDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF recDateTo != null */
	AND CAST(SLIP.REC_DATETM AS DATE) <= CAST(/*recDateTo*/'2010/01/01' AS DATE)
	/*END*/
	/*IF supplierCodeFrom != null */
	AND SLIP.SUPPLIER_CODE >= /*supplierCodeFrom*/'S'
	/*END*/
	/*IF supplierCodeTo != null */
	AND SLIP.SUPPLIER_CODE <= /*supplierCodeTo*/'S'
	/*END*/
	/*IF productCodeFrom != null */
	AND LINE.PRODUCT_CODE >= /*productCodeFrom*/'S'
	/*END*/
	/*IF productCodeTo != null */
	AND LINE.PRODUCT_CODE <= /*productCodeTo*/'S'
	/*END*/
	/*IF deliveryDateFrom != null */
	AND SLIP.DELIVERY_DATE >= CAST(/*deliveryDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF deliveryDateTo != null */
	AND SLIP.DELIVERY_DATE <= CAST(/*deliveryDateTo*/'2010/01/01' AS DATE)
	/*END*/
/*END*/
ORDER BY SLIP.HIST_ID
