SELECT
	SLIP.HIST_ID,
	SLIP.ACTION_TYPE,
	SLIP.ACTION_FUNC,
	SLIP.REC_DATETM,
	SLIP.REC_USER,
	SLIP.SUPPLIER_CODE,
	SLIP.SUPPLIER_NAME,
	SLIP.SUPPLIER_KANA,
	SLIP.SUPPLIER_ABBR,
	SLIP.SUPPLIER_ZIP_CODE,
	SLIP.SUPPLIER_ADDRESS_1,
	SLIP.SUPPLIER_ADDRESS_2,
	SLIP.SUPPLIER_DEPT_NAME,
	SLIP.SUPPLIER_PC_NAME,
	SLIP.SUPPLIER_PC_KANA,
	SLIP.SUPPLIER_PC_PRE_CATEGORY,
	SLIP.SUPPLIER_PC_POST,
	SLIP.SUPPLIER_TEL,
	SLIP.SUPPLIER_FAX,
	SLIP.SUPPLIER_EMAIL,
	SLIP.SUPPLIER_URL,
	SLIP.SUPPLIER_CM_CATEGORY,
	SLIP.TAX_SHIFT_CATEGORY,
	SLIP.PAYMENT_TYPE_CATEGORY,
	SLIP.PAYMENT_CYCLE_CATEGORY,
	SLIP.LAST_CUTOFF_DATE,
	SLIP.PAYMENT_DATE,
	SLIP.TAX_FRACT_CATEGORY,
	SLIP.PRICE_FRACT_CATEGORY,
	SLIP.PO_SLIP_COMEOUT_CATEGORY,
	SLIP.SERVICE_CHARGE_CATEGORY,
	SLIP.TRANSFER_TYPE_CATEGORY,
	SLIP.NATIONAL_CATEGORY,
	SLIP.RATE_ID,
	SLIP.REMARKS,
	SLIP.COMMENT_DATA,
	SLIP.CRE_FUNC,
	SLIP.CRE_DATETM,
	SLIP.CRE_USER,
	SLIP.UPD_FUNC,
	SLIP.UPD_DATETM,
	SLIP.UPD_USER
FROM
	SUPPLIER_MST_HIST_/*$domainId*/ SLIP
/*BEGIN*/
WHERE
	/*IF actionType != null */
	AND SLIP.ACTION_TYPE = /*actionType*/'S'
	/*END*/
	/*IF recDateFrom != null */
	AND CAST(SLIP.REC_DATETM AS DATE) >= CAST(/*recDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF recDateTo != null */
	AND CAST(SLIP.REC_DATETM AS DATE) <= CAST(/*recDateTo*/'2010/01/01' AS DATE)
	/*END*/
	/*IF supplierCodeFrom != null */
	AND SLIP.SUPPLIER_CODE >= /*supplierCodeFrom*/'S'
	/*END*/
	/*IF supplierCodeTo != null */
	AND SLIP.SUPPLIER_CODE <= /*supplierCodeTo*/'S'
	/*END*/
	/*IF creDateFrom != null */
	AND CAST(SLIP.CRE_DATETM AS DATE) >= CAST(/*creDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF creDateTo != null */
	AND CAST(SLIP.CRE_DATETM AS DATE) <= CAST(/*creDateTo*/'2010/01/01' AS DATE)
	/*END*/
/*END*/
ORDER BY SLIP.HIST_ID
