SELECT
	DISTINCT
	LINE.HIST_ID,
	LINE.ACTION_TYPE,
	LINE.ACTION_FUNC,
	LINE.REC_DATETM,
	LINE.REC_USER,
	LINE.DEPOSIT_LINE_ID,
	LINE.STATUS,
	LINE.DEPOSIT_SLIP_ID,
	LINE.LINE_NO,
	LINE.DEPOSIT_CATEGORY,
	LINE.PRICE,
	LINE.INST_DATE,
	LINE.INST_NO,
	LINE.BANK_ID,
	LINE.BANK_INFO,
	LINE.REMARKS,
	LINE.SALES_LINE_ID,
	LINE.CRE_FUNC,
	LINE.CRE_DATETM,
	LINE.CRE_USER,
	LINE.UPD_FUNC,
	LINE.UPD_DATETM,
	LINE.UPD_USER
FROM
	DEPOSIT_SLIP_TRN_HIST_/*$domainId*/ SLIP
	INNER JOIN DEPOSIT_LINE_TRN_HIST_/*$domainId*/ LINE ON SLIP.DEPOSIT_SLIP_ID = LINE.DEPOSIT_SLIP_ID
/*BEGIN*/
WHERE
	/*IF actionType != null */
	AND SLIP.ACTION_TYPE = /*actionType*/'S'
	/*END*/
	/*IF recDateFrom != null */
	AND CAST(LINE.REC_DATETM AS DATE) >= CAST(/*recDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF recDateTo != null */
	AND CAST(LINE.REC_DATETM AS DATE) <= CAST(/*recDateTo*/'2010/01/01' AS DATE)
	/*END*/
	/*IF customerCodeFrom != null */
	AND SLIP.CUSTOMER_CODE >= /*customerCodeFrom*/'S'
	/*END*/
	/*IF customerCodeTo != null */
	AND SLIP.CUSTOMER_CODE <= /*customerCodeTo*/'S'
	/*END*/
/*END*/
ORDER BY LINE.HIST_ID
