SELECT
	SLIP.HIST_ID,
	SLIP.ACTION_TYPE,
	SLIP.ACTION_FUNC,
	SLIP.REC_DATETM,
	SLIP.REC_USER,
	SLIP.DEPOSIT_SLIP_ID,
	SLIP.STATUS,
	SLIP.DEPOSIT_DATE,
	SLIP.INPUT_PDATE,
	SLIP.DEPOSIT_ANNUAL,
	SLIP.DEPOSIT_MONTHLY,
	SLIP.DEPOSIT_YM,
	SLIP.USER_ID,
	SLIP.USER_NAME,
	SLIP.DEPOSIT_ABSTRACT,
	SLIP.REMARKS,
	SLIP.CUSTOMER_CODE,
	SLIP.CUSTOMER_NAME,
	SLIP.CUSTOMER_REMARKS,
	SLIP.CUSTOMER_COMMENT_DATA,
	SLIP.CUTOFF_GROUP,
	SLIP.PAYBACK_CYCLE_CATEGORY,
	SLIP.BA_CODE,
	SLIP.BA_NAME,
	SLIP.BA_KANA,
	SLIP.BA_OFFICE_NAME,
	SLIP.BA_OFFICE_KANA,
	SLIP.BA_DEPT_NAME,
	SLIP.BA_ZIP_CODE,
	SLIP.BA_ADDRESS_1,
	SLIP.BA_ADDRESS_2,
	SLIP.BA_PC_NAME,
	SLIP.BA_PC_KANA,
	SLIP.BA_PC_PRE_CATRGORY,
	SLIP.BA_PC_PRE,
	SLIP.BA_TEL,
	SLIP.BA_FAX,
	SLIP.BA_EMAIL,
	SLIP.BA_URL,
	SLIP.SALES_CM_CATEGORY,
	SLIP.DEPOSIT_CATEGORY,
	SLIP.DEPOSIT_TOTAL,
	SLIP.BILL_ID,
	SLIP.BILL_CUTOFF_DATE,
	SLIP.BILL_CUTOFF_PDATE,
	SLIP.ART_ID,
	SLIP.SALES_SLIP_ID,
	SLIP.DEPOSIT_METHOD_TYPE_CATEGORY,
	SLIP.TAX_FRACT_CATEGORY,
	SLIP.PRICE_FRACT_CATEGORY,
	SLIP.CRE_FUNC,
	SLIP.CRE_DATETM,
	SLIP.CRE_USER,
	SLIP.UPD_FUNC,
	SLIP.UPD_DATETM,
	SLIP.UPD_USER
FROM
	DEPOSIT_SLIP_TRN_HIST_/*$domainId*/ SLIP
/*BEGIN*/
WHERE
	/*IF actionType != null */
	AND SLIP.ACTION_TYPE = /*actionType*/'S'
	/*END*/
	/*IF recDateFrom != null */
	AND CAST(SLIP.REC_DATETM AS DATE) >= CAST(/*recDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF recDateTo != null */
	AND CAST(SLIP.REC_DATETM AS DATE) <= CAST(/*recDateTo*/'2010/01/01' AS DATE)
	/*END*/
	/*IF customerCodeFrom != null */
	AND SLIP.CUSTOMER_CODE >= /*customerCodeFrom*/'S'
	/*END*/
	/*IF customerCodeTo != null */
	AND SLIP.CUSTOMER_CODE <= /*customerCodeTo*/'S'
	/*END*/
/*END*/
ORDER BY SLIP.HIST_ID
