SELECT
	DISTINCT
	LINE.HIST_ID,
	LINE.ACTION_TYPE,
	LINE.ACTION_FUNC,
	LINE.REC_DATETM,
	LINE.REC_USER,
	LINE.ESTIMATE_LINE_ID,
	LINE.ESTIMATE_SHEET_ID,
	LINE.LINE_NO,
	LINE.PRODUCT_CODE,
	LINE.CUSTOMER_PCODE,
	LINE.PRODUCT_ABSTRACT,
	LINE.QUANTITY,
	LINE.UNIT_COST,
	LINE.UNIT_RETAIL_PRICE,
	LINE.COST,
	LINE.RETAIL_PRICE,
	LINE.REMARKS,
	LINE.CRE_FUNC,
	LINE.CRE_DATETM,
	LINE.CRE_USER,
	LINE.UPD_FUNC,
	LINE.UPD_DATETM,
	LINE.UPD_USER
FROM
	ESTIMATE_SHEET_TRN_HIST_/*$domainId*/ SLIP
	INNER JOIN ESTIMATE_LINE_TRN_HIST_/*$domainId*/ LINE ON SLIP.ESTIMATE_SHEET_ID = LINE.ESTIMATE_SHEET_ID
/*BEGIN*/
WHERE
	/*IF actionType != null */
	AND SLIP.ACTION_TYPE = /*actionType*/'S'
	/*END*/
	/*IF recDateFrom != null */
	AND CAST(LINE.REC_DATETM AS DATE) >= CAST(/*recDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF recDateTo != null */
	AND CAST(LINE.REC_DATETM AS DATE) <= CAST(/*recDateTo*/'2010/01/01' AS DATE)
	/*END*/
	/*IF estimateDateFrom != null */
	AND SLIP.ESTIMATE_DATE >= CAST(/*estimateDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF estimateDateTo != null */
	AND SLIP.ESTIMATE_DATE <= CAST(/*estimateDateTo*/'2010/01/01' AS DATE)
	/*END*/
/*END*/
ORDER BY LINE.HIST_ID
