SELECT
	DISTINCT
	SLIP.HIST_ID,
	SLIP.ACTION_TYPE,
	SLIP.ACTION_FUNC,
	SLIP.REC_DATETM,
	SLIP.REC_USER,
	SLIP.PAYMENT_SLIP_ID,
	SLIP.STATUS,
	SLIP.PAYMENT_DATE,
	SLIP.PAYMENT_ANNUAL,
	SLIP.PAYMENT_MONTHLY,
	SLIP.PAYMENT_YM,
	SLIP.USER_ID,
	SLIP.USER_NAME,
	SLIP.PAYMENT_SLIP_CATEGORY,
	SLIP.SUPPLIER_CODE,
	SLIP.SUPPLIER_NAME,
	SLIP.RATE_ID,
	SLIP.TAX_SHIFT_CATEGORY,
	SLIP.TAX_FRACT_CATEGORY,
	SLIP.PRICE_FRACT_CATEGORY,
	SLIP.PRICE_TOTAL,
	SLIP.FE_PRICE_TOTAL,
	SLIP.PO_SLIP_ID,
	SLIP.SUPPLIER_SLIP_ID,
	SLIP.APT_BALANCE_ID,
	SLIP.PAYMENT_CUTOFF_DATE,
	SLIP.PAYMENT_PDATE,
	SLIP.REMARKS,
	SLIP.CRE_FUNC,
	SLIP.CRE_DATETM,
	SLIP.CRE_USER,
	SLIP.UPD_FUNC,
	SLIP.UPD_DATETM,
	SLIP.UPD_USER
FROM
	PAYMENT_SLIP_TRN_HIST_/*$domainId*/ SLIP
	INNER JOIN PAYMENT_LINE_TRN_HIST_/*$domainId*/ LINE ON SLIP.PAYMENT_SLIP_ID = LINE.PAYMENT_SLIP_ID
/*BEGIN*/
WHERE
	/*IF actionType != null */
	AND SLIP.ACTION_TYPE = /*actionType*/'S'
	/*END*/
	/*IF recDateFrom != null */
	AND CAST(SLIP.REC_DATETM AS DATE) >= CAST(/*recDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF recDateTo != null */
	AND CAST(SLIP.REC_DATETM AS DATE) <= CAST(/*recDateTo*/'2010/01/01' AS DATE)
	/*END*/
	/*IF supplierCodeFrom != null */
	AND SLIP.SUPPLIER_CODE >= /*supplierCodeFrom*/'S'
	/*END*/
	/*IF supplierCodeTo != null */
	AND SLIP.SUPPLIER_CODE <= /*supplierCodeTo*/'S'
	/*END*/
	/*IF productCodeFrom != null */
	AND LINE.PRODUCT_CODE >= /*productCodeFrom*/'S'
	/*END*/
	/*IF productCodeTo != null */
	AND LINE.PRODUCT_CODE <= /*productCodeTo*/'S'
	/*END*/
	/*IF paymentDateFrom != null */
	AND SLIP.PAYMENT_DATE >= CAST(/*paymentDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF paymentDateTo != null */
	AND SLIP.PAYMENT_DATE <= CAST(/*paymentDateTo*/'2010/01/01' AS DATE)
	/*END*/
/*END*/
ORDER BY SLIP.HIST_ID
