SELECT
	DISTINCT
	SLIP.HIST_ID,
	SLIP.ACTION_TYPE,
	SLIP.ACTION_FUNC,
	SLIP.REC_DATETM,
	SLIP.REC_USER,
	SLIP.EAD_SLIP_ID,
	SLIP.EAD_DATE,
	SLIP.EAD_ANNUAL,
	SLIP.EAD_MONTHLY,
	SLIP.EAD_YM,
	SLIP.USER_ID,
	SLIP.USER_NAME,
	SLIP.EAD_SLIP_CATEGORY,
	SLIP.EAD_CATEGORY,
	SLIP.REMARKS,
	SLIP.SRC_FUNC,
	SLIP.SALES_SLIP_ID,
	SLIP.SUPPLIER_SLIP_ID,
	SLIP.MOVE_DEPOSIT_SLIP_ID,
	SLIP.STOCK_PDATE,
	SLIP.CRE_FUNC,
	SLIP.CRE_DATETM,
	SLIP.CRE_USER,
	SLIP.UPD_FUNC,
	SLIP.UPD_DATETM,
	SLIP.UPD_USER
FROM
	EAD_SLIP_TRN_HIST_/*$domainId*/ SLIP
	INNER JOIN EAD_LINE_TRN_HIST_/*$domainId*/ LINE ON SLIP.EAD_SLIP_ID = LINE.EAD_SLIP_ID
/*BEGIN*/
WHERE
	/*IF actionType != null */
	AND SLIP.ACTION_TYPE = /*actionType*/'S'
	/*END*/
	/*IF recDateFrom != null */
	AND CAST(SLIP.REC_DATETM AS DATE) >= CAST(/*recDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF recDateTo != null */
	AND CAST(SLIP.REC_DATETM AS DATE) <= CAST(/*recDateTo*/'2010/01/01' AS DATE)
	/*END*/
	/*IF productCodeFrom != null */
	AND LINE.PRODUCT_CODE >= /*productCodeFrom*/'S'
	/*END*/
	/*IF productCodeTo != null */
	AND LINE.PRODUCT_CODE <= /*productCodeTo*/'S'
	/*END*/
	/*IF eadSlipCategory != null */
	AND SLIP.EAD_SLIP_CATEGORY IN /*eadSlipCategory*/('1','2')
	/*END*/
/*END*/
ORDER BY SLIP.HIST_ID
