SELECT
	DISTINCT
	LINE.HIST_ID,
	LINE.ACTION_TYPE,
	LINE.ACTION_FUNC,
	LINE.REC_DATETM,
	LINE.REC_USER,
	LINE.SALES_LINE_ID,
	LINE.STATUS,
	LINE.SALES_SLIP_ID,
	LINE.LINE_NO,
	LINE.RO_LINE_ID,
	LINE.SALES_DETAIL_CATEGORY,
	LINE.PRODUCT_CODE,
	LINE.CUSTOMER_PCODE,
	LINE.PRODUCT_ABSTRACT,
	LINE.PRODUCT_REMARKS,
	LINE.QUANTITY,
	LINE.DELIVERY_PROCESS_CATEGORY,
	LINE.UNIT_PRICE,
	LINE.UNIT_CATEGORY,
	LINE.UNIT_NAME,
	LINE.PACK_QUANTITY,
	LINE.UNIT_RETAIL_PRICE,
	LINE.RETAIL_PRICE,
	LINE.UNIT_COST,
	LINE.COST,
	LINE.TAX_CATEGORY,
	LINE.CTAX_RATE,
	LINE.CTAX_PRICE,
	LINE.GM,
	LINE.REMARKS,
	LINE.EAD_REMARKS,
	LINE.RACK_CODE_SRC,
	LINE.CRE_FUNC,
	LINE.CRE_DATETM,
	LINE.CRE_USER,
	LINE.UPD_FUNC,
	LINE.UPD_DATETM,
	LINE.UPD_USER
FROM
	SALES_SLIP_TRN_HIST_/*$domainId*/ SLIP
	INNER JOIN SALES_LINE_TRN_HIST_/*$domainId*/ LINE ON SLIP.SALES_SLIP_ID = LINE.SALES_SLIP_ID
/*BEGIN*/
WHERE
	/*IF actionType != null */
	AND SLIP.ACTION_TYPE = /*actionType*/'S'
	/*END*/
	/*IF recDateFrom != null */
	AND CAST(LINE.REC_DATETM AS DATE) >= CAST(/*recDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF recDateTo != null */
	AND CAST(LINE.REC_DATETM AS DATE) <= CAST(/*recDateTo*/'2010/01/01' AS DATE)
	/*END*/
	/*IF customerCodeFrom != null */
	AND SLIP.CUSTOMER_CODE >= /*customerCodeFrom*/'S'
	/*END*/
	/*IF customerCodeTo != null */
	AND SLIP.CUSTOMER_CODE <= /*customerCodeTo*/'S'
	/*END*/
	/*IF productCodeFrom != null */
	AND LINE.PRODUCT_CODE >= /*productCodeFrom*/'S'
	/*END*/
	/*IF productCodeTo != null */
	AND LINE.PRODUCT_CODE <= /*productCodeTo*/'S'
	/*END*/
/*END*/
ORDER BY LINE.HIST_ID
