SELECT
	SLIP.HIST_ID,
	SLIP.ACTION_TYPE,
	SLIP.ACTION_FUNC,
	SLIP.REC_DATETM,
	SLIP.REC_USER,
	SLIP.PRODUCT_CODE,
	SLIP.PRODUCT_NAME,
	SLIP.PRODUCT_KANA,
	SLIP.ONLINE_PCODE,
	SLIP.SUPPLIER_PCODE,
	SLIP.SUPPLIER_CODE,
	SLIP.RACK_CODE,
	SLIP.SUPPLIER_PRICE_YEN,
	SLIP.SUPPLIER_PRICE_DOL,
	SLIP.RETAIL_PRICE,
	SLIP.SO_RATE,
	SLIP.UNIT_CATEGORY,
	SLIP.PACK_QUANTITY,
	SLIP.JAN_PCODE,
	SLIP.WIDTH,
	SLIP.WIDTH_UNIT_SIZE_CATEGORY,
	SLIP.DEPTH,
	SLIP.DEPTH_UNIT_SIZE_CATEGORY,
	SLIP.HEIGHT,
	SLIP.HEIGHT_UNIT_SIZE_CATEGORY,
	SLIP.WEIGHT,
	SLIP.WEIGHT_UNIT_SIZE_CATEGORY,
	SLIP.LENGTH,
	SLIP.LENGTH_UNIT_SIZE_CATEGORY,
	SLIP.PO_LOT,
	SLIP.LOT_UPD_FLAG,
	SLIP.LEAD_TIME,
	SLIP.PO_NUM,
	SLIP.PO_UPD_FLAG,
	SLIP.AVG_SHIP_COUNT,
	SLIP.MAX_STOCK_NUM,
	SLIP.STOCK_UPD_FLAG,
	SLIP.TERM_SHIP_NUM,
	SLIP.MAX_PO_NUM,
	SLIP.MAX_PO_UPD_FLAG,
	SLIP.FRACT_CATEGORY,
	SLIP.TAX_CATEGORY,
	SLIP.STOCK_CTL_CATEGORY,
	SLIP.STOCK_ASSES_CATEGORY,
	SLIP.PRODUCT_CATEGORY,
	SLIP.PRODUCT_1,
	SLIP.PRODUCT_2,
	SLIP.PRODUCT_3,
	SLIP.RO_MAX_NUM,
	SLIP.PRODUCT_RANK,
	SLIP.SET_TYPE_CATEGORY,
	SLIP.PRODUCT_STATUS_CATEGORY,
	SLIP.PRODUCT_STOCK_CATEGORY,
	SLIP.PRODUCT_PURVAY_CATEGORY,
	SLIP.PRODUCT_STANDARD_CATEGORY,
	SLIP.CORE_NUM,
	SLIP.NUM_1,
	SLIP.NUM_2,
	SLIP.NUM_3,
	SLIP.NUM_4,
	SLIP.NUM_5,
	SLIP.DEC_1,
	SLIP.DEC_2,
	SLIP.DEC_3,
	SLIP.DEC_4,
	SLIP.DEC_5,
	SLIP.DISCARD_DATE,
	SLIP.REMARKS,
	SLIP.EAD_REMARKS,
	SLIP.COMMENT_DATA,
	SLIP.LAST_RO_DATE,
	SLIP.CRE_FUNC,
	SLIP.CRE_DATETM,
	SLIP.CRE_USER,
	SLIP.UPD_FUNC,
	SLIP.UPD_DATETM,
	SLIP.UPD_USER,
	CASE WHEN DRH.ACTION_TYPE='DELETE' THEN '' ELSE DRH.DISCOUNT_ID END AS DISCOUNT_ID
FROM
	PRODUCT_MST_HIST_/*$domainId*/ SLIP
        LEFT OUTER JOIN DISCOUNT_REL_HIST_/*$domainId*/ DRH
            ON SLIP.PRODUCT_CODE = DRH.PRODUCT_CODE
               AND DRH.REC_DATETM =
			   ( SELECT max(REC_DATETM)
			   	 FROM DISCOUNT_REL_HIST_/*$domainId*/ DRH2
			 	 WHERE DRH2.REC_DATETM <= SLIP.REC_DATETM
			 		AND DRH2.PRODUCT_CODE = SLIP.PRODUCT_CODE
				GROUP BY PRODUCT_CODE
				)
/*BEGIN*/
WHERE
	/*IF actionType != null */
	AND SLIP.ACTION_TYPE = /*actionType*/'S'
	/*END*/
	/*IF recDateFrom != null */
	AND CAST(SLIP.REC_DATETM AS DATE) >= CAST(/*recDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF recDateTo != null */
	AND CAST(SLIP.REC_DATETM AS DATE) <= CAST(/*recDateTo*/'2010/01/01' AS DATE)
	/*END*/
	/*IF productCodeFrom != null */
	AND SLIP.PRODUCT_CODE >= /*productCodeFrom*/'S'
	/*END*/
	/*IF productCodeTo != null */
	AND SLIP.PRODUCT_CODE <= /*productCodeTo*/'S'
	/*END*/
	/*IF creDateFrom != null */
	AND CAST(SLIP.CRE_DATETM AS DATE) >= CAST(/*creDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF creDateTo != null */
	AND CAST(SLIP.CRE_DATETM AS DATE) <= CAST(/*creDateTo*/'2010/01/01' AS DATE)
	/*END*/
/*END*/
ORDER BY SLIP.HIST_ID
