SELECT
	DISTINCT
	LINE.HIST_ID,
	LINE.ACTION_TYPE,
	LINE.ACTION_FUNC,
	LINE.REC_DATETM,
	LINE.REC_USER,
	LINE.EAD_LINE_ID,
	LINE.EAD_SLIP_ID,
	LINE.LINE_NO,
	LINE.PRODUCT_CODE,
	LINE.PRODUCT_ABSTRACT,
	LINE.RACK_CODE,
	LINE.RACK_NAME,
	LINE.QUANTITY,
	LINE.REMARKS,
	LINE.SALES_LINE_ID,
	LINE.SUPPLIER_LINE_ID,
	LINE.CRE_FUNC,
	LINE.CRE_DATETM,
	LINE.CRE_USER,
	LINE.UPD_FUNC,
	LINE.UPD_DATETM,
	LINE.UPD_USER
FROM
	EAD_SLIP_TRN_HIST_/*$domainId*/ SLIP
	INNER JOIN EAD_LINE_TRN_HIST_/*$domainId*/ LINE ON SLIP.EAD_SLIP_ID = LINE.EAD_SLIP_ID
/*BEGIN*/
WHERE
	/*IF actionType != null */
	AND SLIP.ACTION_TYPE = /*actionType*/'S'
	/*END*/
	/*IF recDateFrom != null */
	AND CAST(LINE.REC_DATETM AS DATE) >= CAST(/*recDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF recDateTo != null */
	AND CAST(LINE.REC_DATETM AS DATE) <= CAST(/*recDateTo*/'2010/01/01' AS DATE)
	/*END*/
	/*IF productCodeFrom != null */
	AND LINE.PRODUCT_CODE >= /*productCodeFrom*/'S'
	/*END*/
	/*IF productCodeTo != null */
	AND LINE.PRODUCT_CODE <= /*productCodeTo*/'S'
	/*END*/
	/*IF eadSlipCategory != null */
	AND SLIP.EAD_SLIP_CATEGORY IN /*eadSlipCategory*/('1','2')
	/*END*/
/*END*/
ORDER BY LINE.HIST_ID
