SELECT
	DISTINCT
	LINE.HIST_ID,
	LINE.ACTION_TYPE,
	LINE.ACTION_FUNC,
	LINE.REC_DATETM,
	LINE.REC_USER,
	LINE.SUPPLIER_LINE_ID,
	LINE.STATUS,
	LINE.SUPPLIER_SLIP_ID,
	LINE.LINE_NO,
	LINE.PRODUCT_CODE,
	LINE.SUPPLIER_PCODE,
	LINE.PRODUCT_ABSTRACT,
	LINE.PRODUCT_REMARKS,
	LINE.SUPPLIER_DETAIL_CATEGORY,
	LINE.DELIVERY_PROCESS_CATEGORY,
	LINE.TEMP_UNIT_PRICE_CATEGORY,
	LINE.TAX_CATEGORY,
	LINE.DELIVERY_DATE,
	LINE.QUANTITY,
	LINE.UNIT_PRICE,
	LINE.PRICE,
	LINE.CTAX_RATE,
	LINE.CTAX_PRICE,
	LINE.DOL_UNIT_PRICE,
	LINE.DOL_PRICE,
	LINE.RATE,
	LINE.REMARKS,
	LINE.RACK_CODE,
	LINE.RACK_NAME,
	LINE.PO_LINE_ID,
	LINE.PAYMENT_LINE_ID,
	LINE.CRE_FUNC,
	LINE.CRE_DATETM,
	LINE.CRE_USER,
	LINE.UPD_FUNC,
	LINE.UPD_DATETM,
	LINE.UPD_USER
FROM
	SUPPLIER_SLIP_TRN_HIST_/*$domainId*/ SLIP
	INNER JOIN SUPPLIER_LINE_TRN_HIST_/*$domainId*/ LINE ON SLIP.SUPPLIER_SLIP_ID = LINE.SUPPLIER_SLIP_ID
/*BEGIN*/
WHERE
	/*IF actionType != null */
	AND SLIP.ACTION_TYPE = /*actionType*/'S'
	/*END*/
	/*IF recDateFrom != null */
	AND CAST(LINE.REC_DATETM AS DATE) >= CAST(/*recDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF recDateTo != null */
	AND CAST(LINE.REC_DATETM AS DATE) <= CAST(/*recDateTo*/'2010/01/01' AS DATE)
	/*END*/
	/*IF supplierCodeFrom != null */
	AND SLIP.SUPPLIER_CODE >= /*supplierCodeFrom*/'S'
	/*END*/
	/*IF supplierCodeTo != null */
	AND SLIP.SUPPLIER_CODE <= /*supplierCodeTo*/'S'
	/*END*/
	/*IF productCodeFrom != null */
	AND LINE.PRODUCT_CODE >= /*productCodeFrom*/'S'
	/*END*/
	/*IF productCodeTo != null */
	AND LINE.PRODUCT_CODE <= /*productCodeTo*/'S'
	/*END*/
	/*IF deliveryDateFrom != null */
	AND SLIP.DELIVERY_DATE >= CAST(/*deliveryDateFrom*/'2010/01/01' AS DATE)
	/*END*/
	/*IF deliveryDateTo != null */
	AND SLIP.DELIVERY_DATE <= CAST(/*deliveryDateTo*/'2010/01/01' AS DATE)
	/*END*/
/*END*/
ORDER BY LINE.HIST_ID
