SELECT
	PL.PRODUCT_CODE
	,SUM(PL.QUANTITY - IFNULL(PX.QUANTITY,0)) AS QUANTITY
FROM
	PO_LINE_TRN_/*$domainId*/ PL
	INNER JOIN PO_SLIP_TRN_/*$domainId*/ PS ON PL.PO_SLIP_ID = PS.PO_SLIP_ID
	LEFT OUTER JOIN
	(
		SELECT
			SL.PRODUCT_CODE
			,SL.PO_LINE_ID
			,SUM(SL.QUANTITY) AS QUANTITY
		FROM
			SUPPLIER_LINE_TRN_/*$domainId*/ SL
			INNER JOIN SUPPLIER_SLIP_TRN_/*$domainId*/ SS ON SS.SUPPLIER_SLIP_ID = SL.SUPPLIER_SLIP_ID
		WHERE
			SS.SUPPLIER_DATE <= CURDATE()
			AND SL.PRODUCT_CODE = /*productCode*/'P'
		GROUP BY SL.PRODUCT_CODE,SL.PO_LINE_ID
	) PX ON PL.PRODUCT_CODE = PX.PRODUCT_CODE AND PL.PO_LINE_ID = PX.PO_LINE_ID
/*BEGIN*/
WHERE
	/*IF productCode != null */
	PL.PRODUCT_CODE = /*productCode*/'P'
	/*END*/
	AND PL.STATUS NOT IN ('2','3')
	/*IF transportCategory != null */
	AND PS.TRANSPORT_CATEGORY IN /*transportCategory*/('A','B')
	/*END*/
/*END*/
GROUP BY
	PL.PRODUCT_CODE