SELECT
NULL					AS PO_LINE_ID
,NULL					AS STATUS
,NULL					AS DISP_STATUS
,NULL					AS PO_SLIP_ID
,NULL					AS LINE_NO
,LINE.PRODUCT_CODE			AS PRODUCT_CODE
,PRODMST.SUPPLIER_PCODE		AS SUPPLIER_PCODE
,PRODMST.PRODUCT_NAME	AS PRODUCT_ABSTRACT
,LINE.QUANTITY			AS QUANTITY
,PRODMST.PO_LOT				AS PO_LOT
,PRODMST.MAX_PO_NUM			AS MAX_PO_NUM
,PRODMST.MAX_STOCK_NUM		AS MAX_STOCK_NUM
,NULL						AS TEMP_UNIT_PRICE_CATEGORY
,PRODMST.TAX_CATEGORY		AS TAX_CATEGORY
,SUPP.SUPPLIER_CM_CATEGORY	AS SUPPLIER_CM_CATEGORY
,LINE.UNIT_PRICE			AS UNIT_PRICE
,LINE.PRICE					AS PRICE
,LINE.CTAX_PRICE			AS CTAX_PRICE
,LINE.CTAX_RATE				AS CTAX_RATE
,LINE.DOL_UNIT_PRICE		AS DOL_UNIT_PRICE
,LINE.DOL_PRICE				AS DOL_PRICE
,LINE.RATE					AS RATE
,NULL						AS DELIVERY_DATE
,LINE.REMARKS				AS REMARKS
,LINE.PRODUCT_REMARKS		AS PRODUCT_REMARKS
,NULL						AS REST_QUANTITY
,NULL						AS CRE_FUNC
,NULL						AS CRE_DATETM
,NULL						AS CRE_USER
,NULL						AS UPD_FUNC
,NULL						AS UPD_DATETM
,NULL						AS UPD_USER
FROM
		PO_LINE_TRN_/*$domainId*/ LINE
		INNER JOIN PO_SLIP_TRN_/*$domainId*/ SLIP
			ON SLIP.PO_SLIP_ID = LINE.PO_SLIP_ID
		INNER JOIN SUPPLIER_MST_/*$domainId*/ SUPP
			ON SLIP.SUPPLIER_CODE = SUPP.SUPPLIER_CODE
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ STATUSCAT
			ON STATUSCAT.CATEGORY_ID = /*poLineStatusCategory*/
			AND STATUSCAT.CATEGORY_CODE = LINE.STATUS
		LEFT OUTER JOIN PRODUCT_MST_/*$domainId*/ PRODMST
			ON PRODMST.PRODUCT_CODE = LINE.PRODUCT_CODE
	WHERE
		LINE.PO_SLIP_ID=/*poSlipId*/
	ORDER BY
		LINE.LINE_NO ASC
