INSERT
	INTO
		PO_LINE_TRN_/*$domainId*/ (
			PO_LINE_ID
			,STATUS
			,PO_SLIP_ID
			,LINE_NO
			,PRODUCT_CODE
			,SUPPLIER_PCODE
			,PRODUCT_ABSTRACT
			,QUANTITY
			,TEMP_UNIT_PRICE_CATEGORY
			,TAX_CATEGORY
			,SUPPLIER_CM_CATEGORY
			,UNIT_PRICE
			,PRICE
			,CTAX_PRICE
			,CTAX_RATE
			,DOL_UNIT_PRICE
			,DOL_PRICE
			,RATE
			,DELIVERY_DATE
			,REMARKS
			,PRODUCT_REMARKS
			,REST_QUANTITY
			,CRE_FUNC
			,CRE_DATETM
			,CRE_USER
			,UPD_FUNC
			,UPD_DATETM
			,UPD_USER
		)
SELECT
			/*poLineId*/
			,0
			,/*poSlipId*/
			,/*lineNo*/
			,/*productCode*/
			,PRD.SUPPLIER_PCODE
			,PRD.PRODUCT_NAME
			,/*quantity*/
			,NULL
			,PRD.TAX_CATEGORY
			,SUP.SUPPLIER_CM_CATEGORY
			,PRD.SUPPLIER_PRICE_YEN
			,COALESCE(PRD.SUPPLIER_PRICE_YEN,0) * COALESCE(/*quantity*/0
																		,0)
			,COALESCE(PRD.SUPPLIER_PRICE_YEN,0) * COALESCE(/*quantity*/0
																		,0) * TAXRATE.SUPPLIER_TAX_RATE / 100.0
			,TAXRATE.SUPPLIER_TAX_RATE
			,CASE WHEN RATE.SUPPLIER_RATE IS NULL THEN NULL
				ELSE PRD.SUPPLIER_PRICE_DOL
				END
			,CASE WHEN (RATE.SUPPLIER_RATE IS NULL)
						OR (PRD.SUPPLIER_PRICE_DOL IS NULL) THEN NULL
				ELSE COALESCE(PRD.SUPPLIER_PRICE_DOL,0) * COALESCE(/*quantity*/0
																				,0)
				END
			,RATE.SUPPLIER_RATE
			,/*deliveryDate*/
			,''
			,PRD.REMARKS
			,/*quantity*/
			,/*creFunc*/
			,NOW()
			,/*creUser*/
			,/*updFunc*/
			,NOW()
			,/*updUser*/
FROM
	PO_SLIP_TRN_/*$domainId*/ PS
	INNER JOIN PRODUCT_MST_/*$domainId*/ PRD
		ON PRD.PRODUCT_CODE = /*productCode*/
	INNER JOIN SUPPLIER_MST_/*$domainId*/ SUP
		ON SUP.SUPPLIER_CODE = /*supplierCode*/

	-- レート抽出
	LEFT OUTER JOIN(
		SELECT
			PS.SUPPLIER_CODE 			AS SUPPLIER_CODE
			,RTRN.RATE 					AS SUPPLIER_RATE
		FROM
			PO_SLIP_TRN_/*$domainId*/ PS
			LEFT OUTER JOIN RATE_MST_/*$domainId*/ RMST
					ON PS.RATE_ID = RMST.RATE_ID
				LEFT OUTER JOIN RATE_TRN_/*$domainId*/ RTRN
					ON RMST.RATE_ID = RTRN.RATE_ID
		WHERE
			PS.PO_SLIP_ID = /*poSlipId*/
			AND RTRN.START_DATE <= PS.PO_DATE
	ORDER BY
		RTRN.START_DATE DESC LIMIT 1
	) RATE
		ON RATE.SUPPLIER_CODE = SUP.SUPPLIER_CODE

	-- 消費税率抽出
	LEFT OUTER JOIN(
		SELECT
			PS.SUPPLIER_CODE 			AS SUPPLIER_CODE
			,TMST.TAX_RATE				AS SUPPLIER_TAX_RATE
		FROM
			PO_SLIP_TRN_/*$domainId*/ PS
			INNER JOIN TAX_RATE_MST_/*$domainId*/ TMST
				ON TMST.TAX_TYPE_CATEGORY = /*taxTypeCategory*/
		WHERE
			PS.PO_SLIP_ID = /*poSlipId*/
			AND PS.TAX_SHIFT_CATEGORY IN /*taxShiftCategoryList*/('2','3')
			AND TMST.START_DATE <= PS.PO_DATE
			AND PS.RATE_ID IS NULL
		ORDER BY
			TMST.START_DATE DESC LIMIT 1
	) TAXRATE
		ON TAXRATE.SUPPLIER_CODE = SUP.SUPPLIER_CODE

WHERE
	PS.PO_SLIP_ID = /*poSlipId*/
