UPDATE
	PO_LINE_TRN_/*$domainId*/
	SET
		QUANTITY = (
			SELECT TEMPVALUE FROM
			(
			SELECT
				CASE WHEN MINE.NUM_DEC_ALIGNMENT >= 0 AND MINE.NUM_DEC_ALIGNMENT <= /*numAlignMax*/ THEN
					CASE COALESCE(QUAFCATM.CATEGORY_CODE,MINE.PRODUCT_FRACT_CATEGORY)
						WHEN /*roundDownId*/'0'	THEN TRUNCATE(PL.QUANTITY,MINE.NUM_DEC_ALIGNMENT)
						WHEN /*halfUpId*/'1'	THEN ROUND(PL.QUANTITY,MINE.NUM_DEC_ALIGNMENT)
						WHEN /*roundUpId*/'2'	THEN TRUNCATE(PL.QUANTITY + 0.9 * POW(10,- MINE.NUM_DEC_ALIGNMENT) * SIGN(PL.QUANTITY) ,MINE.NUM_DEC_ALIGNMENT)
						ELSE PL.QUANTITY END
				ELSE PL.QUANTITY END AS TEMPVALUE
				FROM
					PO_LINE_TRN_/*$domainId*/ PL
					INNER JOIN PO_SLIP_TRN_/*$domainId*/ PS
						ON PS.PO_SLIP_ID = PL.PO_SLIP_ID
					INNER JOIN MINE_MST_/*$domainId*/ MINE
						ON COMPANY_NAME IS NOT NULL
					LEFT OUTER JOIN PRODUCT_MST_/*$domainId*/ PM
						ON PM.PRODUCT_CODE = PL.PRODUCT_CODE
					LEFT OUTER JOIN SUPPLIER_MST_/*$domainId*/ SUP
						ON SUP.SUPPLIER_CODE = PS.SUPPLIER_CODE
					LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ QUAFCATM
						ON QUAFCATM.CATEGORY_ID = /*quantityFractCategoryId*/
						AND PM.FRACT_CATEGORY = QUAFCATM.CATEGORY_CODE
				WHERE
					PO_LINE_ID = /*poLineId*/
			) TEMPTABLE
		)
		,UNIT_PRICE = (
			SELECT TEMPVALUE FROM
			(
			SELECT
				CASE COALESCE(SLIPPRIFCATM.CATEGORY_CODE ,SUPPPRIFCATM.CATEGORY_CODE ,MINE.PRICE_FRACT_CATEGORY)
					WHEN /*roundDownId*/'0'	THEN TRUNCATE(PL.UNIT_PRICE,0)
					WHEN /*halfUpId*/'1'	THEN ROUND(PL.UNIT_PRICE,0)
					WHEN /*roundUpId*/'2'	THEN TRUNCATE(PL.UNIT_PRICE + 0.9 * SIGN(PL.UNIT_PRICE) ,0)
				ELSE PL.UNIT_PRICE END AS TEMPVALUE
				FROM
					PO_LINE_TRN_/*$domainId*/ PL
					INNER JOIN PO_SLIP_TRN_/*$domainId*/ PS
						ON PS.PO_SLIP_ID = PL.PO_SLIP_ID
					INNER JOIN MINE_MST_/*$domainId*/ MINE
						ON COMPANY_NAME IS NOT NULL
					LEFT OUTER JOIN SUPPLIER_MST_/*$domainId*/ SUP
						ON SUP.SUPPLIER_CODE = PS.SUPPLIER_CODE
					LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ SUPPPRIFCATM
						ON SUPPPRIFCATM.CATEGORY_ID = /*priceFractCategoryId*/
						AND SUP.PRICE_FRACT_CATEGORY = SUPPPRIFCATM.CATEGORY_CODE
					LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ SLIPPRIFCATM
						ON SLIPPRIFCATM.CATEGORY_ID = /*priceFractCategoryId*/
						AND PS.PRICE_FRACT_CATEGORY = SLIPPRIFCATM.CATEGORY_CODE
				WHERE
					PO_LINE_ID = /*poLineId*/
			) TEMPTABLE
		)
		,PRICE = (
			SELECT TEMPVALUE FROM
			(
			SELECT
				CASE COALESCE(SLIPPRIFCATM.CATEGORY_CODE ,SUPPPRIFCATM.CATEGORY_CODE ,MINE.PRICE_FRACT_CATEGORY)
					WHEN /*roundDownId*/'0'	THEN TRUNCATE(PL.PRICE,0)
					WHEN /*halfUpId*/'1'	THEN ROUND(PL.PRICE,0)
					WHEN /*roundUpId*/'2'	THEN TRUNCATE(PL.PRICE + 0.9 * SIGN(PL.PRICE) ,0)
				ELSE PL.PRICE END AS TEMPVALUE
				FROM
					PO_LINE_TRN_/*$domainId*/ PL
					INNER JOIN PO_SLIP_TRN_/*$domainId*/ PS
						ON PS.PO_SLIP_ID = PL.PO_SLIP_ID
					INNER JOIN MINE_MST_/*$domainId*/ MINE
						ON COMPANY_NAME IS NOT NULL
					LEFT OUTER JOIN SUPPLIER_MST_/*$domainId*/ SUP
						ON SUP.SUPPLIER_CODE = PS.SUPPLIER_CODE
					LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ SUPPPRIFCATM
						ON SUPPPRIFCATM.CATEGORY_ID = /*priceFractCategoryId*/
						AND SUP.PRICE_FRACT_CATEGORY = SUPPPRIFCATM.CATEGORY_CODE
					LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ SLIPPRIFCATM
						ON SLIPPRIFCATM.CATEGORY_ID = /*priceFractCategoryId*/
						AND PS.PRICE_FRACT_CATEGORY = SLIPPRIFCATM.CATEGORY_CODE
				WHERE
					PO_LINE_ID = /*poLineId*/
			) TEMPTABLE
		)
		,CTAX_PRICE = (
			SELECT TEMPVALUE FROM
			(
			SELECT
				CASE COALESCE(SLIPTAXFCATM.CATEGORY_CODE ,SUPPTAXFCATM.CATEGORY_CODE ,MINE.PRICE_FRACT_CATEGORY)
					WHEN /*roundDownId*/'0'	THEN TRUNCATE(PL.CTAX_PRICE,0)
					WHEN /*halfUpId*/'1'	THEN ROUND(PL.CTAX_PRICE,0)
					WHEN /*roundUpId*/'2'	THEN TRUNCATE(PL.CTAX_PRICE + 0.9 * SIGN(PL.CTAX_PRICE) ,0)
				ELSE PL.CTAX_PRICE END AS TEMPVALUE
				FROM
					PO_LINE_TRN_/*$domainId*/ PL
					INNER JOIN PO_SLIP_TRN_/*$domainId*/ PS
						ON PS.PO_SLIP_ID = PL.PO_SLIP_ID
					INNER JOIN MINE_MST_/*$domainId*/ MINE
						ON COMPANY_NAME IS NOT NULL
					LEFT OUTER JOIN SUPPLIER_MST_/*$domainId*/ SUP
						ON SUP.SUPPLIER_CODE = PS.SUPPLIER_CODE
					LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ SUPPTAXFCATM
						ON SUPPTAXFCATM.CATEGORY_ID = /*taxFractCategoryId*/
						AND SUP.PRICE_FRACT_CATEGORY = SUPPTAXFCATM.CATEGORY_CODE
					LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ SLIPTAXFCATM
						ON SLIPTAXFCATM.CATEGORY_ID = /*taxFractCategoryId*/
						AND PS.PRICE_FRACT_CATEGORY = SLIPTAXFCATM.CATEGORY_CODE
				WHERE
					PO_LINE_ID = /*poLineId*/
			) TEMPTABLE
		)
		,DOL_UNIT_PRICE = (
			SELECT TEMPVALUE FROM
			(
			SELECT
				CASE WHEN MINE.UNIT_PRICE_DEC_ALIGNMENT >= 0 AND MINE.UNIT_PRICE_DEC_ALIGNMENT <= /*priceAlignMax*/ THEN
					CASE COALESCE(SLIPPRIFCATM.CATEGORY_CODE ,SUPPPRIFCATM.CATEGORY_CODE ,MINE.PRICE_FRACT_CATEGORY)
						WHEN /*roundDownId*/'0'	THEN TRUNCATE(PL.DOL_UNIT_PRICE,UNIT_PRICE_DEC_ALIGNMENT)
						WHEN /*halfUpId*/'1'	THEN ROUND(PL.DOL_UNIT_PRICE,UNIT_PRICE_DEC_ALIGNMENT)
						WHEN /*roundUpId*/'2'	THEN TRUNCATE(PL.DOL_UNIT_PRICE + 0.9 * POW(10,- MINE.UNIT_PRICE_DEC_ALIGNMENT) * SIGN(PL.DOL_UNIT_PRICE) ,MINE.UNIT_PRICE_DEC_ALIGNMENT)
					ELSE PL.DOL_UNIT_PRICE END
				ELSE PL.DOL_UNIT_PRICE END AS TEMPVALUE
				FROM
					PO_LINE_TRN_/*$domainId*/ PL
					INNER JOIN PO_SLIP_TRN_/*$domainId*/ PS
						ON PS.PO_SLIP_ID = PL.PO_SLIP_ID
					INNER JOIN MINE_MST_/*$domainId*/ MINE
						ON COMPANY_NAME IS NOT NULL
					LEFT OUTER JOIN SUPPLIER_MST_/*$domainId*/ SUP
						ON SUP.SUPPLIER_CODE = PS.SUPPLIER_CODE
					LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ SUPPPRIFCATM
						ON SUPPPRIFCATM.CATEGORY_ID = /*priceFractCategoryId*/
						AND SUP.PRICE_FRACT_CATEGORY = SUPPPRIFCATM.CATEGORY_CODE
					LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ SLIPPRIFCATM
						ON SLIPPRIFCATM.CATEGORY_ID = /*priceFractCategoryId*/
						AND PS.PRICE_FRACT_CATEGORY = SLIPPRIFCATM.CATEGORY_CODE
				WHERE
					PO_LINE_ID = /*poLineId*/
			) TEMPTABLE
		)
		,DOL_PRICE = (
			SELECT TEMPVALUE FROM
			(
			SELECT
				CASE WHEN MINE.UNIT_PRICE_DEC_ALIGNMENT >= 0 AND MINE.UNIT_PRICE_DEC_ALIGNMENT <= /*priceAlignMax*/ THEN
					CASE COALESCE(SLIPPRIFCATM.CATEGORY_CODE ,SUPPPRIFCATM.CATEGORY_CODE ,MINE.PRICE_FRACT_CATEGORY)
						WHEN /*roundDownId*/'0'	THEN TRUNCATE(PL.DOL_PRICE,UNIT_PRICE_DEC_ALIGNMENT)
						WHEN /*halfUpId*/'1'	THEN ROUND(PL.DOL_PRICE,UNIT_PRICE_DEC_ALIGNMENT)
						WHEN /*roundUpId*/'2'	THEN TRUNCATE(PL.DOL_PRICE + 0.9 * POW(10,- MINE.UNIT_PRICE_DEC_ALIGNMENT) * SIGN(PL.DOL_PRICE) ,MINE.UNIT_PRICE_DEC_ALIGNMENT)
					ELSE PL.DOL_PRICE END
				ELSE PL.DOL_PRICE END AS TEMPVALUE
				FROM
					PO_LINE_TRN_/*$domainId*/ PL
					INNER JOIN PO_SLIP_TRN_/*$domainId*/ PS
						ON PS.PO_SLIP_ID = PL.PO_SLIP_ID
					INNER JOIN MINE_MST_/*$domainId*/ MINE
						ON COMPANY_NAME IS NOT NULL
					LEFT OUTER JOIN SUPPLIER_MST_/*$domainId*/ SUP
						ON SUP.SUPPLIER_CODE = PS.SUPPLIER_CODE
					LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ SUPPPRIFCATM
						ON SUPPPRIFCATM.CATEGORY_ID = /*priceFractCategoryId*/
						AND SUP.PRICE_FRACT_CATEGORY = SUPPPRIFCATM.CATEGORY_CODE
					LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ SLIPPRIFCATM
						ON SLIPPRIFCATM.CATEGORY_ID = /*priceFractCategoryId*/
						AND PS.PRICE_FRACT_CATEGORY = SLIPPRIFCATM.CATEGORY_CODE
				WHERE
					PO_LINE_ID = /*poLineId*/
			) TEMPTABLE
		)
	WHERE
		PO_LINE_ID = /*poLineId*/