SELECT
	S.SALES_DATE
FROM
	SALES_LINE_TRN_/*$domainId*/ SL
       	LEFT OUTER JOIN SALES_SLIP_TRN_/*$domainId*/ S
       		ON ( SL.SALES_SLIP_ID = S.SALES_SLIP_ID )
WHERE
	SL.RO_LINE_ID = /*roLineId*/0
	AND S.SALES_SLIP_ID != /*salesSlipId*/0
ORDER BY
	S.SALES_DATE DESC
LIMIT 1 OFFSET 0
