SELECT
	D.DELIVERY_CODE
FROM
	CUSTOMER_REL_/*$domainId*/ CR
		LEFT OUTER JOIN DELIVERY_MST_/*$domainId*/ D ON CR.REL_CODE = D.DELIVERY_CODE
WHERE
	CR.CUSTOMER_CODE = /*customerCode*/ AND
	CR.CUST_REL_CATEGORY = /*custRelCategory*/
ORDER BY
	D.CRE_DATETM ASC
LIMIT 1

