SELECT
	P.PICKING_LINE_ID,
	P.PICKING_LIST_ID,
	P.SALES_LINE_ID,
	P.RO_LINE_ID,
	P.LINE_NO,
	P.SALES_DETAIL_CATEGORY,
	P.PRODUCT_CODE,
	P.CUSTOMER_PCODE,
	P.PRODUCT_ABSTRACT,
	P.QUANTITY,
	P.UNIT_PRICE,
	P.UNIT_CATEGORY,
	P.UNIT_NAME,
	P.PACK_QUANTITY,
	P.UNIT_RETAIL_PRICE,
	P.RETAIL_PRICE,
	P.UNIT_COST,
	P.COST,
	P.TAX_CATEGORY,
	P.CTAX_RATE,
	P.CTAX_PRICE,
	P.GM,
	P.RACK_CODE_SRC,
	P.STOCK_NUM,
	P.REMARKS,
	P.PICKING_REMARKS,
	P.SET_TYPE_CATEGORY,
	P.CRE_FUNC,
	P.CRE_DATETM,
	P.CRE_USER,
	P.UPD_FUNC,
	P.UPD_DATETM,
	P.UPD_USER
FROM
	PICKING_LINE_TRN_/*$domainId*/ P
/*BEGIN*/
WHERE
	/*IF pickingListId != null */
	AND P.PICKING_LIST_ID = /*pickingListId*/0
	/*END*/
	/*IF setTypeCategory != null */
	AND P.SET_TYPE_CATEGORY = /*setTypeCategory*/'x'
	/*END*/
/*END*/
