SELECT
        C.CUSTOMER_CODE
        ,C.CUSTOMER_NAME
        ,C.CUSTOMER_KANA
        ,C.CUSTOMER_OFFICE_NAME
        ,C.CUSTOMER_OFFICE_KANA
        ,C.CUSTOMER_ABBR
        ,C.CUSTOMER_DEPT_NAME
        ,C.CUSTOMER_ZIP_CODE
        ,C.CUSTOMER_ADDRESS_1
        ,C.CUSTOMER_ADDRESS_2
        ,C.CUSTOMER_PC_POST
        ,C.CUSTOMER_PC_NAME
        ,C.CUSTOMER_PC_KANA
        ,C.CUSTOMER_PC_PRE_CATEGORY
        ,C.CUSTOMER_TEL
        ,C.CUSTOMER_FAX
        ,C.CUSTOMER_EMAIL
        ,C.CUSTOMER_URL
        ,C.CUSTOMER_BUSINESS_CATEGORY
        ,C.CUSTOMER_JOB_CATEGORY
        ,C.CUSTOMER_RO_CATEGORY
        ,C.CUSTOMER_RANK_CATEGORY
        ,C.CUSTOMER_UPD_FLAG
        ,C.SALES_CM_CATEGORY
        ,C.TAX_SHIFT_CATEGORY
        ,C.RATE
        ,C.MAX_CREDIT_LIMIT
        ,C.LAST_CUTOFF_DATE
        ,C.CUTOFF_GROUP
        ,C.PAYBACK_TYPE_CATEGORY
        ,C.PAYBACK_CYCLE_CATEGORY
        ,C.TAX_FRACT_CATEGORY
        ,C.PRICE_FRACT_CATEGORY
        ,C.TEMP_DELIVERY_SLIP_FLAG
        ,C.PAYMENT_NAME
        ,C.REMARKS
        ,C.FIRST_SALES_DATE
        ,C.LAST_SALES_DATE
        ,C.SALES_PRICE_TOTAL
        ,C.SALES_PRICE_LSM
        ,C.COMMENT_DATA
		,C.CRE_FUNC
		,C.CRE_DATETM
		,C.CRE_USER
		,C.UPD_FUNC
		,C.UPD_DATETM
		,C.UPD_USER
		,C.LAST_SALES_CUTOFF_DATE
	,V.SALES_DATE
	,V.SALES_COUNT
FROM
	CUSTOMER_MST_/*$domainId*/ C
	,(
		SELECT
			S.CUSTOMER_CODE
			,S.SALES_DATE
			,count(S.CUSTOMER_CODE) SALES_COUNT
		FROM
			(
				SELECT
					S2.CUSTOMER_CODE
					,S2.SALES_DATE
				FROM
					SALES_SLIP_TRN_/*$domainId*/ S2,
					SALES_LINE_TRN_/*$domainId*/ L2
				WHERE
					S2.CUSTOMER_CODE = /*customerCode*/
					AND L2.SALES_SLIP_ID = S2.SALES_SLIP_ID
					AND S2.STATUS = '0'
					AND S2.SALES_CM_CATEGORY = '0'
					AND S2.SALES_DATE <= /*salesDate*/'2010/08/10'
			) S
		GROUP BY
			S.CUSTOMER_CODE,S.SALES_DATE
	) V
WHERE
	C.CUSTOMER_CODE = /*customerCode*/
	AND C.CUSTOMER_CODE = V.CUSTOMER_CODE
	AND V.SALES_COUNT > 1
