INSERT
    INTO
	SALES_LINE_TRN_/*$domainId*/ (
		SALES_LINE_ID
		,STATUS
		,SALES_SLIP_ID
		,LINE_NO
		,RO_LINE_ID
		,SALES_DETAIL_CATEGORY
		,PRODUCT_CODE
		,CUSTOMER_PCODE
		,PRODUCT_ABSTRACT
		,QUANTITY
		,DELIVERY_PROCESS_CATEGORY
		,UNIT_PRICE
		,UNIT_CATEGORY
		,UNIT_NAME
		,PACK_QUANTITY
		,UNIT_RETAIL_PRICE
		,RETAIL_PRICE
		,UNIT_COST
		,COST
		,TAX_CATEGORY
		,CTAX_RATE
		,CTAX_PRICE
		,GM
		,REMARKS
		,EAD_REMARKS
		,PRODUCT_REMARKS
		,RACK_CODE_SRC
		,CRE_FUNC
		,CRE_DATETM
		,CRE_USER
		,UPD_FUNC
		,UPD_DATETM
		,UPD_USER
) VALUES (
		/*salesLineId*/0
		,/*status*/NULL
		,/*salesSlipId*/NULL
		,/*lineNo*/NULL
		,/*roLineId*/NULL
		,/*salesDetailCategory*/NULL
		,/*productCode*/NULL
		,/*customerPcode*/NULL
		,/*productAbstract*/NULL
		,/*quantity*/NULL
		,/*deliveryProcessCategory*/NULL
		,/*unitPrice*/NULL
		,/*unitCategory*/NULL
		,/*unitName*/NULL
		,/*packQuantity*/NULL
		,/*unitRetailPrice*/NULL
		,/*retailPrice*/NULL
		,/*unitCost*/NULL
		,/*cost*/NULL
		,/*taxCategory*/NULL
		,/*ctaxRate*/NULL
		,/*ctaxPrice*/NULL
		,/*gm*/NULL
		,/*remarks*/NULL
		,/*eadRemarks*/NULL
		,/*productRemarks*/NULL
		,/*rackCodeSrc*/NULL
		,/*creFunc*/NULL
		,now()
		,/*creUser*/NULL
		,/*updFunc*/NULL
		,now()
		,/*updUser*/NULL
)
