UPDATE
        SALES_SLIP_TRN_/*$domainId*/'DEFAULT' SET
			BILL_PRINT_COUNT=BILL_PRINT_COUNT+/*billPrintCount*/0
			,DELIVERY_PRINT_COUNT=DELIVERY_PRINT_COUNT+/*deliveryPrintCount*/0
			,TEMP_DELIVERY_PRINT_COUNT=TEMP_DELIVERY_PRINT_COUNT+/*tempDeliveryPrintCount*/0
			,SHIPPING_PRINT_COUNT=SHIPPING_PRINT_COUNT+/*shippingPrintCount*/0
			,ESTIMATE_PRINT_COUNT=ESTIMATE_PRINT_COUNT+/*estimatePrintCount*/0
			,DELBOR_PRINT_COUNT=DELBOR_PRINT_COUNT+/*delborPrintCount*/0
			,SI_PRINT_COUNT=SI_PRINT_COUNT+/*siPrintCount*/0
			,PO_PRINT_COUNT=PO_PRINT_COUNT+/*poPrintCount*/0
	WHERE
		SALES_SLIP_ID=/*salesSlipId*/0
