SELECT
	DISTINCT
	SLIP.EAD_SLIP_ID,
	SLIP.EAD_DATE,
	SLIP.EAD_ANNUAL,
	SLIP.EAD_MONTHLY,
	SLIP.EAD_YM,
	SLIP.USER_ID,
	SLIP.USER_NAME,
	SLIP.EAD_SLIP_CATEGORY,
	SLIP.EAD_CATEGORY,
	SLIP.REMARKS,
	SLIP.SRC_FUNC,
	SLIP.SALES_SLIP_ID,
	SLIP.SUPPLIER_SLIP_ID,
	SLIP.MOVE_DEPOSIT_SLIP_ID,
	SLIP.STOCK_PDATE,
	SLIP.CRE_FUNC,
	SLIP.CRE_DATETM,
	SLIP.CRE_USER,
	SLIP.UPD_FUNC,
	SLIP.UPD_DATETM,
	SLIP.UPD_USER
FROM
	EAD_SLIP_TRN_/*$domainId*/ SLIP
	INNER JOIN EAD_LINE_TRN_/*$domainId*/ LINE ON SLIP.EAD_SLIP_ID = LINE.EAD_SLIP_ID
/*BEGIN*/
WHERE
	/*IF rackCode != null */
	AND LINE.RACK_CODE = /*rackCode*/
	/*END*/
	/*IF productCode != null */
	AND LINE.PRODUCT_CODE = /*productCode*/
	/*END*/
	/*IF stockPdate != null */
	AND SLIP.STOCK_PDATE = CAST(/*stockPdate*/ AS DATE)
	-- ELSE AND SLIP.STOCK_PDATE IS NULL
	/*END*/
	/*IF eadDate != null */
	AND SLIP.EAD_DATE <= CAST(/*eadDate*/ AS DATE)
	/*END*/
/*END*/
