INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','024','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','025','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','027','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','028','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','030','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','031','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','032','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','033','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','034','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','035','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','036','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','037','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','038','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','039','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','040','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','041','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','042','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','043','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','044','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','045','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','046','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','047','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','048','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','049','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','050','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','051','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','052','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','053','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','054','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','055','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','056','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','057','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','058','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','059','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','060','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','061','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','062','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','063','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','064','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','065','初期登録',now(),'ARK','初期登録',now(),'ARK');
-- INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','066','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','067','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','068','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','069','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','070','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','071','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','072','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','073','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','074','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','075','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','076','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','077','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','078','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','079','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','080','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','081','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','F02','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','089','初期登録',now(),'ARK','初期登録',now(),'ARK');

-- 委託入出庫
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','083','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','084','初期登録',now(),'ARK','初期登録',now(),'ARK');

-- 在庫照会
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','085','初期登録',now(),'ARK','初期登録',now(),'ARK');

-- 売掛締処理画面
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','086','初期登録',now(),'ARK','初期登録',now(),'ARK');

-- 商品ダウンロード/アップロード
INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','G01','初期登録',now(),'ARK','初期登録',now(),'ARK');

INSERT INTO GRANT_ROLE_XXXXX(USER_ID,ROLE_ID,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('SYSTEM','090','初期登録',now(),'ARK','初期登録',now(),'ARK');
