INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('001','0200','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('002','0300','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('003','0400','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('004','0600','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('005','0700','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('006','0800','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('007','0900','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('008','1000','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('009','1002','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('010','1202','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('011','1203','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('012','1300','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('013','1301','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('014','1302','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('015','1303','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('016','1305','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('017','1306','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('018','1309','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('019','1310','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('020','1311','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('021','1313','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('022','1314','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('023','1315','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('024','0200','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('025','0201','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
-- INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('026','0202','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('027','0300','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('028','0301','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
-- INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('029','0302','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('030','0303','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('031','0400','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('032','0401','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('033','0402','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('034','0403','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('035','0500','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('036','0501','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('037','0502','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('038','0600','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('039','0601','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('040','0603','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('041','0604','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('042','0700','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('043','0701','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('044','0702','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('045','0704','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('046','0800','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('047','0801','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('048','0900','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('049','0901','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('050','0902','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('051','1000','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('052','1001','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('053','1002','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('054','1003','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('055','1004','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('056','1005','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('057','1100','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('058','1101','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('059','1200','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('060','1201','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('061','1202','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('062','1203','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('063','1204','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('064','1205','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('065','1206','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
-- INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('066','1207','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('067','1300','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('068','1301','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('069','1302','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('070','1303','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('071','1305','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('072','1306','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('073','1309','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('074','1310','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('075','1311','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('076','1313','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('077','1314','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('078','1315','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('079','1316','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('F01','1407','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('F02','1407','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('080','0203','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('081','1102','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('088','1307','1','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('089','1307','2','初期登録',now(),'ARK','初期登録',now(),'ARK');

-- 委託入出庫 仮置き
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('082','1007','1','初期登録',now(),'ARK','初期登録',now(),'ARK');

INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('083','1007','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('084','1008','2','初期登録',now(),'ARK','初期登録',now(),'ARK');

-- 在庫照会 仮置き
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('085','1006','2','初期登録',now(),'ARK','初期登録',now(),'ARK');

-- 売掛締処理画面
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('086','0503','2','初期登録',now(),'ARK','初期登録',now(),'ARK');

-- 商品ダウンロード/アップロード
INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('G01','1500','2','初期登録',now(),'ARK','初期登録',now(),'ARK');

INSERT INTO ROLE_CFG_XXXXX (ROLE_ID,MENU_ID,VALID_FLAG,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('090','1207','2','初期登録',now(),'ARK','初期登録',now(),'ARK');
