INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('001','見積入力（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('002','受注入力（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('003','売上入力（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('004','入金入力（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('005','発注入力（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('006','仕入入力（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('007','支払入力（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('008','入出庫入力（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('009','在庫移動入力（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('010','部門情報（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('011','社員情報（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('012','商品（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('013','セット商品（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('014','顧客（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('015','仕入先（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('016','数量割引（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('017','棚番（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('018','区分（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('019','税（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('020','分類（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('021','レート（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('022','顧客ランク（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('023','銀行（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('024','見積入力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('025','見積検索',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('027','受注入力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('028','受注検索',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('030','オンライン受注データ取込',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('031','売上入力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('032','売上検索',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('033','売上帳票出力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('034','送り状データ出力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('035','請求検索',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('036','請求締処理',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('037','請求書発行',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('038','入金入力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('039','入金検索',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('040','配送業者入金データ取込',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('041','銀行入金データ取込',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('042','発注入力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('043','発注検索',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('044','発注書発行',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('045','補充発注推奨リスト出力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('046','仕入入力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('047','仕入検索',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('048','支払入力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('049','支払検索',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('050','支払実績締処理',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('051','入出庫入力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('052','入出庫検索',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('053','在庫移動入力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('054','在庫表出力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('055','在庫一覧表',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('056','在庫締処理',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('057','残高一覧表出力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('058','履歴参照',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('059','自社情報',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('060','在庫管理',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('061','部門情報',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('062','社員情報',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('063','おしらせ編集',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('064','ファイル登録',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('065','パスワード変更',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
-- INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('066','スケジュール',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('067','商品',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('068','セット商品',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('069','顧客',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('070','仕入先',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('071','数量割引',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('072','棚番',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('073','区分',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('074','税',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('075','分類',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('076','レート',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('077','顧客ランク',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('078','銀行',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('079','郵便番号辞書',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('F01','ファイル参照（一部可）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('F02','ファイル参照',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('080','単価照会',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('081','マスタリスト',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('088','倉庫（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('089','倉庫',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');

-- 委託入出庫
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('082','委託入出庫入力（参照）',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');

INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('083','委託入出庫入力',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('084','委託入出庫検索',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');

-- 在庫照会
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('085','在庫照会',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');

-- 売掛締処理画面
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('086','売掛締処理',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');

-- 商品ダウンロード/アップロード
INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('G01','商品ダウンロード/アップロード',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');

INSERT INTO ROLE_MST_XXXXX(ROLE_ID,NAME,REMARKS,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('090','セキュリティ設定',NULL,'初期登録',now(),'ARK','初期登録',now(),'ARK');
