INSERT INTO TAX_RATE_MST_XXXXX (TAX_TYPE_CATEGORY,START_DATE,TAX_RATE,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('1', '1995-01-01', 3, '初期登録',now(),'ARK', '初期登録',now(),'ARK');
INSERT INTO TAX_RATE_MST_XXXXX (TAX_TYPE_CATEGORY,START_DATE,TAX_RATE,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('1', '1998-04-01', 5, '初期登録',now(),'ARK', '初期登録',now(),'ARK');
INSERT INTO TAX_RATE_MST_XXXXX (TAX_TYPE_CATEGORY,START_DATE,TAX_RATE,CRE_FUNC,CRE_DATETM,CRE_USER,UPD_FUNC,UPD_DATETM,UPD_USER) VALUES ('1', '2014-04-01', 8, '初期登録',now(),'ARK', '初期登録',now(),'ARK');
