-- プロシージャ登録
SOURCE ./sp/SP_UPDATE_CUSTOMER_RANK_SALES.sql
SOURCE ./sp/SP_UPDATE_PRODUCT_STATUS_CATEGORY_SALES.sql
SOURCE ./sp/SP_UPDATE_PRODUCT_STOCK_VALUES_SALES.sql
SOURCE ./sp/SP_UPDATE_STDDEV_WORK_SALES.sql
SOURCE ./sp/SP_WRITE_LOG.sql