SELECT
	REL.HIST_ID,
	REL.ACTION_TYPE,
	REL.PRODUCT_CODE,
	REL.DISCOUNT_ID DISCOUNT_ID_CDX,
	MST.DISCOUNT_NAME DISCOUNT_NM,
	REL.REC_DATETM UPD_DATETM
FROM
	DISCOUNT_REL_HIST_/*$domainId*/ REL
		LEFT OUTER JOIN DISCOUNT_MST_HIST_/*$domainId*/ MST
			ON REL.DISCOUNT_ID = MST.DISCOUNT_ID
			   AND MST.REC_DATETM =
			   ( SELECT max(REC_DATETM)
			   	 FROM DISCOUNT_MST_HIST_/*$domainId*/ MST2
			 	 WHERE REC_DATETM <= REL.REC_DATETM
			 		AND REL.DISCOUNT_ID = MST2.DISCOUNT_ID
					GROUP BY DISCOUNT_ID
				)
WHERE
	REL.PRODUCT_CODE = /*productCode*/'S'
ORDER BY REL.HIST_ID
