LOCK TABLES
	PRODUCT_MST_/*$domainId*/ AS PRODUCT_MST_/*$domainId*/ WRITE,
	PRODUCT_MST_/*$domainId*/ AS P WRITE,
	PRODUCT_MST_HIST_/*$domainId*/ AS PRODUCT_MST_HIST_/*$domainId*/ WRITE,
	DISCOUNT_REL_/*$domainId*/ AS DISCOUNT_REL_/*$domainId*/ WRITE,
	DISCOUNT_REL_/*$domainId*/ AS DISREL WRITE,
	DISCOUNT_REL_HIST_/*$domainId*/ AS DISCOUNT_REL_HIST_/*$domainId*/ WRITE