SELECT
	R.WAREHOUSE_CODE,
	W.WAREHOUSE_NAME,
	R.RACK_CODE,
	P.PRODUCT_CODE,
	P.PRODUCT_NAME
FROM
	RACK_MST_/*$domainId*/ R INNER JOIN PRODUCT_MST_/*$domainId*/ P
	ON R.RACK_CODE=P.RACK_CODE
	LEFT OUTER JOIN WAREHOUSE_MST_/*$domainId*/ W
	ON R.WAREHOUSE_CODE = W.WAREHOUSE_CODE
/*BEGIN*/
WHERE
	/*IF rackCode != null*/
	R.RACK_CODE IN /*rackCode*/('R', 'R')
	/*END*/
/*END*/
ORDER BY
	R.RACK_CODE ASC,
	P.PRODUCT_CODE ASC