SELECT
	V.CUSTOMER_CODE
	,V.CUSTOMER_NAME
	,V.SALES_COUNT
	,V.DEPOSIT_COUNT
	,V.COV_PRICE
	,V.LAST_CUTOFF_DATE BILL_CUTOFF_DATE
FROM
  (
  SELECT
    C.CUSTOMER_CODE
    ,C.CUSTOMER_NAME
    ,C.LAST_CUTOFF_DATE
    ,(
		SELECT
		    count(D.CUSTOMER_CODE)
		FROM
			(
				SELECT
					D2.CUSTOMER_CODE
				FROM
					DEPOSIT_SLIP_TRN_/*$domainId*/ D2
				WHERE
					D2.DEPOSIT_DATE <= /*depositDate*/'2010/08/15'
					AND D2.SALES_CUTOFF_DATE is null
			) AS D
		WHERE
			C.CUSTOMER_CODE = D.CUSTOMER_CODE
		GROUP BY
			C.CUSTOMER_CODE
		    ,C.CUSTOMER_NAME
		    ,C.LAST_CUTOFF_DATE
		) AS DEPOSIT_COUNT

		,(
		SELECT
		    count(S.CUSTOMER_CODE)
		FROM
		    (
				SELECT
					S2.CUSTOMER_CODE
				FROM
					SALES_SLIP_TRN_/*$domainId*/ S2
				WHERE
					S2.SALES_DATE <= /*salesDate*/'2010/08/15'
					AND S2.SALES_CUTOFF_DATE is null
			) AS S

		WHERE
			C.CUSTOMER_CODE = S.CUSTOMER_CODE
		GROUP BY
			C.CUSTOMER_CODE
		    ,C.CUSTOMER_NAME
		    ,C.LAST_CUTOFF_DATE
		) AS SALES_COUNT
		,(
			SELECT
				A.COV_PRICE
			FROM
				ART_BALANCE_TRN_/*$domainId*/ A
            WHERE
                C.CUSTOMER_CODE = A.CUSTOMER_CODE
                AND C.LAST_CUTOFF_DATE = A.ART_CUTOFF_DATE
		) AS COV_PRICE
    FROM
        CUSTOMER_MST_/*$domainId*/ C
  ) V
WHERE
	( V.SALES_COUNT > 0 OR V.DEPOSIT_COUNT > 0  OR V.COV_PRICE <> 0 )
ORDER BY
	V.CUSTOMER_CODE ASC


