SELECT
	HIST_ID,
	ACTION_TYPE,
	DELIVERY_CODE ,
	DELIVERY_NAME 			BILL_DELIVERY_NAME,
	DELIVERY_KANA 			BILL_DELIVERY_KANA,
	DELIVERY_OFFICE_NAME 	BILL_DELIVERY_OFFICE_NAME,
	DELIVERY_OFFICE_KANA 	BILL_DELIVERY_OFFICE_KANA,
	DELIVERY_DEPT_NAME 		BILL_DELIVERY_DEPT_NAME,
	DELIVERY_ZIP_CODE 		BILL_DELIVERY_ZIP_CODE,
	DELIVERY_ADDRESS_1 		BILL_DELIVERY_ADDRESS_1,
	DELIVERY_ADDRESS_2 		BILL_DELIVERY_ADDRESS_2,
	DELIVERY_PC_NAME 		BILL_DELIVERY_PC_NAME,
	DELIVERY_PC_KANA 		BILL_DELIVERY_PC_KANA,
	DELIVERY_PC_PRE_CATEGORY BILL_PC_PRE_CATEGORY_CDX,
	CATT.CATEGORY_CODE_NAME BILL_CATEGORY_CODE_NAME,
	DELIVERY_TEL 			BILL_DELIVERY_TEL,
	DELIVERY_FAX 			BILL_DELIVERY_FAX,
	DELIVERY_EMAIL 			BILL_DELIVERY_EMAIL,
	REMARKS 				BILL_DELIVERY_REMARKS,
	HIST.REC_DATETM UPD_DATETM

FROM
    DELIVERY_MST_HIST_/*$domainId*/ HIST
        LEFT OUTER JOIN (
        	SELECT
        		CUSTOMER_CODE, REL_CODE, CUST_REL_CATEGORY
        	FROM
        		CUSTOMER_REL_HIST_/*$domainId*/ CRH
        	WHERE
        		CRH.CUSTOMER_CODE = /*customerCode*/'S'
				AND CRH.CUST_REL_CATEGORY = '02'
        	group by
        		CUSTOMER_CODE, REL_CODE, CUST_REL_CATEGORY ) R
            ON DELIVERY_CODE = R.REL_CODE
		LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CATT
        	ON DELIVERY_PC_PRE_CATEGORY = CATT.CATEGORY_CODE AND CATT.CATEGORY_ID=10
WHERE
	R.CUSTOMER_CODE = /*customerCode*/'S'
	AND R.CUST_REL_CATEGORY = '02'
ORDER BY DELIVERY_CODE, HIST_ID
