SELECT
		D1.DEPT_ID
		,D1.NAME
		,D1.PARENT_ID
		,D2.NAME AS PARENT_NAME
		,D1.CRE_FUNC
		,D1.CRE_DATETM
		,D1.CRE_USER
		,D1.UPD_FUNC
		,D1.UPD_DATETM
		,D1.UPD_USER
    FROM
        DEPT_MST_/*$domainId*/ D1 LEFT OUTER JOIN DEPT_MST_/*$domainId*/ D2
        ON D1.PARENT_ID = D2.DEPT_ID
	WHERE
		D1.DEPT_ID = /*deptId*/'S'