SELECT
		C.CATEGORY_ID
		,C.GROUP_NAME
		,C.CATEGORY_NAME
		,C.CATEGORY_ADD
		,C.CATEGORY_UPD
		,C.CATEGORY_DEL
		,C.CATEGORY_DSP
		,C.CATEGORY_DATA_TYPE
		,C.CATEGORY_STR_SIZE
		,C.CATEGORY_CODE_SIZE
		,C.CATEGORY_TITLE
		,CT.CATEGORY_ID
		,CT.CATEGORY_CODE
		,CT.CATEGORY_CODE_NAME
		,CT.CATEGORY_STR
		,CT.CATEGORY_NUM
		,CT.CATEGORY_FLT
		,CT.CATEGORY_BOOL
		,CT.CATEGORY_DSP AS CATEGORY_TRN_DSP
    FROM
        CATEGORY_MST_/*$domainId*/ C
        	LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CT
        ON (C.CATEGORY_ID=CT.CATEGORY_ID AND C.CATEGORY_ID=/*categoryId*/)
    WHERE
        CT.CATEGORY_DSP='1'
    ORDER BY
    	CT.CATEGORY_CODE ASC