 SELECT
    CATEGORY_ID
    ,GROUP_NAME
    ,CATEGORY_NAME AS NAME
	,CATEGORY_ADD
	,CATEGORY_UPD
	,CATEGORY_DEL
    ,CASE
		WHEN CATEGORY_ADD = 1 THEN 'true'
		WHEN CATEGORY_ADD = 0 THEN 'false'
		ELSE 'false'
	END AS IS_INSERT
    ,CASE
		WHEN CATEGORY_UPD = 1 THEN 'true'
		WHEN CATEGORY_UPD = 0 THEN 'false'
		ELSE 'false'
	END AS IS_UPDATE
    ,CASE
		WHEN CATEGORY_DEL = 1 THEN 'true'
		WHEN CATEGORY_DEL = 0 THEN 'false'
		ELSE 'false'
	END AS IS_DELETE
	,CATEGORY_DSP
    ,CATEGORY_DATA_TYPE
    ,CATEGORY_STR_SIZE
    ,CATEGORY_CODE_SIZE
    ,CATEGORY_TITLE
    ,CRE_FUNC
    ,CRE_DATETM
    ,CRE_USER
    ,UPD_FUNC
    ,UPD_DATETM
    ,UPD_USER
FROM
	CATEGORY_MST_/*$domainId*/
ORDER BY
	CATEGORY_ID ASC
