-- テーブル削除
DROP TRIGGER ENTRUST_EAD_LINE_TRN_XXXXX_INS;

DROP TRIGGER ENTRUST_EAD_LINE_TRN_XXXXX_UPD;

DROP TRIGGER ENTRUST_EAD_LINE_TRN_XXXXX_DEL;


DROP TRIGGER ENTRUST_EAD_SLIP_TRN_XXXXX_INS;

DROP TRIGGER ENTRUST_EAD_SLIP_TRN_XXXXX_UPD;

DROP TRIGGER ENTRUST_EAD_SLIP_TRN_XXXXX_DEL;


DROP TRIGGER BANK_DEPOSIT_REL_XXXXX_INS;

DROP TRIGGER BANK_DEPOSIT_REL_XXXXX_UPD;

DROP TRIGGER BANK_DEPOSIT_REL_XXXXX_DEL;


DROP TRIGGER DELIVERY_DEPOSIT_REL_XXXXX_INS;

DROP TRIGGER DELIVERY_DEPOSIT_REL_XXXXX_UPD;

DROP TRIGGER DELIVERY_DEPOSIT_REL_XXXXX_DEL;


DROP TRIGGER ONLINE_ORDER_REL_XXXXX_INS;

DROP TRIGGER ONLINE_ORDER_REL_XXXXX_UPD;

DROP TRIGGER ONLINE_ORDER_REL_XXXXX_DEL;


DROP TRIGGER FILE_INFO_XXXXX_INS;

DROP TRIGGER FILE_INFO_XXXXX_UPD;

DROP TRIGGER FILE_INFO_XXXXX_DEL;


DROP TRIGGER SCHEDULE_MST_XXXXX_INS;

DROP TRIGGER SCHEDULE_MST_XXXXX_UPD;

DROP TRIGGER SCHEDULE_MST_XXXXX_DEL;


DROP TRIGGER GRANT_ROLE_XXXXX_INS;

DROP TRIGGER GRANT_ROLE_XXXXX_UPD;

DROP TRIGGER GRANT_ROLE_XXXXX_DEL;


DROP TRIGGER USER_MST_XXXXX_INS;

DROP TRIGGER USER_MST_XXXXX_UPD;

DROP TRIGGER USER_MST_XXXXX_DEL;


DROP TRIGGER DEPT_MST_XXXXX_INS;

DROP TRIGGER DEPT_MST_XXXXX_UPD;

DROP TRIGGER DEPT_MST_XXXXX_DEL;


DROP TRIGGER DISCOUNT_REL_XXXXX_INS;

DROP TRIGGER DISCOUNT_REL_XXXXX_UPD;

DROP TRIGGER DISCOUNT_REL_XXXXX_DEL;


DROP TRIGGER DISCOUNT_TRN_XXXXX_INS;

DROP TRIGGER DISCOUNT_TRN_XXXXX_UPD;

DROP TRIGGER DISCOUNT_TRN_XXXXX_DEL;


DROP TRIGGER DISCOUNT_MST_XXXXX_INS;

DROP TRIGGER DISCOUNT_MST_XXXXX_UPD;

DROP TRIGGER DISCOUNT_MST_XXXXX_DEL;


DROP TRIGGER APT_BALANCE_TRN_XXXXX_INS;

DROP TRIGGER APT_BALANCE_TRN_XXXXX_UPD;

DROP TRIGGER APT_BALANCE_TRN_XXXXX_DEL;


DROP TRIGGER ART_BALANCE_TRN_XXXXX_INS;

DROP TRIGGER ART_BALANCE_TRN_XXXXX_UPD;

DROP TRIGGER ART_BALANCE_TRN_XXXXX_DEL;


DROP TRIGGER PAYMENT_LINE_TRN_XXXXX_INS;

DROP TRIGGER PAYMENT_LINE_TRN_XXXXX_UPD;

DROP TRIGGER PAYMENT_LINE_TRN_XXXXX_DEL;


DROP TRIGGER PAYMENT_SLIP_TRN_XXXXX_INS;

DROP TRIGGER PAYMENT_SLIP_TRN_XXXXX_UPD;

DROP TRIGGER PAYMENT_SLIP_TRN_XXXXX_DEL;


DROP TRIGGER EAD_LINE_TRN_XXXXX_INS;

DROP TRIGGER EAD_LINE_TRN_XXXXX_UPD;

DROP TRIGGER EAD_LINE_TRN_XXXXX_DEL;


DROP TRIGGER EAD_SLIP_TRN_XXXXX_INS;

DROP TRIGGER EAD_SLIP_TRN_XXXXX_UPD;

DROP TRIGGER EAD_SLIP_TRN_XXXXX_DEL;


DROP TRIGGER SUPPLIER_LINE_TRN_XXXXX_INS;

DROP TRIGGER SUPPLIER_LINE_TRN_XXXXX_UPD;

DROP TRIGGER SUPPLIER_LINE_TRN_XXXXX_DEL;


DROP TRIGGER SUPPLIER_SLIP_TRN_XXXXX_INS;

DROP TRIGGER SUPPLIER_SLIP_TRN_XXXXX_UPD;

DROP TRIGGER SUPPLIER_SLIP_TRN_XXXXX_DEL;


DROP TRIGGER PO_LINE_TRN_XXXXX_INS;

DROP TRIGGER PO_LINE_TRN_XXXXX_UPD;

DROP TRIGGER PO_LINE_TRN_XXXXX_DEL;


DROP TRIGGER PO_SLIP_TRN_XXXXX_INS;

DROP TRIGGER PO_SLIP_TRN_XXXXX_UPD;

DROP TRIGGER PO_SLIP_TRN_XXXXX_DEL;


DROP TRIGGER DEPOSIT_LINE_TRN_XXXXX_INS;

DROP TRIGGER DEPOSIT_LINE_TRN_XXXXX_UPD;

DROP TRIGGER DEPOSIT_LINE_TRN_XXXXX_DEL;


DROP TRIGGER DEPOSIT_SLIP_TRN_XXXXX_INS;

DROP TRIGGER DEPOSIT_SLIP_TRN_XXXXX_UPD;

DROP TRIGGER DEPOSIT_SLIP_TRN_XXXXX_DEL;


DROP TRIGGER BILL_TRN_XXXXX_INS;

DROP TRIGGER BILL_TRN_XXXXX_UPD;

DROP TRIGGER BILL_TRN_XXXXX_DEL;


DROP TRIGGER PICKING_LINE_TRN_XXXXX_INS;

DROP TRIGGER PICKING_LINE_TRN_XXXXX_UPD;

DROP TRIGGER PICKING_LINE_TRN_XXXXX_DEL;


DROP TRIGGER PICKING_LIST_TRN_XXXXX_INS;

DROP TRIGGER PICKING_LIST_TRN_XXXXX_UPD;

DROP TRIGGER PICKING_LIST_TRN_XXXXX_DEL;


DROP TRIGGER SALES_LINE_TRN_XXXXX_INS;

DROP TRIGGER SALES_LINE_TRN_XXXXX_UPD;

DROP TRIGGER SALES_LINE_TRN_XXXXX_DEL;


DROP TRIGGER SALES_SLIP_TRN_XXXXX_INS;

DROP TRIGGER SALES_SLIP_TRN_XXXXX_UPD;

DROP TRIGGER SALES_SLIP_TRN_XXXXX_DEL;


DROP TRIGGER RO_LINE_TRN_XXXXX_INS;

DROP TRIGGER RO_LINE_TRN_XXXXX_UPD;

DROP TRIGGER RO_LINE_TRN_XXXXX_DEL;


DROP TRIGGER RO_SLIP_TRN_XXXXX_INS;

DROP TRIGGER RO_SLIP_TRN_XXXXX_UPD;

DROP TRIGGER RO_SLIP_TRN_XXXXX_DEL;


DROP TRIGGER ESTIMATE_LINE_TRN_XXXXX_INS;

DROP TRIGGER ESTIMATE_LINE_TRN_XXXXX_UPD;

DROP TRIGGER ESTIMATE_LINE_TRN_XXXXX_DEL;


DROP TRIGGER ESTIMATE_SHEET_TRN_XXXXX_INS;

DROP TRIGGER ESTIMATE_SHEET_TRN_XXXXX_UPD;

DROP TRIGGER ESTIMATE_SHEET_TRN_XXXXX_DEL;


DROP TRIGGER PRODUCT_STOCK_TRN_XXXXX_INS;

DROP TRIGGER PRODUCT_STOCK_TRN_XXXXX_UPD;

DROP TRIGGER PRODUCT_STOCK_TRN_XXXXX_DEL;


DROP TRIGGER CUSTOMER_RANK_MST_XXXXX_INS;

DROP TRIGGER CUSTOMER_RANK_MST_XXXXX_UPD;

DROP TRIGGER CUSTOMER_RANK_MST_XXXXX_DEL;


DROP TRIGGER RATE_TRN_XXXXX_INS;

DROP TRIGGER RATE_TRN_XXXXX_UPD;

DROP TRIGGER RATE_TRN_XXXXX_DEL;


DROP TRIGGER RATE_MST_XXXXX_INS;

DROP TRIGGER RATE_MST_XXXXX_UPD;

DROP TRIGGER RATE_MST_XXXXX_DEL;


DROP TRIGGER BANK_MST_XXXXX_INS;

DROP TRIGGER BANK_MST_XXXXX_UPD;

DROP TRIGGER BANK_MST_XXXXX_DEL;


DROP TRIGGER TAX_RATE_MST_XXXXX_INS;

DROP TRIGGER TAX_RATE_MST_XXXXX_UPD;

DROP TRIGGER TAX_RATE_MST_XXXXX_DEL;


DROP TRIGGER CATEGORY_TRN_XXXXX_INS;

DROP TRIGGER CATEGORY_TRN_XXXXX_UPD;

DROP TRIGGER CATEGORY_TRN_XXXXX_DEL;


DROP TRIGGER SUPPLIER_MST_XXXXX_INS;

DROP TRIGGER SUPPLIER_MST_XXXXX_UPD;

DROP TRIGGER SUPPLIER_MST_XXXXX_DEL;


DROP TRIGGER CUSTOMER_REL_XXXXX_INS;

DROP TRIGGER CUSTOMER_REL_XXXXX_UPD;

DROP TRIGGER CUSTOMER_REL_XXXXX_DEL;


DROP TRIGGER DELIVERY_MST_XXXXX_INS;

DROP TRIGGER DELIVERY_MST_XXXXX_UPD;

DROP TRIGGER DELIVERY_MST_XXXXX_DEL;


DROP TRIGGER CUSTOMER_MST_XXXXX_INS;

DROP TRIGGER CUSTOMER_MST_XXXXX_UPD;

DROP TRIGGER CUSTOMER_MST_XXXXX_DEL;


DROP TRIGGER RACK_MST_XXXXX_INS;

DROP TRIGGER RACK_MST_XXXXX_UPD;

DROP TRIGGER RACK_MST_XXXXX_DEL;


DROP TRIGGER WAREHOUSE_MST_XXXXX_INS;

DROP TRIGGER WAREHOUSE_MST_XXXXX_UPD;

DROP TRIGGER WAREHOUSE_MST_XXXXX_DEL;


DROP TRIGGER PRODUCT_SET_MST_XXXXX_INS;

DROP TRIGGER PRODUCT_SET_MST_XXXXX_UPD;

DROP TRIGGER PRODUCT_SET_MST_XXXXX_DEL;


DROP TRIGGER PRODUCT_CLASS_MST_XXXXX_INS;

DROP TRIGGER PRODUCT_CLASS_MST_XXXXX_UPD;

DROP TRIGGER PRODUCT_CLASS_MST_XXXXX_DEL;


DROP TRIGGER PRODUCT_MST_XXXXX_INS;

DROP TRIGGER PRODUCT_MST_XXXXX_UPD;

DROP TRIGGER PRODUCT_MST_XXXXX_DEL;


DROP TRIGGER MINE_MST_XXXXX_INS;

DROP TRIGGER MINE_MST_XXXXX_UPD;

DROP TRIGGER MINE_MST_XXXXX_DEL;


DROP TABLE IF EXISTS BILL_OLD_XXXXX;

DROP TABLE IF EXISTS STDDEV_PRODUCT_XXXXX_YM_WORK_XXXXX;

DROP TABLE IF EXISTS STDDEV_AGGREGATE_YM_WORK_XXXXX;

DROP TABLE IF EXISTS STDDEV_YM_WORK_XXXXX;

DROP TABLE IF EXISTS STDDEV_AGGREGATE_DATA_WORK_XXXXX;

DROP TABLE IF EXISTS STDDEV_DATE_WORK_XXXXX;

DROP TABLE IF EXISTS ENTRUST_EAD_LINE_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS ENTRUST_EAD_LINE_TRN_XXXXX;

DROP TABLE IF EXISTS ENTRUST_EAD_SLIP_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS ENTRUST_EAD_SLIP_TRN_XXXXX;

DROP TABLE IF EXISTS CUSTOMER_SALES_TEMP_XXXXX;

DROP TABLE IF EXISTS CUSTOMER_RANK_SUMMARY_XXXXX;

DROP TABLE IF EXISTS BANK_DEPOSIT_REL_HIST_XXXXX;

DROP TABLE IF EXISTS BANK_DEPOSIT_REL_XXXXX;

DROP TABLE IF EXISTS DELIVERY_DEPOSIT_REL_HIST_XXXXX;

DROP TABLE IF EXISTS DELIVERY_DEPOSIT_REL_XXXXX;

DROP TABLE IF EXISTS ONLINE_ORDER_REL_HIST_XXXXX;

DROP TABLE IF EXISTS ONLINE_ORDER_REL_XXXXX;

DROP TABLE IF EXISTS FILE_INFO_HIST_XXXXX;

DROP TABLE IF EXISTS FILE_INFO_XXXXX;

DROP TABLE IF EXISTS SCHEDULE_MST_HIST_XXXXX;

DROP TABLE IF EXISTS SCHEDULE_MST_XXXXX;

DROP TABLE IF EXISTS NEWS_MST_XXXXX;

DROP TABLE IF EXISTS DETAIL_DISP_ITEM_CFG_XXXXX;

DROP TABLE IF EXISTS DETAIL_DISP_ITEM_MST_XXXXX;

DROP TABLE IF EXISTS GRANT_ROLE_HIST_XXXXX;

DROP TABLE IF EXISTS GRANT_ROLE_XXXXX;

DROP TABLE IF EXISTS ROLE_CFG_XXXXX;

DROP TABLE IF EXISTS ROLE_MST_XXXXX;

DROP TABLE IF EXISTS USER_MST_HIST_XXXXX;

DROP TABLE IF EXISTS USER_MST_XXXXX;

DROP TABLE IF EXISTS DEPT_MST_HIST_XXXXX;

DROP TABLE IF EXISTS DEPT_MST_XXXXX;

DROP TABLE IF EXISTS REPORT_TEMPLATE_MST_XXXXX;

DROP TABLE IF EXISTS MENU_MST_XXXXX;

DROP TABLE IF EXISTS DOMAIN_MST;

DROP TABLE IF EXISTS BATCH_LOG;

DROP TABLE IF EXISTS DISCOUNT_REL_HIST_XXXXX;

DROP TABLE IF EXISTS DISCOUNT_REL_XXXXX;

DROP TABLE IF EXISTS DISCOUNT_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS DISCOUNT_TRN_XXXXX;

DROP TABLE IF EXISTS DISCOUNT_MST_HIST_XXXXX;

DROP TABLE IF EXISTS DISCOUNT_MST_XXXXX;

DROP TABLE IF EXISTS BANK_DEPOSIT_WORK_XXXXX;

DROP TABLE IF EXISTS DELIVERY_DEPOSIT_WORK_XXXXX;

DROP TABLE IF EXISTS INVOICE_DATA_WORK_XXXXX;

DROP TABLE IF EXISTS ONLINE_ORDER_WORK_XXXXX;

DROP TABLE IF EXISTS APT_BALANCE_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS APT_BALANCE_TRN_XXXXX;

DROP TABLE IF EXISTS ART_BALANCE_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS ART_BALANCE_TRN_XXXXX;

DROP TABLE IF EXISTS PAYMENT_LINE_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS PAYMENT_LINE_TRN_XXXXX;

DROP TABLE IF EXISTS PAYMENT_SLIP_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS PAYMENT_SLIP_TRN_XXXXX;

DROP TABLE IF EXISTS EAD_LINE_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS EAD_LINE_TRN_XXXXX;

DROP TABLE IF EXISTS EAD_SLIP_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS EAD_SLIP_TRN_XXXXX;

DROP TABLE IF EXISTS SUPPLIER_LINE_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS SUPPLIER_LINE_TRN_XXXXX;

DROP TABLE IF EXISTS SUPPLIER_SLIP_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS SUPPLIER_SLIP_TRN_XXXXX;

DROP TABLE IF EXISTS PO_LINE_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS PO_LINE_TRN_XXXXX;

DROP TABLE IF EXISTS PO_SLIP_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS PO_SLIP_TRN_XXXXX;

DROP TABLE IF EXISTS DEPOSIT_LINE_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS DEPOSIT_LINE_TRN_XXXXX;

DROP TABLE IF EXISTS DEPOSIT_SLIP_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS DEPOSIT_SLIP_TRN_XXXXX;

DROP TABLE IF EXISTS BILL_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS BILL_TRN_XXXXX;

DROP TABLE IF EXISTS PICKING_LINE_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS PICKING_LINE_TRN_XXXXX;

DROP TABLE IF EXISTS PICKING_LIST_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS PICKING_LIST_TRN_XXXXX;

DROP TABLE IF EXISTS SALES_LINE_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS SALES_LINE_TRN_XXXXX;

DROP TABLE IF EXISTS SALES_SLIP_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS SALES_SLIP_TRN_XXXXX;

DROP TABLE IF EXISTS RO_LINE_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS RO_LINE_TRN_XXXXX;

DROP TABLE IF EXISTS RO_SLIP_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS RO_SLIP_TRN_XXXXX;

DROP TABLE IF EXISTS ESTIMATE_LINE_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS ESTIMATE_LINE_TRN_XXXXX;

DROP TABLE IF EXISTS ESTIMATE_SHEET_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS ESTIMATE_SHEET_TRN_XXXXX;

DROP TABLE IF EXISTS PRODUCT_STOCK_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS PRODUCT_STOCK_TRN_XXXXX;

DROP TABLE IF EXISTS CUSTOMER_RANK_MST_HIST_XXXXX;

DROP TABLE IF EXISTS CUSTOMER_RANK_MST_XXXXX;

DROP TABLE IF EXISTS RATE_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS RATE_TRN_XXXXX;

DROP TABLE IF EXISTS RATE_MST_HIST_XXXXX;

DROP TABLE IF EXISTS RATE_MST_XXXXX;

DROP TABLE IF EXISTS INIT_MST_XXXXX;

DROP TABLE IF EXISTS BANK_MST_HIST_XXXXX;

DROP TABLE IF EXISTS BANK_MST_XXXXX;

DROP TABLE IF EXISTS TAX_RATE_MST_HIST_XXXXX;

DROP TABLE IF EXISTS TAX_RATE_MST_XXXXX;

DROP TABLE IF EXISTS CATEGORY_TRN_HIST_XXXXX;

DROP TABLE IF EXISTS CATEGORY_TRN_XXXXX;

DROP TABLE IF EXISTS CATEGORY_MST_XXXXX;

DROP TABLE IF EXISTS ZIP_MST_XXXXX;

DROP TABLE IF EXISTS SUPPLIER_MST_HIST_XXXXX;

DROP TABLE IF EXISTS SUPPLIER_MST_XXXXX;

DROP TABLE IF EXISTS CUSTOMER_REL_HIST_XXXXX;

DROP TABLE IF EXISTS CUSTOMER_REL_XXXXX;

DROP TABLE IF EXISTS DELIVERY_MST_HIST_XXXXX;

DROP TABLE IF EXISTS DELIVERY_MST_XXXXX;

DROP TABLE IF EXISTS CUSTOMER_MST_HIST_XXXXX;

DROP TABLE IF EXISTS CUSTOMER_MST_XXXXX;

DROP TABLE IF EXISTS RACK_MST_HIST_XXXXX;

DROP TABLE IF EXISTS RACK_MST_XXXXX;

DROP TABLE IF EXISTS WAREHOUSE_MST_HIST_XXXXX;

DROP TABLE IF EXISTS WAREHOUSE_MST_XXXXX;

DROP TABLE IF EXISTS PRODUCT_SET_MST_HIST_XXXXX;

DROP TABLE IF EXISTS PRODUCT_SET_MST_XXXXX;

DROP TABLE IF EXISTS PRODUCT_CLASS_MST_HIST_XXXXX;

DROP TABLE IF EXISTS PRODUCT_CLASS_MST_XXXXX;

DROP TABLE IF EXISTS PRODUCT_MST_HIST_XXXXX;

DROP TABLE IF EXISTS PRODUCT_MST_XXXXX;

DROP TABLE IF EXISTS MINE_MST_HIST_XXXXX;

DROP TABLE IF EXISTS MINE_MST_XXXXX;

DROP TABLE IF EXISTS SEQ_MAKER_HIST_XXXXX;

DROP TABLE IF EXISTS SEQ_MAKER_XXXXX;

DROP TABLE IF EXISTS PASSWORD_MAKER_XXXXX;
