SELECT
		RANK_CODE
		,RANK_NAME
		,RANK_RATE
		,RO_COUNT_FROM
		,ENROLL_TERM_FROM
		,DEFECT_TERM_FROM
		,RO_MONTHLY_AVG_FROM
		,POSTAGE_TYPE
		,REMARKS
		,CRE_FUNC
		,CRE_DATETM
		,CRE_USER
		,UPD_FUNC
		,UPD_DATETM
		,UPD_USER
		,RO_COUNT_TO
		,ENROLL_TERM_TO
		,DEFECT_TERM_TO
		,RO_MONTHLY_AVG_TO
    FROM
        CUSTOMER_RANK_MST_/*$domainId*/
    ORDER BY
        RANK_CODE ASC