INSERT
    INTO DETAIL_DISP_ITEM_CFG_/*$domainId*/
        (
            USER_ID
            ,DETAIL_ID
            ,TARGET
            ,ITEM_ID
            ,SEQ
            ,CRE_FUNC
            ,CRE_DATETM
            ,CRE_USER
            ,UPD_FUNC
            ,UPD_DATETM
            ,UPD_USER
        )
    VALUES
        (
        	/*userId*/''
        	,/*detailId*/''
        	,/*target*/''
        	,/*itemId*/''
        	,/*seq*/0
        	,/*creFunc*/''
        	,now()
        	,/*creUser*/''
        	,/*updFunc*/''
        	,now()
        	,/*updUser*/''
        )