SELECT
		C.CATEGORY_ID
		,C.GROUP_NAME
		,C.CATEGORY_NAME
		,C.CATEGORY_ADD
		,C.CATEGORY_UPD
		,C.CATEGORY_DEL
		,C.CATEGORY_DSP
		,C.CATEGORY_DATA_TYPE
		,C.CATEGORY_STR_SIZE
		,C.CATEGORY_CODE_SIZE
		,C.CATEGORY_TITLE
		,C.CRE_DATETM
		,C.UPD_DATETM
    FROM
        CATEGORY_MST_/*$domainId*/ C
    WHERE
        C.CATEGORY_ID=/*categoryId*/
