SELECT
	LINE.RACK_CODE
	,LINE.PRODUCT_CODE
	,SLIP.EAD_CATEGORY
	,SUM(LINE.QUANTITY) AS QUANTITY
FROM
	EAD_SLIP_TRN_/*$domainId*/ SLIP
	INNER JOIN EAD_LINE_TRN_/*$domainId*/ LINE ON SLIP.EAD_SLIP_ID = LINE.EAD_SLIP_ID
WHERE
	SLIP.STOCK_PDATE IS NULL
	AND SLIP.EAD_DATE <= CAST(/*eadDate*/ AS DATE)
	/*IF rackCode != null */
	AND LINE.RACK_CODE = /*rackCode*/
	/*END*/
	/*IF productCode != null */
	AND LINE.PRODUCT_CODE = /*productCode*/
	/*END*/
GROUP BY LINE.RACK_CODE, LINE.PRODUCT_CODE, SLIP.EAD_CATEGORY
