SELECT
	LINE.PRODUCT_CODE
	,LINE.RACK_CODE
FROM
	EAD_SLIP_TRN_/*$domainId*/ SLIP
	INNER JOIN EAD_LINE_TRN_/*$domainId*/ LINE ON SLIP.EAD_SLIP_ID = LINE.EAD_SLIP_ID
/*BEGIN*/
WHERE
	/*IF stockPdate != null */
	AND SLIP.STOCK_PDATE = CAST(/*stockPdate*/ AS DATE)
	-- ELSE AND SLIP.STOCK_PDATE IS NULL
	/*END*/
	/*IF eadDate != null */
	AND SLIP.EAD_DATE <= CAST(/*eadDate*/ AS DATE)
	/*END*/
/*END*/
GROUP BY
	LINE.PRODUCT_CODE
	,LINE.RACK_CODE
