SELECT
	DISTINCT
	CONCAT(CAST(LINE.SUPPLIER_SLIP_ID AS CHAR),' - ',CAST(LINE.LINE_NO AS CHAR)) AS SUPPLIER_SLIP_ID,
	CONCAT(CAST(PO_LINE.PO_SLIP_ID AS CHAR),' - ',CAST(PO_LINE.LINE_NO AS CHAR)) AS PO_SLIP_ID,
	CONCAT(CAST(PY_LINE.PAYMENT_SLIP_ID AS CHAR),' - ',CAST(PY_LINE.LINE_NO AS CHAR)) AS PAYMENT_SLIP_ID,
	SLIP.SUPPLIER_DATE,
	SLIP.DELIVERY_DATE,
	CAT1.CATEGORY_CODE_NAME AS SUPPLIER_SLIP_CATEGORY,
	SLIP.REMARKS,
	SLIP.SUPPLIER_CODE,
	SLIP.SUPPLIER_NAME,
	CAT2.CATEGORY_CODE_NAME AS SUPPLIER_CM_CATEGORY,
	LINE.PRODUCT_CODE,
	LINE.PRODUCT_ABSTRACT,
	LINE.SUPPLIER_PCODE,
	LINE.DELIVERY_DATE AS DELIVERY_DETAIL_DATE,
	CAT3.CATEGORY_CODE_NAME AS SUPPLIER_DETAIL_CATEGORY,
	CAT4.CATEGORY_CODE_NAME AS DELIVERY_PROCESS_CATEGORY,
	CAT5.CATEGORY_CODE_NAME AS TEMP_UNIT_PRICE_CATEGORY,
	CAT6.CATEGORY_CODE_NAME AS TAX_CATEGORY,
	LINE.QUANTITY,
	LINE.UNIT_PRICE,
	LINE.PRICE,
	LINE.CTAX_PRICE,
	LINE.DOL_UNIT_PRICE,
	LINE.DOL_PRICE,
	LINE.REMARKS AS LINE_REMARKS,
	LINE.PRODUCT_REMARKS,
	LINE.RACK_CODE,
	LINE.RATE,
	LINE.SUPPLIER_SLIP_ID AS SORT_SUPPLIER_SLIP_ID,
	LINE.LINE_NO AS SORT_SUPPLIER_LINE_NO,
	PO_LINE.PO_SLIP_ID AS SORT_PO_SLIP_ID,
	PO_LINE.LINE_NO AS SORT_PO_LINE_NO,
	PY_LINE.PAYMENT_SLIP_ID SORT_PAYMENT_SLIP_ID,
	PY_LINE.LINE_NO AS SORT_PAYMENT_LINE_NO
FROM
	SUPPLIER_SLIP_TRN_/*$domainId*/ SLIP
	INNER JOIN SUPPLIER_LINE_TRN_/*$domainId*/ LINE ON SLIP.SUPPLIER_SLIP_ID = LINE.SUPPLIER_SLIP_ID
	LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CAT1
		ON SLIP.SUPPLIER_SLIP_CATEGORY = CAT1.CATEGORY_CODE AND CAT1.CATEGORY_ID = /*supplierSlipCategory*/57
	LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CAT2
		ON SLIP.SUPPLIER_CM_CATEGORY = CAT2.CATEGORY_CODE AND CAT2.CATEGORY_ID = /*supplierCmCategory*/13
	LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CAT3
		ON LINE.SUPPLIER_DETAIL_CATEGORY = CAT3.CATEGORY_CODE AND CAT3.CATEGORY_ID = /*supplierDetailCategory*/6
	LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CAT4
		ON LINE.DELIVERY_PROCESS_CATEGORY = CAT4.CATEGORY_CODE AND CAT4.CATEGORY_ID = /*deliveryProcessCategoryMst*/30
	LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CAT5
		ON LINE.TEMP_UNIT_PRICE_CATEGORY = CAT5.CATEGORY_CODE AND CAT5.CATEGORY_ID = /*tempUnitPriceCategory*/56
	LEFT OUTER JOIN CATEGORY_TRN_/*$domainId*/ CAT6
		ON LINE.TAX_CATEGORY = CAT6.CATEGORY_CODE AND CAT6.CATEGORY_ID = /*taxCategory*/39
	LEFT OUTER JOIN PRODUCT_MST_/*$domainId*/ PROD ON LINE.PRODUCT_CODE = PROD.PRODUCT_CODE
	LEFT OUTER JOIN PO_LINE_TRN_/*$domainId*/ PO_LINE ON LINE.PO_LINE_ID = PO_LINE.PO_LINE_ID
	LEFT OUTER JOIN PAYMENT_LINE_TRN_/*$domainId*/ PY_LINE ON LINE.PAYMENT_LINE_ID = PY_LINE.PAYMENT_LINE_ID
/*BEGIN*/
WHERE
	/*IF supplierSlipId != null */
	AND SLIP.SUPPLIER_SLIP_ID = /*supplierSlipId*/1
	/*END*/
	/*IF poSlipId != null */
	AND SLIP.PO_SLIP_ID = /*poSlipId*/1
	/*END*/
	/*IF userName != null */
	AND SLIP.USER_NAME like /*userName*/'S%'
	/*END*/
	/*IF supplierDateFrom != null */
	AND SLIP.SUPPLIER_DATE >= CAST(/*supplierDateFrom*/'2000/01/01' AS DATE)
	/*END*/
	/*IF supplierDateTo != null */
	AND SLIP.SUPPLIER_DATE <= CAST(/*supplierDateTo*/'2000/01/01' AS DATE)
	/*END*/
	/*IF deliveryProcessCategory != null */
	AND LINE.DELIVERY_PROCESS_CATEGORY IN /*deliveryProcessCategory*/('1','2')
	/*END*/
	/*IF supplierCode != null */
	AND SLIP.SUPPLIER_CODE LIKE /*supplierCode*/'S%'
	/*END*/
	/*IF supplierName != null */
	AND SLIP.SUPPLIER_NAME LIKE /*supplierName*/'%S%'
	/*END*/
	/*IF remarks != null */
	AND SLIP.REMARKS LIKE /*remarks*/'%S%'
	/*END*/
	/*IF productCode != null */
	AND LINE.PRODUCT_CODE LIKE /*productCode*/'S%'
	/*END*/
	/*IF productAbstract != null */
	AND LINE.PRODUCT_ABSTRACT LIKE /*productAbstract*/'%S%'
	/*END*/
	/*IF product1 != null */
	AND PROD.PRODUCT_1 = /*product1*/'S'
	/*END*/
	/*IF product2 != null */
	AND PROD.PRODUCT_2 = /*product2*/'S'
	/*END*/
	/*IF product3 != null */
	AND PROD.PRODUCT_3 = /*product3*/'S'
	/*END*/
/*END*/
/*BEGIN*/
	ORDER BY

		/*IF sortColumn != null */
			/*$sortColumn*/
			/*IF sortOrderAsc != null*/
			/*$sortOrderAsc*/
			-- ELSE ASC
			/*END*/
		/*END*/

		/*IF sortColumnSlip != null */
			/*$sortColumnSlip*/
			/*IF sortOrderAsc != null*/
				/*$sortOrderAsc*/
				-- ELSE ASC
			/*END*/
		/*END*/
		/*IF sortColumnLine != null */
			/*IF sortColumnSlip != null */,/*END*/
			/*$sortColumnLine*/
			/*IF sortOrderAsc != null*/
			/*$sortOrderAsc*/
			-- ELSE ASC
			/*END*/
		/*END*/
/*END*/
/*IF rowCount != null && offsetRow != null*/
	LIMIT /*rowCount*/ OFFSET /*offsetRow*/
/*END*/