SELECT
	S.SUPPLIER_LINE_ID
	,S.STATUS
	,S.SUPPLIER_SLIP_ID
	,S.LINE_NO
	,S.PRODUCT_CODE
	,S.SUPPLIER_PCODE
	,S.PRODUCT_ABSTRACT
	,S.SUPPLIER_DETAIL_CATEGORY
	,S.DELIVERY_PROCESS_CATEGORY
	,S.TEMP_UNIT_PRICE_CATEGORY
	,S.TAX_CATEGORY
	,S.DELIVERY_DATE
	,S.QUANTITY
	,S.UNIT_PRICE
	,S.PRICE
	,S.CTAX_RATE
	,S.CTAX_PRICE
	,S.DOL_UNIT_PRICE
	,S.DOL_PRICE
	,S.RATE
	,S.REMARKS
	,S.RACK_CODE
	,S.RACK_NAME
	,S.PO_LINE_ID
	,S.PAYMENT_LINE_ID
	,S.PRODUCT_REMARKS
	,S.CRE_FUNC
	,S.CRE_DATETM
	,S.CRE_USER
	,S.UPD_FUNC
	,S.UPD_DATETM
	,S.UPD_USER
FROM
	SUPPLIER_LINE_TRN_/*$domainId*/ S
WHERE
	S.SUPPLIER_LINE_ID <> /*supplierLineId*/0
	AND S.PO_LINE_ID = /*poLineId*/0
